// Code generated by wit-bindgen-go. DO NOT EDIT.

package profiling

// This file contains wasmimport and wasmexport declarations for "slicer:common".

//go:wasmimport slicer:common/profiling profile-enabled
//go:noescape
func wasmimport_ProfileEnabled() (result0 uint32)

//go:wasmimport slicer:common/profiling profile-register
//go:noescape
func wasmimport_ProfileRegister(name0 *uint8, name1 uint32) (result0 uint32)

//go:wasmimport slicer:common/profiling profile-mark
//go:noescape
func wasmimport_ProfileMark(scope0 uint32, edge0 uint32)
