// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package profiling represents the imported interface "slicer:common/profiling".
//
// Fuel-based module profiling (ADR-0050).
//
// Deliberately a **separate interface** from `host-services` rather than three
// more functions on it: profiling is host-gated diagnostic plumbing with a
// different lifetime and a different audience than the geometry/mesh services,
// and keeping it apart means a world can import one without the other.
//
// A guest cannot read a clock (`wasm32-unknown-unknown` has no WASI) and cannot
// read its own fuel. So the guest only says *where* it is; the host samples
// *what it costs* at that instant. Because a mark is a host call, it burns no
// fuel and therefore cannot pollute the measurement it is taking.
package profiling

import (
	"go.bytecodealliance.org/cm"
)

// MarkEdge represents the enum "slicer:common/profiling#mark-edge".
//
// Which side of a scope a mark sits on. Marks nest: the host keeps a
// per-call stack so both self and total cost are recoverable.
//
//	enum mark-edge {
//		enter,
//		exit
//	}
type MarkEdge uint8

const (
	MarkEdgeEnter MarkEdge = iota
	MarkEdgeExit
)

var _MarkEdgeStrings = [2]string{
	"enter",
	"exit",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e MarkEdge) String() string {
	return _MarkEdgeStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e MarkEdge) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *MarkEdge) UnmarshalText(text []byte) error {
	return _MarkEdgeUnmarshalCase(e, text)
}

var _MarkEdgeUnmarshalCase = cm.CaseUnmarshaler[MarkEdge](_MarkEdgeStrings[:])

// ProfileEnabled represents the imported function "profile-enabled".
//
// Whether the host is recording marks at all. Guests are expected to cache
// this once per instance and branch on the cached bool, so the steady-state
// cost with profiling off is a predictable branch rather than a host call.
//
//	profile-enabled: func() -> bool
//
//go:nosplit
func ProfileEnabled() (result bool) {
	result0 := wasmimport_ProfileEnabled()
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// ProfileRegister represents the imported function "profile-register".
//
// Interns `name` and returns its scope id, allocating one on first sight.
//
// The registry is process-global and append-only, so an id stays valid for
// the whole run even though each dispatch call gets a fresh guest instance
// (and therefore a fresh copy of whatever the guest cached). Re-registering
// a name always returns the same id.
//
// Ids below `slicer_core::profile::ScopeId::USER_BASE` are reserved for
// `slicer-core`'s own scopes and are never handed out by this function.
//
//	profile-register: func(name: string) -> u32
//
//go:nosplit
func ProfileRegister(name string) (result uint32) {
	name0, name1 := cm.LowerString(name)
	result0 := wasmimport_ProfileRegister((*uint8)(name0), (uint32)(name1))
	result = (uint32)((uint32)(result0))
	return
}

// ProfileMark represents the imported function "profile-mark".
//
// Records one scope transition. The host attaches consumed fuel and a
// wall-clock reading taken at this instant.
//
//	profile-mark: func(scope: u32, edge: mark-edge)
//
//go:nosplit
func ProfileMark(scope uint32, edge MarkEdge) {
	scope0 := (uint32)(scope)
	edge0 := (uint32)(edge)
	wasmimport_ProfileMark((uint32)(scope0), (uint32)(edge0))
	return
}
