// Code generated by wit-bindgen-go. DO NOT EDIT.

package hostservices

import (
	"foreign-language-text-postprocess/slicer/types/geometry"
	"go.bytecodealliance.org/cm"
	"unsafe"
)

func lower_Polygon(v geometry.Polygon) (f0 *geometry.Point2, f1 uint32) {
	f0, f1 = cm.LowerList(v.Points)
	return
}

func lower_ExPolygon(v geometry.ExPolygon) (f0 *geometry.Point2, f1 uint32, f2 *geometry.Polygon, f3 uint32) {
	f0, f1 = lower_Polygon(v.Contour)
	f2, f3 = cm.LowerList(v.Holes)
	return
}

// TupleListExtrusionLineListExtrusionLineShape is used for storage in variant or result types.
type TupleListExtrusionLineListExtrusionLineShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof([2]cm.List[ExtrusionLine]{})]byte
}
