// Code generated by wit-bindgen-go. DO NOT EDIT.

package hostservices

import (
	"foreign-language-text-postprocess/slicer/types/geometry"
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "slicer:common".

//go:wasmimport slicer:common/host-services log
//go:noescape
func wasmimport_Log(level0 uint32, message0 *uint8, message1 uint32)

//go:wasmimport slicer:common/host-services raycast-z-down
//go:noescape
func wasmimport_RaycastZDown(objectId0 *uint8, objectId1 uint32, x0 float32, y0 float32, startZ0 float32, result *cm.Option[float32])

//go:wasmimport slicer:common/host-services surface-normal-at
//go:noescape
func wasmimport_SurfaceNormalAt(objectId0 *uint8, objectId1 uint32, x0 float32, y0 float32, z0 float32, result *cm.Option[Point3])

//go:wasmimport slicer:common/host-services object-bounds
//go:noescape
func wasmimport_ObjectBounds(objectId0 *uint8, objectId1 uint32, result *BoundingBox3)

//go:wasmimport slicer:common/host-services clip-polygons
//go:noescape
func wasmimport_ClipPolygons(subject0 *ExPolygon, subject1 uint32, clip0 *ExPolygon, clip1 uint32, op0 uint32, result *cm.List[ExPolygon])

//go:wasmimport slicer:common/host-services offset-polygons
//go:noescape
func wasmimport_OffsetPolygons(polygons0 *ExPolygon, polygons1 uint32, deltaMm0 float32, join0 uint32, arcToleranceMm0 float32, result *cm.List[ExPolygon])

//go:wasmimport slicer:common/host-services simplify-polygon
//go:noescape
func wasmimport_SimplifyPolygon(polygon0 *geometry.Point2, polygon1 uint32, toleranceMm0 float32, result *Polygon)

//go:wasmimport slicer:common/host-services offset-polygons-batch
//go:noescape
func wasmimport_OffsetPolygonsBatch(requests0 *OffsetRequest, requests1 uint32, result *cm.List[cm.List[ExPolygon]])

//go:wasmimport slicer:common/host-services clip-polygons-batch
//go:noescape
func wasmimport_ClipPolygonsBatch(requests0 *ClipRequest, requests1 uint32, result *cm.List[cm.List[ExPolygon]])

//go:wasmimport slicer:common/host-services simplify-polygon-batch
//go:noescape
func wasmimport_SimplifyPolygonBatch(requests0 *SimplifyRequest, requests1 uint32, result *cm.List[Polygon])

//go:wasmimport slicer:common/host-services raycast-z-down-batch
//go:noescape
func wasmimport_RaycastZDownBatch(requests0 *RaycastRequest, requests1 uint32, result *cm.List[cm.Option[float32]])

//go:wasmimport slicer:common/host-services surface-normal-at-batch
//go:noescape
func wasmimport_SurfaceNormalAtBatch(requests0 *SurfaceNormalRequest, requests1 uint32, result *cm.List[cm.Option[Point3]])

//go:wasmimport slicer:common/host-services medial-axis
//go:noescape
func wasmimport_MedialAxis(input0 *geometry.Point2, input1 uint32, input2 *geometry.Polygon, input3 uint32, minWidth0 float32, maxWidth0 float32, result *cm.Result[cm.List[ThickPolyline], cm.List[ThickPolyline], string])

//go:wasmimport slicer:common/host-services generate-arachne-walls
//go:noescape
func wasmimport_GenerateArachneWalls(params *wasmimport_GenerateArachneWalls_params, result *cm.Result[TupleListExtrusionLineListExtrusionLineShape, [2]cm.List[ExtrusionLine], string])

//go:wasmimport slicer:common/host-services now-us
//go:noescape
func wasmimport_NowUs() (result0 uint64)
