// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package hostservices represents the imported interface "slicer:common/host-services".
package hostservices

import (
	irhandles "foreign-language-text-postprocess/slicer/ir-handles/ir-handles"
	"foreign-language-text-postprocess/slicer/types/geometry"
	"go.bytecodealliance.org/cm"
)

// Point3 represents the type alias "slicer:common/host-services#point3".
//
// See [geometry.Point3] for more information.
type Point3 = geometry.Point3

// BoundingBox3 represents the type alias "slicer:common/host-services#bounding-box3".
//
// See [geometry.BoundingBox3] for more information.
type BoundingBox3 = geometry.BoundingBox3

// ExPolygon represents the type alias "slicer:common/host-services#ex-polygon".
//
// See [geometry.ExPolygon] for more information.
type ExPolygon = geometry.ExPolygon

// Polygon represents the type alias "slicer:common/host-services#polygon".
//
// See [geometry.Polygon] for more information.
type Polygon = geometry.Polygon

// ThickPolyline represents the type alias "slicer:common/host-services#thick-polyline".
//
// See [geometry.ThickPolyline] for more information.
type ThickPolyline = geometry.ThickPolyline

// ExtrusionLine represents the type alias "slicer:common/host-services#extrusion-line".
//
// See [irhandles.ExtrusionLine] for more information.
type ExtrusionLine = irhandles.ExtrusionLine

// ObjectID represents the string "slicer:common/host-services#object-id".
//
//	type object-id = string
type ObjectID string

// LogLevel represents the enum "slicer:common/host-services#log-level".
//
//	enum log-level {
//		trace,
//		debug,
//		info,
//		warn,
//		error
//	}
type LogLevel uint8

const (
	LogLevelTrace LogLevel = iota
	LogLevelDebug
	LogLevelInfo
	LogLevelWarn
	LogLevelError
)

var _LogLevelStrings = [5]string{
	"trace",
	"debug",
	"info",
	"warn",
	"error",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e LogLevel) String() string {
	return _LogLevelStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e LogLevel) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *LogLevel) UnmarshalText(text []byte) error {
	return _LogLevelUnmarshalCase(e, text)
}

var _LogLevelUnmarshalCase = cm.CaseUnmarshaler[LogLevel](_LogLevelStrings[:])

// ClipOperation represents the enum "slicer:common/host-services#clip-operation".
//
//	enum clip-operation {
//		union,
//		intersection,
//		difference,
//		xor
//	}
type ClipOperation uint8

const (
	ClipOperationUnion ClipOperation = iota
	ClipOperationIntersection
	ClipOperationDifference
	ClipOperationXor
)

var _ClipOperationStrings = [4]string{
	"union",
	"intersection",
	"difference",
	"xor",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e ClipOperation) String() string {
	return _ClipOperationStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e ClipOperation) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *ClipOperation) UnmarshalText(text []byte) error {
	return _ClipOperationUnmarshalCase(e, text)
}

var _ClipOperationUnmarshalCase = cm.CaseUnmarshaler[ClipOperation](_ClipOperationStrings[:])

// OffsetJoinType represents the enum "slicer:common/host-services#offset-join-type".
//
//	enum offset-join-type {
//		miter,
//		round,
//		square
//	}
type OffsetJoinType uint8

const (
	OffsetJoinTypeMiter OffsetJoinType = iota
	OffsetJoinTypeRound
	OffsetJoinTypeSquare
)

var _OffsetJoinTypeStrings = [3]string{
	"miter",
	"round",
	"square",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e OffsetJoinType) String() string {
	return _OffsetJoinTypeStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e OffsetJoinType) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *OffsetJoinType) UnmarshalText(text []byte) error {
	return _OffsetJoinTypeUnmarshalCase(e, text)
}

var _OffsetJoinTypeUnmarshalCase = cm.CaseUnmarshaler[OffsetJoinType](_OffsetJoinTypeStrings[:])

// WallSequence represents the enum "slicer:common/host-services#wall-sequence".
//
//	enum wall-sequence {
//		inner-outer,
//		outer-inner,
//		inner-outer-inner
//	}
type WallSequence uint8

const (
	WallSequenceInnerOuter WallSequence = iota
	WallSequenceOuterInner
	WallSequenceInnerOuterInner
)

var _WallSequenceStrings = [3]string{
	"inner-outer",
	"outer-inner",
	"inner-outer-inner",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e WallSequence) String() string {
	return _WallSequenceStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e WallSequence) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *WallSequence) UnmarshalText(text []byte) error {
	return _WallSequenceUnmarshalCase(e, text)
}

var _WallSequenceUnmarshalCase = cm.CaseUnmarshaler[WallSequence](_WallSequenceStrings[:])

// OffsetRequest represents the record "slicer:common/host-services#offset-request".
//
// ── Batched forms ────────────────────────────────────────────────────
//
// A guest that calls one of these once, instead of calling the singular
// form in a loop, lets the host run the items concurrently on the rayon
// pool it already owns. The guest itself stays single-threaded: the whole
// batch crosses the boundary in one call, so nothing re-enters the host
// concurrently and no host service has to be safe against that.
//
// Results are returned in **input order**, always — the i-th result
// corresponds to the i-th request whether the host ran the batch serially
// or in parallel. Output therefore cannot depend on worker count or
// scheduling.
//
// Parameters are per item rather than shared across the batch, so a caller
// whose deltas or operations vary does not have to fall back to a loop.
//
// The host decides serially-or-parallel from an estimated-work model, not
// from item count; see `batch` in the host implementation. Callers should
// batch whatever is naturally independent and leave that choice alone.
//
// `medial-axis` and `generate-arachne-walls` deliberately have no batch
// form — see ADR-0049.
//
//	record offset-request {
//		polygons: list<ex-polygon>,
//		delta-mm: f32,
//		join: offset-join-type,
//		arc-tolerance-mm: f32,
//	}
type OffsetRequest struct {
	_              cm.HostLayout      `json:"-"`
	Polygons       cm.List[ExPolygon] `json:"polygons"`
	DeltaMm        float32            `json:"delta-mm"`
	Join           OffsetJoinType     `json:"join"`
	ArcToleranceMm float32            `json:"arc-tolerance-mm"`
}

// ClipRequest represents the record "slicer:common/host-services#clip-request".
//
//	record clip-request {
//		subject: list<ex-polygon>,
//		clip: list<ex-polygon>,
//		op: clip-operation,
//	}
type ClipRequest struct {
	_       cm.HostLayout      `json:"-"`
	Subject cm.List[ExPolygon] `json:"subject"`
	Clip    cm.List[ExPolygon] `json:"clip"`
	Op      ClipOperation      `json:"op"`
}

// SimplifyRequest represents the record "slicer:common/host-services#simplify-request".
//
//	record simplify-request {
//		polygon: polygon,
//		tolerance-mm: f32,
//	}
type SimplifyRequest struct {
	_           cm.HostLayout `json:"-"`
	Polygon     Polygon       `json:"polygon"`
	ToleranceMm float32       `json:"tolerance-mm"`
}

// RaycastRequest represents the record "slicer:common/host-services#raycast-request".
//
//	record raycast-request {
//		object-id: object-id,
//		x: f32,
//		y: f32,
//		start-z: f32,
//	}
type RaycastRequest struct {
	_        cm.HostLayout `json:"-"`
	ObjectID ObjectID      `json:"object-id"`
	X        float32       `json:"x"`
	Y        float32       `json:"y"`
	StartZ   float32       `json:"start-z"`
}

// SurfaceNormalRequest represents the record "slicer:common/host-services#surface-normal-request".
//
//	record surface-normal-request {
//		object-id: object-id,
//		x: f32,
//		y: f32,
//		z: f32,
//	}
type SurfaceNormalRequest struct {
	_        cm.HostLayout `json:"-"`
	ObjectID ObjectID      `json:"object-id"`
	X        float32       `json:"x"`
	Y        float32       `json:"y"`
	Z        float32       `json:"z"`
}

// ArachneParams represents the record "slicer:common/host-services#arachne-params".
//
// Parameters for `generate-arachne-walls`, mirroring
// `slicer_core::arachne::pipeline::ArachneParams` field-for-field
// (packet 112, Step 9A). Every distance/width field is in millimeters,
// matching `medial-axis`'s `min-width`/`max-width` convention above.
//
//	record arachne-params {
//		optimal-width: f32,
//		preferred-bead-width-outer: f32,
//		max-bead-count: u32,
//		distribution-count: u32,
//		transition-filter-dist: f32,
//		min-central-distance: f32,
//		min-length-factor: f32,
//		min-width: f32,
//		print-thin-walls: bool,
//		min-feature-size: f32,
//		min-bead-width: f32,
//		wall-transition-length: f32,
//		wall-transition-angle: f32,
//		initial-layer-min-bead-width: f32,
//		outer-wall-offset: f32,
//		is-initial-layer: bool,
//		is-bottom-layer: bool,
//		is-topmost-layer: bool,
//		smallest-line-segment-squared: f32,
//		allowed-error-distance-squared: f32,
//		maximum-extrusion-area-deviation: f32,
//		wall-sequence: wall-sequence,
//	}
type ArachneParams struct {
	_                        cm.HostLayout `json:"-"`
	OptimalWidth             float32       `json:"optimal-width"`
	PreferredBeadWidthOuter  float32       `json:"preferred-bead-width-outer"`
	MaxBeadCount             uint32        `json:"max-bead-count"`
	DistributionCount        uint32        `json:"distribution-count"`
	TransitionFilterDist     float32       `json:"transition-filter-dist"`
	MinCentralDistance       float32       `json:"min-central-distance"`
	MinLengthFactor          float32       `json:"min-length-factor"`
	MinWidth                 float32       `json:"min-width"`
	PrintThinWalls           bool          `json:"print-thin-walls"`
	MinFeatureSize           float32       `json:"min-feature-size"`
	MinBeadWidth             float32       `json:"min-bead-width"`
	WallTransitionLength     float32       `json:"wall-transition-length"`
	WallTransitionAngle      float32       `json:"wall-transition-angle"`
	InitialLayerMinBeadWidth float32       `json:"initial-layer-min-bead-width"`
	OuterWallOffset          float32       `json:"outer-wall-offset"`
	IsInitialLayer           bool          `json:"is-initial-layer"`
	IsBottomLayer            bool          `json:"is-bottom-layer"`
	IsTopmostLayer           bool          `json:"is-topmost-layer"`

	// Squared distance gate (mm²) from meshfix_maximum_resolution.
	SmallestLineSegmentSquared float32 `json:"smallest-line-segment-squared"`

	// Squared error distance gate (mm²) from meshfix_maximum_deviation.
	AllowedErrorDistanceSquared float32 `json:"allowed-error-distance-squared"`

	// Area deviation threshold (mm²) for near-colinear fast-path guard.
	MaximumExtrusionAreaDeviation float32      `json:"maximum-extrusion-area-deviation"`
	WallSequence                  WallSequence `json:"wall-sequence"`
}

// Log represents the imported function "log".
//
//	log: func(level: log-level, message: string)
//
//go:nosplit
func Log(level LogLevel, message string) {
	level0 := (uint32)(level)
	message0, message1 := cm.LowerString(message)
	wasmimport_Log((uint32)(level0), (*uint8)(message0), (uint32)(message1))
	return
}

// RaycastZDown represents the imported function "raycast-z-down".
//
//	raycast-z-down: func(object-id: object-id, x: f32, y: f32, start-z: f32) -> option<f32>
//
//go:nosplit
func RaycastZDown(objectID ObjectID, x float32, y float32, startZ float32) (result cm.Option[float32]) {
	objectId0, objectId1 := cm.LowerString(objectID)
	x0 := (float32)(x)
	y0 := (float32)(y)
	startZ0 := (float32)(startZ)
	wasmimport_RaycastZDown((*uint8)(objectId0), (uint32)(objectId1), (float32)(x0), (float32)(y0), (float32)(startZ0), &result)
	return
}

// SurfaceNormalAt represents the imported function "surface-normal-at".
//
//	surface-normal-at: func(object-id: object-id, x: f32, y: f32, z: f32) -> option<point3>
//
//go:nosplit
func SurfaceNormalAt(objectID ObjectID, x float32, y float32, z float32) (result cm.Option[Point3]) {
	objectId0, objectId1 := cm.LowerString(objectID)
	x0 := (float32)(x)
	y0 := (float32)(y)
	z0 := (float32)(z)
	wasmimport_SurfaceNormalAt((*uint8)(objectId0), (uint32)(objectId1), (float32)(x0), (float32)(y0), (float32)(z0), &result)
	return
}

// ObjectBounds represents the imported function "object-bounds".
//
//	object-bounds: func(object-id: object-id) -> bounding-box3
//
//go:nosplit
func ObjectBounds(objectID ObjectID) (result BoundingBox3) {
	objectId0, objectId1 := cm.LowerString(objectID)
	wasmimport_ObjectBounds((*uint8)(objectId0), (uint32)(objectId1), &result)
	return
}

// ClipPolygons represents the imported function "clip-polygons".
//
//	clip-polygons: func(subject: list<ex-polygon>, clip: list<ex-polygon>, op: clip-operation)
//	-> list<ex-polygon>
//
//go:nosplit
func ClipPolygons(subject cm.List[ExPolygon], clip cm.List[ExPolygon], op ClipOperation) (result cm.List[ExPolygon]) {
	subject0, subject1 := cm.LowerList(subject)
	clip0, clip1 := cm.LowerList(clip)
	op0 := (uint32)(op)
	wasmimport_ClipPolygons((*ExPolygon)(subject0), (uint32)(subject1), (*ExPolygon)(clip0), (uint32)(clip1), (uint32)(op0), &result)
	return
}

// OffsetPolygons represents the imported function "offset-polygons".
//
//	offset-polygons: func(polygons: list<ex-polygon>, delta-mm: f32, join: offset-join-type,
//	arc-tolerance-mm: f32) -> list<ex-polygon>
//
//go:nosplit
func OffsetPolygons(polygons cm.List[ExPolygon], deltaMm float32, join OffsetJoinType, arcToleranceMm float32) (result cm.List[ExPolygon]) {
	polygons0, polygons1 := cm.LowerList(polygons)
	deltaMm0 := (float32)(deltaMm)
	join0 := (uint32)(join)
	arcToleranceMm0 := (float32)(arcToleranceMm)
	wasmimport_OffsetPolygons((*ExPolygon)(polygons0), (uint32)(polygons1), (float32)(deltaMm0), (uint32)(join0), (float32)(arcToleranceMm0), &result)
	return
}

// SimplifyPolygon represents the imported function "simplify-polygon".
//
//	simplify-polygon: func(polygon: polygon, tolerance-mm: f32) -> polygon
//
//go:nosplit
func SimplifyPolygon(polygon Polygon, toleranceMm float32) (result Polygon) {
	polygon0, polygon1 := lower_Polygon(polygon)
	toleranceMm0 := (float32)(toleranceMm)
	wasmimport_SimplifyPolygon((*geometry.Point2)(polygon0), (uint32)(polygon1), (float32)(toleranceMm0), &result)
	return
}

// OffsetPolygonsBatch represents the imported function "offset-polygons-batch".
//
//	offset-polygons-batch: func(requests: list<offset-request>) -> list<list<ex-polygon>>
//
//go:nosplit
func OffsetPolygonsBatch(requests cm.List[OffsetRequest]) (result cm.List[cm.List[ExPolygon]]) {
	requests0, requests1 := cm.LowerList(requests)
	wasmimport_OffsetPolygonsBatch((*OffsetRequest)(requests0), (uint32)(requests1), &result)
	return
}

// ClipPolygonsBatch represents the imported function "clip-polygons-batch".
//
//	clip-polygons-batch: func(requests: list<clip-request>) -> list<list<ex-polygon>>
//
//go:nosplit
func ClipPolygonsBatch(requests cm.List[ClipRequest]) (result cm.List[cm.List[ExPolygon]]) {
	requests0, requests1 := cm.LowerList(requests)
	wasmimport_ClipPolygonsBatch((*ClipRequest)(requests0), (uint32)(requests1), &result)
	return
}

// SimplifyPolygonBatch represents the imported function "simplify-polygon-batch".
//
//	simplify-polygon-batch: func(requests: list<simplify-request>) -> list<polygon>
//
//go:nosplit
func SimplifyPolygonBatch(requests cm.List[SimplifyRequest]) (result cm.List[Polygon]) {
	requests0, requests1 := cm.LowerList(requests)
	wasmimport_SimplifyPolygonBatch((*SimplifyRequest)(requests0), (uint32)(requests1), &result)
	return
}

// RaycastZDownBatch represents the imported function "raycast-z-down-batch".
//
//	raycast-z-down-batch: func(requests: list<raycast-request>) -> list<option<f32>>
//
//go:nosplit
func RaycastZDownBatch(requests cm.List[RaycastRequest]) (result cm.List[cm.Option[float32]]) {
	requests0, requests1 := cm.LowerList(requests)
	wasmimport_RaycastZDownBatch((*RaycastRequest)(requests0), (uint32)(requests1), &result)
	return
}

// SurfaceNormalAtBatch represents the imported function "surface-normal-at-batch".
//
//	surface-normal-at-batch: func(requests: list<surface-normal-request>) -> list<option<point3>>
//
//go:nosplit
func SurfaceNormalAtBatch(requests cm.List[SurfaceNormalRequest]) (result cm.List[cm.Option[Point3]]) {
	requests0, requests1 := cm.LowerList(requests)
	wasmimport_SurfaceNormalAtBatch((*SurfaceNormalRequest)(requests0), (uint32)(requests1), &result)
	return
}

// MedialAxis represents the imported function "medial-axis".
//
//	medial-axis: func(input: ex-polygon, min-width: f32, max-width: f32) -> result<list<thick-polyline>,
//	string>
//
//go:nosplit
func MedialAxis(input ExPolygon, minWidth float32, maxWidth float32) (result cm.Result[cm.List[ThickPolyline], cm.List[ThickPolyline], string]) {
	input0, input1, input2, input3 := lower_ExPolygon(input)
	minWidth0 := (float32)(minWidth)
	maxWidth0 := (float32)(maxWidth)
	wasmimport_MedialAxis((*geometry.Point2)(input0), (uint32)(input1), (*geometry.Polygon)(input2), (uint32)(input3), (float32)(minWidth0), (float32)(maxWidth0), &result)
	return
}

// GenerateArachneWalls represents the imported function "generate-arachne-walls".
//
// Runs the full Arachne beading-strategy pipeline
// (`slicer_core::arachne::pipeline::run_arachne_pipeline`) host-side, for
// a WASM guest that cannot itself link the `host-algos` feature
// (rayon + boostvoronoi are native-only) — mirrors the `medial-axis`
// bridge above.
//
// Returns a tuple of (toolpaths, inner_contour):
// - `toolpaths`: printable variable-width wall lines.
// - `inner_contour`: zero-width marker lines defining the wall/infill
// boundary (consumed by `arachne-perimeters` to set infill areas).
//
//	generate-arachne-walls: func(polygons: list<ex-polygon>, params: arachne-params)
//	-> result<tuple<list<extrusion-line>, list<extrusion-line>>, string>
//
//go:nosplit
func GenerateArachneWalls(polygons cm.List[ExPolygon], params ArachneParams) (result cm.Result[TupleListExtrusionLineListExtrusionLineShape, [2]cm.List[ExtrusionLine], string]) {
	params_ := wasmimport_GenerateArachneWalls_params{polygons: polygons, params: params}
	wasmimport_GenerateArachneWalls(&params_, &result)
	return
}

// wasmimport_GenerateArachneWalls_params represents the flattened function params for [wasmimport_GenerateArachneWalls].
// See the Canonical ABI flattening rules for more information.
type wasmimport_GenerateArachneWalls_params struct {
	_        cm.HostLayout      `json:"-"`
	polygons cm.List[ExPolygon] `json:"polygons"`
	params   ArachneParams      `json:"params"`
}

// NowUs represents the imported function "now-us".
//
//	now-us: func() -> u64
//
//go:nosplit
func NowUs() (result uint64) {
	result0 := wasmimport_NowUs()
	result = (uint64)((uint64)(result0))
	return
}
