// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package textpostprocessmodule represents the world "slicer:postpass-text-postprocess/text-postprocess-module@1.0.0".
package textpostprocessmodule
