// Code generated by wit-bindgen-go. DO NOT EDIT.

package textpostprocess

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// ModuleErrorShape is used for storage in variant or result types.
type ModuleErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(ModuleError{})]byte
}
