// Code generated by wit-bindgen-go. DO NOT EDIT.

package textpostprocess

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "slicer:postpass-text-postprocess/text-postprocess@1.0.0".
var Exports struct {
	// Run represents the caller-defined, exported function "run".
	//
	//	run: func(gcode-text: string, config: config-view) -> result<string, module-error>
	Run func(gcodeText string, config ConfigView) (result cm.Result[ModuleErrorShape, string, ModuleError])
}
