// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package textpostprocess represents the exported interface "slicer:postpass-text-postprocess/text-postprocess@1.0.0".
package textpostprocess

import (
	moduleerrors "foreign-language-text-postprocess/slicer/common/module-errors"
	configtypes "foreign-language-text-postprocess/slicer/config/config-types"
)

// ConfigView represents the exported type alias "slicer:postpass-text-postprocess/text-postprocess@1.0.0#config-view".
//
// See [configtypes.ConfigView] for more information.
type ConfigView = configtypes.ConfigView

// ModuleError represents the type alias "slicer:postpass-text-postprocess/text-postprocess@1.0.0#module-error".
//
// See [moduleerrors.ModuleError] for more information.
type ModuleError = moduleerrors.ModuleError
