// Code generated by wit-bindgen-go. DO NOT EDIT.

package textpostprocess

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "slicer:postpass-text-postprocess@1.0.0".

//go:wasmexport slicer:postpass-text-postprocess/text-postprocess@1.0.0#run
//export slicer:postpass-text-postprocess/text-postprocess@1.0.0#run
func wasmexport_Run(gcodeText0 *uint8, gcodeText1 uint32, config0 uint32) (result *cm.Result[ModuleErrorShape, string, ModuleError]) {
	gcodeText := cm.LiftString[string]((*uint8)(gcodeText0), (uint32)(gcodeText1))
	config := cm.Reinterpret[ConfigView]((uint32)(config0))
	result_ := Exports.Run(gcodeText, config)
	result = &result_
	return
}
