// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package geometry represents the imported interface "slicer:types/geometry".
package geometry

import (
	"go.bytecodealliance.org/cm"
)

// Point2 represents the record "slicer:types/geometry#point2".
//
//	record point2 {
//		x: s64,
//		y: s64,
//	}
type Point2 struct {
	_ cm.HostLayout `json:"-"`
	X int64         `json:"x"`
	Y int64         `json:"y"`
}

// Point3 represents the record "slicer:types/geometry#point3".
//
//	record point3 {
//		x: f32,
//		y: f32,
//		z: f32,
//	}
type Point3 struct {
	_ cm.HostLayout `json:"-"`
	X float32       `json:"x"`
	Y float32       `json:"y"`
	Z float32       `json:"z"`
}

// Point3WithWidth represents the record "slicer:types/geometry#point3-with-width".
//
//	record point3-with-width {
//		x: f32,
//		y: f32,
//		z: f32,
//		width: f32,
//		flow-factor: f32,
//		overhang-quartile: option<u8>,
//		dist-to-top-mm: f32,
//		overhang-distance-mm: option<f32>,
//	}
type Point3WithWidth struct {
	_                  cm.HostLayout      `json:"-"`
	X                  float32            `json:"x"`
	Y                  float32            `json:"y"`
	Z                  float32            `json:"z"`
	Width              float32            `json:"width"`
	FlowFactor         float32            `json:"flow-factor"`
	OverhangQuartile   cm.Option[uint8]   `json:"overhang-quartile"`
	DistToTopMm        float32            `json:"dist-to-top-mm"`
	OverhangDistanceMm cm.Option[float32] `json:"overhang-distance-mm"`
}

// SeamPoint3WithWidth represents the record "slicer:types/geometry#seam-point3-with-width".
//
//	record seam-point3-with-width {
//		x: f32,
//		y: f32,
//		z: f32,
//		width: f32,
//		flow-factor: f32,
//		overhang-quartile: option<u8>,
//	}
type SeamPoint3WithWidth struct {
	_                cm.HostLayout    `json:"-"`
	X                float32          `json:"x"`
	Y                float32          `json:"y"`
	Z                float32          `json:"z"`
	Width            float32          `json:"width"`
	FlowFactor       float32          `json:"flow-factor"`
	OverhangQuartile cm.Option[uint8] `json:"overhang-quartile"`
}

// BoundingBox2 represents the record "slicer:types/geometry#bounding-box2".
//
//	record bounding-box2 {
//		min: point2,
//		max: point2,
//	}
type BoundingBox2 struct {
	_   cm.HostLayout `json:"-"`
	Min Point2        `json:"min"`
	Max Point2        `json:"max"`
}

// BoundingBox3 represents the record "slicer:types/geometry#bounding-box3".
//
//	record bounding-box3 {
//		min: point3,
//		max: point3,
//	}
type BoundingBox3 struct {
	_   cm.HostLayout `json:"-"`
	Min Point3        `json:"min"`
	Max Point3        `json:"max"`
}

// Polygon represents the record "slicer:types/geometry#polygon".
//
//	record polygon {
//		points: list<point2>,
//	}
type Polygon struct {
	_      cm.HostLayout   `json:"-"`
	Points cm.List[Point2] `json:"points"`
}

// ExPolygon represents the record "slicer:types/geometry#ex-polygon".
//
//	record ex-polygon {
//		contour: polygon,
//		holes: list<polygon>,
//	}
type ExPolygon struct {
	_       cm.HostLayout    `json:"-"`
	Contour Polygon          `json:"contour"`
	Holes   cm.List[Polygon] `json:"holes"`
}

// ExtrusionRole represents the variant "slicer:types/geometry#extrusion-role".
//
//	variant extrusion-role {
//		outer-wall,
//		inner-wall,
//		thin-wall,
//		top-solid-infill,
//		bottom-solid-infill,
//		sparse-infill,
//		support-material,
//		support-interface,
//		ironing,
//		bridge-infill,
//		wipe-tower,
//		gap-fill,
//		raft-infill,
//		custom(string),
//	}
type ExtrusionRole cm.Variant[uint8, string, string]

// ExtrusionRoleOuterWall returns a [ExtrusionRole] of case "outer-wall".
func ExtrusionRoleOuterWall() ExtrusionRole {
	var data struct{}
	return cm.New[ExtrusionRole](0, data)
}

// OuterWall returns true if [ExtrusionRole] represents the variant case "outer-wall".
func (self *ExtrusionRole) OuterWall() bool {
	return self.Tag() == 0
}

// ExtrusionRoleInnerWall returns a [ExtrusionRole] of case "inner-wall".
func ExtrusionRoleInnerWall() ExtrusionRole {
	var data struct{}
	return cm.New[ExtrusionRole](1, data)
}

// InnerWall returns true if [ExtrusionRole] represents the variant case "inner-wall".
func (self *ExtrusionRole) InnerWall() bool {
	return self.Tag() == 1
}

// ExtrusionRoleThinWall returns a [ExtrusionRole] of case "thin-wall".
func ExtrusionRoleThinWall() ExtrusionRole {
	var data struct{}
	return cm.New[ExtrusionRole](2, data)
}

// ThinWall returns true if [ExtrusionRole] represents the variant case "thin-wall".
func (self *ExtrusionRole) ThinWall() bool {
	return self.Tag() == 2
}

// ExtrusionRoleTopSolidInfill returns a [ExtrusionRole] of case "top-solid-infill".
func ExtrusionRoleTopSolidInfill() ExtrusionRole {
	var data struct{}
	return cm.New[ExtrusionRole](3, data)
}

// TopSolidInfill returns true if [ExtrusionRole] represents the variant case "top-solid-infill".
func (self *ExtrusionRole) TopSolidInfill() bool {
	return self.Tag() == 3
}

// ExtrusionRoleBottomSolidInfill returns a [ExtrusionRole] of case "bottom-solid-infill".
func ExtrusionRoleBottomSolidInfill() ExtrusionRole {
	var data struct{}
	return cm.New[ExtrusionRole](4, data)
}

// BottomSolidInfill returns true if [ExtrusionRole] represents the variant case "bottom-solid-infill".
func (self *ExtrusionRole) BottomSolidInfill() bool {
	return self.Tag() == 4
}

// ExtrusionRoleSparseInfill returns a [ExtrusionRole] of case "sparse-infill".
func ExtrusionRoleSparseInfill() ExtrusionRole {
	var data struct{}
	return cm.New[ExtrusionRole](5, data)
}

// SparseInfill returns true if [ExtrusionRole] represents the variant case "sparse-infill".
func (self *ExtrusionRole) SparseInfill() bool {
	return self.Tag() == 5
}

// ExtrusionRoleSupportMaterial returns a [ExtrusionRole] of case "support-material".
func ExtrusionRoleSupportMaterial() ExtrusionRole {
	var data struct{}
	return cm.New[ExtrusionRole](6, data)
}

// SupportMaterial returns true if [ExtrusionRole] represents the variant case "support-material".
func (self *ExtrusionRole) SupportMaterial() bool {
	return self.Tag() == 6
}

// ExtrusionRoleSupportInterface returns a [ExtrusionRole] of case "support-interface".
func ExtrusionRoleSupportInterface() ExtrusionRole {
	var data struct{}
	return cm.New[ExtrusionRole](7, data)
}

// SupportInterface returns true if [ExtrusionRole] represents the variant case "support-interface".
func (self *ExtrusionRole) SupportInterface() bool {
	return self.Tag() == 7
}

// ExtrusionRoleIroning returns a [ExtrusionRole] of case "ironing".
func ExtrusionRoleIroning() ExtrusionRole {
	var data struct{}
	return cm.New[ExtrusionRole](8, data)
}

// Ironing returns true if [ExtrusionRole] represents the variant case "ironing".
func (self *ExtrusionRole) Ironing() bool {
	return self.Tag() == 8
}

// ExtrusionRoleBridgeInfill returns a [ExtrusionRole] of case "bridge-infill".
func ExtrusionRoleBridgeInfill() ExtrusionRole {
	var data struct{}
	return cm.New[ExtrusionRole](9, data)
}

// BridgeInfill returns true if [ExtrusionRole] represents the variant case "bridge-infill".
func (self *ExtrusionRole) BridgeInfill() bool {
	return self.Tag() == 9
}

// ExtrusionRoleWipeTower returns a [ExtrusionRole] of case "wipe-tower".
func ExtrusionRoleWipeTower() ExtrusionRole {
	var data struct{}
	return cm.New[ExtrusionRole](10, data)
}

// WipeTower returns true if [ExtrusionRole] represents the variant case "wipe-tower".
func (self *ExtrusionRole) WipeTower() bool {
	return self.Tag() == 10
}

// ExtrusionRoleGapFill returns a [ExtrusionRole] of case "gap-fill".
func ExtrusionRoleGapFill() ExtrusionRole {
	var data struct{}
	return cm.New[ExtrusionRole](11, data)
}

// GapFill returns true if [ExtrusionRole] represents the variant case "gap-fill".
func (self *ExtrusionRole) GapFill() bool {
	return self.Tag() == 11
}

// ExtrusionRoleRaftInfill returns a [ExtrusionRole] of case "raft-infill".
func ExtrusionRoleRaftInfill() ExtrusionRole {
	var data struct{}
	return cm.New[ExtrusionRole](12, data)
}

// RaftInfill returns true if [ExtrusionRole] represents the variant case "raft-infill".
func (self *ExtrusionRole) RaftInfill() bool {
	return self.Tag() == 12
}

// ExtrusionRoleCustom returns a [ExtrusionRole] of case "custom".
func ExtrusionRoleCustom(data string) ExtrusionRole {
	return cm.New[ExtrusionRole](13, data)
}

// Custom returns a non-nil *[string] if [ExtrusionRole] represents the variant case "custom".
func (self *ExtrusionRole) Custom() *string {
	return cm.Case[string](self, 13)
}

var _ExtrusionRoleStrings = [14]string{
	"outer-wall",
	"inner-wall",
	"thin-wall",
	"top-solid-infill",
	"bottom-solid-infill",
	"sparse-infill",
	"support-material",
	"support-interface",
	"ironing",
	"bridge-infill",
	"wipe-tower",
	"gap-fill",
	"raft-infill",
	"custom",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v ExtrusionRole) String() string {
	return _ExtrusionRoleStrings[v.Tag()]
}

// ExtrusionPath3d represents the record "slicer:types/geometry#extrusion-path3d".
//
//	record extrusion-path3d {
//		points: list<point3-with-width>,
//		role: extrusion-role,
//		speed-factor: f32,
//	}
type ExtrusionPath3d struct {
	_           cm.HostLayout            `json:"-"`
	Points      cm.List[Point3WithWidth] `json:"points"`
	Role        ExtrusionRole            `json:"role"`
	SpeedFactor float32                  `json:"speed-factor"`
}

// Semver represents the record "slicer:types/geometry#semver".
//
//	record semver {
//		major: u32,
//		minor: u32,
//		patch: u32,
//	}
type Semver struct {
	_     cm.HostLayout `json:"-"`
	Major uint32        `json:"major"`
	Minor uint32        `json:"minor"`
	Patch uint32        `json:"patch"`
}

// Point2WithWidth represents the record "slicer:types/geometry#point2-with-width".
//
//	record point2-with-width {
//		x: f32,
//		y: f32,
//		width: f32,
//	}
type Point2WithWidth struct {
	_     cm.HostLayout `json:"-"`
	X     float32       `json:"x"`
	Y     float32       `json:"y"`
	Width float32       `json:"width"`
}

// ThickPolyline represents the record "slicer:types/geometry#thick-polyline".
//
//	record thick-polyline {
//		points: list<point2-with-width>,
//	}
type ThickPolyline struct {
	_      cm.HostLayout            `json:"-"`
	Points cm.List[Point2WithWidth] `json:"points"`
}
