//! Core IR type definitions
//!
//! All coordinate conversions follow the canonical rules:
//! - mm → units: `units = round(mm * 10_000.0)` (round half away from zero).
//! - units → mm: `mm = units / 10_000.0`.

use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, HashMap};

// `ResolvedConfig` is generated by `declare_resolved_config!` in `crate::resolved_config`.
use crate::resolved_config::ResolvedConfig;

// ============================================================================
// ID Types
// ============================================================================

/// UUID string for objects
pub type ObjectId = String;

/// UUID string for modifiers
pub type ModifierId = String;

/// Reverse-domain module identifier (e.g., "com.example.module")
pub type ModuleId = String;

/// Surface group identifier
pub type SurfaceGroupId = u64;

/// Bridge region identifier
pub type BridgeRegionId = u64;

/// Overhang region identifier
pub type OverhangRegionId = u64;

/// Region identifier
pub type RegionId = u64;

/// Stage identifier
pub type StageId = String;

// ============================================================================
// Coordinate System and Basic Types
// ============================================================================

/// Scaling factor: 1 mm = 10 000 units (1 unit = 100 nm = 10⁻⁴ mm).
///
/// Use this constant anywhere an f64 mm→unit conversion is needed so that
/// the factor has a single authoritative source.
pub const UNITS_PER_MM: f64 = 10_000.0;

/// Convert millimeters to scaled integer units
///
/// # Arguments
/// * `mm` - Value in millimeters
///
/// # Returns
/// Scaled integer units (1 unit = 100 nm = 10^-4 mm)
#[inline]
pub fn mm_to_units(mm: f32) -> i64 {
    (mm * UNITS_PER_MM as f32).round() as i64
}

/// Convert scaled integer units to millimeters
///
/// # Arguments
/// * `units` - Scaled integer units
///
/// # Returns
/// Value in millimeters
#[inline]
pub fn units_to_mm(units: i64) -> f32 {
    (units as f32) / UNITS_PER_MM as f32
}

/// 2D point using scaled integer coordinates
///
/// Coordinate system: 1 unit = 100 nm = 10^-4 mm
#[derive(
    Debug, Clone, Copy, Default, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize,
)]
pub struct Point2 {
    /// X coordinate in scaled integer units (1 unit = 100 nm)
    pub x: i64,
    /// Y coordinate in scaled integer units (1 unit = 100 nm)
    pub y: i64,
}

impl Point2 {
    /// Create from millimeter values
    pub fn from_mm(x: f32, y: f32) -> Self {
        Self {
            x: mm_to_units(x),
            y: mm_to_units(y),
        }
    }

    /// Convert to millimeter values
    pub fn to_mm(&self) -> (f32, f32) {
        (units_to_mm(self.x), units_to_mm(self.y))
    }
}

/// 3D point using floating-point millimeter coordinates
#[derive(Debug, Clone, Copy, Default, PartialEq, Serialize, Deserialize)]
pub struct Point3 {
    /// X coordinate in millimeters
    pub x: f32,
    /// Y coordinate in millimeters
    pub y: f32,
    /// Z coordinate in millimeters
    pub z: f32,
}

/// 3D bounding box
#[derive(Debug, Clone, Copy, Default, PartialEq, Serialize, Deserialize)]
pub struct BoundingBox3 {
    /// Minimum corner of the bounding box
    pub min: Point3,
    /// Maximum corner of the bounding box
    pub max: Point3,
}

/// 2D bounding box in scaled integer units (1 unit = 100 nm)
#[derive(Debug, Clone, Copy, Default, PartialEq, Serialize, Deserialize)]
pub struct BoundingBox2 {
    /// Minimum corner of the bounding box
    pub min: Point2,
    /// Maximum corner of the bounding box
    pub max: Point2,
}

impl BoundingBox2 {
    /// Returns true if the point is inside or on the bounding box edges.
    pub fn contains_point(&self, point: Point2) -> bool {
        point.x >= self.min.x
            && point.x <= self.max.x
            && point.y >= self.min.y
            && point.y <= self.max.y
    }
}

/// 3D transformation (column-major 4x4 matrix)
///
/// **Hazard:** `Transform3d::default()` is an all-zeros matrix, not the
/// identity — multiplying by it collapses every point to the origin. Call
/// sites that need a real transform must override `matrix` explicitly. See
/// `docs/specs/default-builder-migration.md` §11 Q2.
#[derive(Debug, Clone, Copy, Default, PartialEq, Serialize, Deserialize)]
pub struct Transform3d {
    /// 4x4 transformation matrix in column-major order
    pub matrix: [f64; 16],
}

/// Indexed triangle set (vertices + indices)
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct IndexedTriangleSet {
    /// List of 3D vertices
    pub vertices: Vec<Point3>,
    /// List of indices into vertices, 3 per triangle
    pub indices: Vec<u32>,
}

/// Semantic versioning
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct SemVer {
    /// Major version number
    pub major: u32,
    /// Minor version number
    pub minor: u32,
    /// Patch version number
    pub patch: u32,
}

impl std::fmt::Display for SemVer {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}.{}.{}", self.major, self.minor, self.patch)
    }
}

/// Schema version for `SurfaceClassificationIR`. Single source of truth — production
/// constructors must use this constant, not literal `SemVer { ... }` values.
/// Minor bump to 1.2.0 (packet 106) adds the additive `OverhangRegion.xy_footprint`
/// field and `SurfaceClassificationIR.overhang_quartile_polygons` map.
/// `#[serde(default)]` preserves backward compatibility with 1.1.0 fixtures.
pub const CURRENT_SURFACE_CLASSIFICATION_SCHEMA_VERSION: SemVer = SemVer {
    major: 1,
    minor: 2,
    patch: 0,
};

/// Schema version for `SliceIR`. Bumped to 4.0.0 by packet 91 — breaking
/// field changes: `SlicedRegion.boundary_paint` renamed to `segment_annotations`,
/// `SlicedRegion.variant_chain` added. Prior bump to 3.0.0 was made by an
/// earlier packet; this packet's rename layers a new breaking change.
/// Minor bump to 4.1.0 adds the additive `SlicedRegion.sparse_infill_area`
/// field (host-side fill partition output); `#[serde(default)]` preserves
/// backward compatibility with serialized 4.0.0 fixtures.
/// Minor bump to 4.4.0 (packet 105) adds the additive `LoopType::GapFill` and
/// `ExtrusionRole::GapFill` enums (T-062b). `#[non_exhaustive]` on both enums
/// preserves backward compatibility.
/// Minor bump to 4.6.0 (packet 109) removes the dead external-contour field from
/// `SlicedRegion` and its WIT `external-contour` accessor. The IR Versioning
/// Contract (`docs/02_ir_schemas.md`) classifies field removal as *major* by
/// default; this specific removal is a deliberate, documented exception that
/// ships as a backward-COMPATIBLE minor bump because ALL THREE hold: (1) the
/// field had no live consumer (superseded by ADR-0013 Model-A per-color
/// fragmentation; consumption was already removed in P105, D-105-AC22-PARITY-RESHAPE),
/// (2) serde ignores the now-absent field, so serialized 4.x fixtures still parse,
/// and (3) every loaded module declares `max_ir_schema = 5.0.0`, so a 5.0.0 host
/// would fail the scheduler's `validate_ir_versions` gate for EVERY module — a
/// major bump would break the whole module ecosystem for a removal that changes
/// no behaviour. Rationale recorded in the `docs/02_ir_schemas.md` Contract note.
/// Minor bump to 4.7.0 (packet 112, T-224) adds the additive `ExtrusionJunction`
/// and `ExtrusionLine` types (Arachne beading-strategy-stack variable-width wall
/// representation) plus the `extrusion_line_to_extrusion_path3d` converter to the
/// existing `ExtrusionPath3D` wall surface. No existing field or type changed;
/// `#[serde(default)]` on the new optional fields preserves backward
/// compatibility with 4.6.0 fixtures that predate these types.
pub const CURRENT_SLICE_IR_SCHEMA_VERSION: SemVer = SemVer {
    major: 4,
    minor: 7,
    patch: 0,
};

/// Schema version for `MeshIR`. Bumped to 1.1.0 by packet 56b — populated
/// `modifier_volumes` from `Metadata/model_settings.config`.
pub const CURRENT_MESH_IR_SCHEMA_VERSION: SemVer = SemVer {
    major: 1,
    minor: 1,
    patch: 0,
};

/// Schema version for `LayerPlanIR`. Initial 1.0.0 — no bumps recorded in
/// `docs/02_ir_schemas.md` as of TASK-200b.
pub const CURRENT_LAYER_PLAN_IR_SCHEMA_VERSION: SemVer = SemVer {
    major: 1,
    minor: 0,
    patch: 0,
};

/// Schema version for `SeamPlanIR`. Initial 1.0.0 — no bumps recorded in
/// `docs/02_ir_schemas.md` as of TASK-200b.
pub const CURRENT_SEAM_PLAN_IR_SCHEMA_VERSION: SemVer = SemVer {
    major: 1,
    minor: 0,
    patch: 0,
};

/// Schema version for `SupportPlanIR`. Initial 1.0.0 — no bumps recorded in
/// `docs/02_ir_schemas.md` as of TASK-200b.
pub const CURRENT_SUPPORT_PLAN_IR_SCHEMA_VERSION: SemVer = SemVer {
    major: 1,
    minor: 0,
    patch: 0,
};

/// Schema version for `SupportGeometryIR`. Initial 1.0.0 — no bumps recorded
/// in `docs/02_ir_schemas.md` as of TASK-200b.
pub const CURRENT_SUPPORT_GEOMETRY_IR_SCHEMA_VERSION: SemVer = SemVer {
    major: 1,
    minor: 0,
    patch: 0,
};

/// Schema version for `LightningTreeIR`. Initial 1.0.0 — packet 137 lands
/// the contract; algorithm ships in 138/139.
pub const CURRENT_LIGHTNING_TREE_IR_SCHEMA_VERSION: SemVer = SemVer {
    major: 1,
    minor: 0,
    patch: 0,
};

/// Schema version for `RegionMapIR`. Bumped to 2.0.0 by packet 91 — breaking
/// field changes: `RegionPlan.config` is now a `ConfigId` (interner index),
/// `configs` Vec added to `RegionMapIR`, `RegionKey.variant_chain` added.
pub const CURRENT_REGION_MAP_IR_SCHEMA_VERSION: SemVer = SemVer {
    major: 2,
    minor: 0,
    patch: 0,
};

/// Schema version for `PerimeterIR`. Initial 1.0.0 — no bumps recorded in
/// `docs/02_ir_schemas.md` as of TASK-200b.
pub const CURRENT_PERIMETER_IR_SCHEMA_VERSION: SemVer = SemVer {
    major: 1,
    minor: 0,
    patch: 0,
};

/// Schema version for `InfillIR`. Initial 1.0.0 — no bumps recorded in
/// `docs/02_ir_schemas.md` as of TASK-200b.
pub const CURRENT_INFILL_IR_SCHEMA_VERSION: SemVer = SemVer {
    major: 1,
    minor: 0,
    patch: 0,
};

/// Schema version for `SupportIR`. Initial 1.0.0 — no bumps recorded in
/// `docs/02_ir_schemas.md` as of TASK-200b.
pub const CURRENT_SUPPORT_IR_SCHEMA_VERSION: SemVer = SemVer {
    major: 1,
    minor: 0,
    patch: 0,
};

/// Schema version for `LayerCollectionIR`. 1.1.0 — packet 125 follow-up added
/// the additive `PrintEntity.tool_index` field (tool/identity split).
pub const CURRENT_LAYER_COLLECTION_IR_SCHEMA_VERSION: SemVer = SemVer {
    major: 1,
    minor: 1,
    patch: 0,
};

/// Schema version for `GCodeIR`. Initial 1.0.0 — no bumps recorded in
/// `docs/02_ir_schemas.md` as of TASK-200b.
pub const CURRENT_GCODE_IR_SCHEMA_VERSION: SemVer = SemVer {
    major: 1,
    minor: 0,
    patch: 0,
};

// ============================================================================
// Mesh IR Types
// ============================================================================

/// Raw user config (not yet resolved)
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ObjectConfig {
    /// Configuration data key-value map
    pub data: HashMap<String, ConfigValue>,
}

/// Paint semantic types
#[derive(Debug, Clone, PartialEq, Eq, Hash, Ord, PartialOrd, Serialize, Deserialize)]
pub enum PaintSemantic {
    /// Which tool/filament to use for this surface region
    Material,
    /// Apply fuzzy skin texture to this surface region
    FuzzySkin,
    /// Force support generation in this region regardless of overhang angle
    SupportEnforcer,
    /// Block support generation in this region regardless of overhang angle
    SupportBlocker,
    /// Community-defined semantic
    Custom(String),
}

/// Paint value types
///
/// # Total-ordering contract
/// `Scalar(f32)` uses `f32::total_cmp` for ordering (NaN is ordered after all
/// finite values). Callers MUST NOT construct `Scalar(f32::NAN)` — the `Eq`
/// impl treats NaN-bit-equal values as equal (via `to_bits`), but `Ord` will
/// place them at a defined position rather than panic.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PaintValue {
    /// Boolean flag
    Flag(bool),
    /// Scalar value
    Scalar(f32),
    /// Tool/material index
    ToolIndex(u32),
    /// Community-defined or module-defined string value.
    /// Used when none of the typed variants is appropriate.
    Custom(String),
}

impl PartialEq for PaintValue {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::Flag(a), Self::Flag(b)) => a == b,
            (Self::Scalar(a), Self::Scalar(b)) => a.to_bits() == b.to_bits(),
            (Self::ToolIndex(a), Self::ToolIndex(b)) => a == b,
            (Self::Custom(a), Self::Custom(b)) => a == b,
            _ => false,
        }
    }
}

impl Eq for PaintValue {}

impl PartialOrd for PaintValue {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for PaintValue {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        use std::cmp::Ordering;
        // Variant order: Flag(0) < Scalar(1) < ToolIndex(2) < Custom(3)
        fn discriminant(v: &PaintValue) -> u8 {
            match v {
                PaintValue::Flag(_) => 0,
                PaintValue::Scalar(_) => 1,
                PaintValue::ToolIndex(_) => 2,
                PaintValue::Custom(_) => 3,
            }
        }
        let da = discriminant(self);
        let db = discriminant(other);
        if da != db {
            return da.cmp(&db);
        }
        match (self, other) {
            (Self::Flag(a), Self::Flag(b)) => a.cmp(b),
            (Self::Scalar(a), Self::Scalar(b)) => a.total_cmp(b),
            (Self::ToolIndex(a), Self::ToolIndex(b)) => a.cmp(b),
            (Self::Custom(a), Self::Custom(b)) => a.cmp(b),
            _ => Ordering::Equal, // unreachable: discriminants matched above
        }
    }
}

impl std::hash::Hash for PaintValue {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        std::mem::discriminant(self).hash(state);
        match self {
            Self::Flag(b) => b.hash(state),
            Self::Scalar(f) => f.to_bits().hash(state),
            Self::ToolIndex(n) => n.hash(state),
            Self::Custom(s) => s.hash(state),
        }
    }
}

/// Paint stroke (3D triangles defining painted region)
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PaintStroke {
    /// 3D triangles on the mesh surface defining the painted region
    pub triangles: Vec<[Point3; 3]>,
    /// The semantic type of this paint stroke
    pub semantic: PaintSemantic,
    /// The value associated with this paint stroke
    pub value: PaintValue,
}

/// Paint layer (all paint with same semantic on one object)
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PaintLayer {
    /// The semantic type of this paint layer
    pub semantic: PaintSemantic,
    /// One entry per mesh triangle, parallel to mesh.triangles
    pub facet_values: Vec<Option<PaintValue>>,
    /// Sub-facet strokes that cross triangle boundaries
    pub strokes: Vec<PaintStroke>,
}

/// All paint layers on one object
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FacetPaintData {
    /// List of paint layers on this object
    pub layers: Vec<PaintLayer>,
}

/// Config delta (only explicitly set fields)
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ConfigDelta {
    /// Configuration fields that are explicitly set
    pub fields: HashMap<ConfigKey, ConfigValue>,
}

/// Modifier scope
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ModifierScope {
    /// Applies to all features
    AllFeatures,
    /// Applies only to infill
    Infill,
    /// Applies only to perimeters
    Perimeters,
    /// Applies only to support
    Support,
    /// Applies to layer height
    LayerHeight,
}

/// Modifier volume
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ModifierVolume {
    /// Unique identifier for the modifier
    pub id: ModifierId,
    /// Geometry of the modifier
    pub mesh: IndexedTriangleSet,
    /// Configuration changes applied by this modifier
    pub config_delta: ConfigDelta,
    /// Priority of the modifier (higher wins)
    pub priority: u32,
    /// Scope of the modifier application
    pub applies_to: ModifierScope,
}

/// Object mesh
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ObjectMesh {
    /// Unique identifier for the object
    pub id: ObjectId,
    /// Geometry of the object
    pub mesh: IndexedTriangleSet,
    /// World-space placement of the object
    pub transform: Transform3d,
    /// Raw user config for the object
    pub config: ObjectConfig,
    /// Modifier volumes affecting this object
    pub modifier_volumes: Vec<ModifierVolume>,
    /// All user-painted data for this object
    pub paint_data: Option<FacetPaintData>,
    /// Cached world-space Z extent `(z_min, z_max)` in millimeters.
    ///
    /// Computed once at `ObjectMesh` construction time by applying the
    /// object transform to all mesh vertices and extracting the Z range.
    /// `None` when the mesh is empty or the extent is degenerate
    /// (`z_max <= z_min`, e.g. a lay-flat rotation collapses vertical extent).
    ///
    /// Not serialized — recomputed on every load so the field always reflects
    /// the current `transform` value. No schema version bump needed (v1.0.0
    /// not released). This makes world-space Z a first-class IR contract
    /// surface, closing DEV-027.
    #[serde(skip_deserializing, default)]
    pub world_z_extent: Option<(f32, f32)>,
}

/// Mesh IR (produced by host mesh loader)
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MeshIR {
    /// Schema version of this IR
    pub schema_version: SemVer,
    /// List of objects in the mesh
    pub objects: Vec<ObjectMesh>,
    /// Build volume bounding box
    pub build_volume: BoundingBox3,
}

impl Default for MeshIR {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_MESH_IR_SCHEMA_VERSION,
            objects: Vec::new(),
            build_volume: BoundingBox3::default(),
        }
    }
}

// ============================================================================
// Surface Classification IR Types
// ============================================================================

/// Facet classification
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum FacetClass {
    /// Normal facet
    Normal,
    /// Near horizontal facet
    NearHorizontal {
        /// Slope angle in degrees
        slope_angle_deg: f32,
    },
    /// Overhang facet
    Overhang {
        /// Angle in degrees
        angle_deg: f32,
    },
    /// Bridge facet
    Bridge,
    /// Top surface facet
    TopSurface,
    /// Bottom surface facet
    BottomSurface,
}

/// Surface group
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SurfaceGroup {
    /// Unique identifier for the surface group
    pub id: SurfaceGroupId,
    /// Indices of facets in this group
    pub facet_indices: Vec<u32>,
    /// Minimum Z height of the group
    pub z_min: f32,
    /// Maximum Z height of the group
    pub z_max: f32,
    /// Area of the group in mm^2
    pub area_mm2: f32,
    /// Whether the group is printable
    pub printable: bool,
    /// Shell count for the group
    pub shell_count: u32,
}

/// Bridge region
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct BridgeRegion {
    /// Unique identifier for the bridge region
    pub id: BridgeRegionId,
    /// Indices of facets in this region
    pub facet_indices: Vec<u32>,
    /// Optimal bridge angle in degrees
    pub bridge_direction_deg: f32,
    /// Shortest perpendicular run of contiguous anchor edges (mm)
    #[serde(default)]
    pub anchor_width_mm: f32,
    /// Longest unsupported span across the cluster (mm)
    #[serde(default)]
    pub bridge_length_mm: f32,
    /// Frozen at PrePass from MeshAnalysisConfig (mm)
    #[serde(default)]
    pub expansion_margin_mm: f32,
    /// Pass/fail of min-length + anchor-width filters
    #[serde(default)]
    pub is_valid: bool,
    /// Facet-cluster XY projection in 100 nm units
    #[serde(default)]
    pub xy_footprint: Vec<ExPolygon>,
}

/// Overhang region
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct OverhangRegion {
    /// Unique identifier for the overhang region
    pub id: OverhangRegionId,
    /// Indices of facets in this region
    pub facet_indices: Vec<u32>,
    /// Maximum overhang angle in degrees
    pub max_angle_deg: f32,
    /// Whether this region needs support
    pub needs_support: bool,
    /// Facet-cluster XY projection in 100 nm units
    #[serde(default)]
    pub xy_footprint: Vec<ExPolygon>,
}

/// A quartile-banded subset of overhang polygons for a single layer, used by
/// the PrePass overhang-annotation pipeline to bucket overhang area by
/// severity quartile (1 = least severe, 4 = most severe).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct QuartileBand {
    /// Quartile bucket (1-4)
    pub quartile: u8,
    /// Polygons assigned to this quartile band
    pub polygons: Vec<ExPolygon>,
}

/// Object surface data
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ObjectSurfaceData {
    /// Facet classifications for each triangle
    pub facet_classes: Vec<FacetClass>,
    /// Surface groups in the object
    pub surface_groups: Vec<SurfaceGroup>,
    /// Bridge regions in the object
    pub bridge_regions: Vec<BridgeRegion>,
    /// Overhang regions in the object
    pub overhang_regions: Vec<OverhangRegion>,
}

/// Surface classification IR
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SurfaceClassificationIR {
    /// Schema version of this IR
    pub schema_version: SemVer,
    /// Per-object surface data
    pub per_object: HashMap<ObjectId, ObjectSurfaceData>,
    /// Overhang polygons bucketed by severity quartile, keyed by global layer
    /// index. Host-only aggregation populated by the PrePass overhang
    /// annotation pipeline; not mirrored in the WIT boundary.
    #[serde(default)]
    pub overhang_quartile_polygons: HashMap<u32, Vec<QuartileBand>>,
}

impl Default for SurfaceClassificationIR {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_SURFACE_CLASSIFICATION_SCHEMA_VERSION,
            per_object: HashMap::new(),
            overhang_quartile_polygons: HashMap::new(),
        }
    }
}

// ============================================================================
// Layer Plan IR Types
// ============================================================================

/// Config key type
pub type ConfigKey = String;

/// Config value type
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ConfigValue {
    /// Boolean value
    Bool(bool),
    /// Integer value
    Int(i64),
    /// Floating-point value
    Float(f64),
    /// String value
    String(String),
    /// List of config values
    List(Vec<ConfigValue>),
    /// Percent value (e.g. `25.0` meaning 25%). Always resolved relative to
    /// a base via [`ConfigView::get_abs_value`]; never coerced by the plain
    /// typed accessors (`get_float` etc. return `None`).
    Percent(f64),
    /// A value that is either a plain float (already absolute) or a
    /// percent of some base, mirroring OrcaSlicer's `ConfigOptionFloatOrPercent`.
    /// Mirrors the WIT `float-or-percent` record shape exactly.
    FloatOrPercent {
        /// The literal numeric value (absolute float, or percent magnitude
        /// when `is_percent` is true).
        value: f64,
        /// True when `value` should be interpreted as a percent of a base.
        is_percent: bool,
    },
}

impl PartialEq for ConfigValue {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::Bool(a), Self::Bool(b)) => a == b,
            (Self::Int(a), Self::Int(b)) => a == b,
            (Self::Float(a), Self::Float(b)) => a.to_bits() == b.to_bits(),
            (Self::String(a), Self::String(b)) => a == b,
            (Self::List(a), Self::List(b)) => a == b,
            (Self::Percent(a), Self::Percent(b)) => a.to_bits() == b.to_bits(),
            (
                Self::FloatOrPercent {
                    value: va,
                    is_percent: pa,
                },
                Self::FloatOrPercent {
                    value: vb,
                    is_percent: pb,
                },
            ) => va.to_bits() == vb.to_bits() && pa == pb,
            _ => false,
        }
    }
}

impl Eq for ConfigValue {}

impl std::hash::Hash for ConfigValue {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        std::mem::discriminant(self).hash(state);
        match self {
            Self::Bool(b) => b.hash(state),
            Self::Int(i) => i.hash(state),
            Self::Float(f) => f.to_bits().hash(state),
            Self::String(s) => s.hash(state),
            Self::List(v) => v.hash(state),
            Self::Percent(p) => p.to_bits().hash(state),
            Self::FloatOrPercent { value, is_percent } => {
                value.to_bits().hash(state);
                is_percent.hash(state);
            }
        }
    }
}

/// Config view (pre-filtered for specific module).
///
/// # Contract
///
/// Mirrors the `config-view` WIT resource (`wit/deps/config.wit`):
/// read-only and pre-filtered to a module's declared reads only. The
/// Rust side enforces this by keeping the backing `HashMap` private — all
/// consumers (host built-ins, guest modules, and tests) go through the
/// typed accessors (`get`, `get_bool`, `get_int`, `get_float`,
/// `get_string`, `get_float_list`, `get_string_list`, `keys`,
/// `iter_entries`) rather than touching the map directly (docs/03
/// §host-boundary access enforcement; docs/05 §module SDK).
///
/// # Construction
///
/// The only binding path allowed by the docs is pre-filtering to the
/// module's declared config keys. Use [`ConfigView::from_declared`] when
/// the host wires a config view for a compiled module; use
/// [`ConfigView::new`] or [`ConfigView::from_map`] for test fixtures that
/// simulate an already-filtered view.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ConfigView {
    // Private map. External construction goes through `from_map` /
    // `from_declared`; reads go through the typed accessors below. This
    // enforces the WIT `resource config-view { ... }` read-only
    // contract at the Rust boundary, so consumers cannot mutate a
    // view after the host synthesises it.
    fields: HashMap<ConfigKey, ConfigValue>,
}

impl ConfigView {
    /// Create an empty, already-frozen config view.
    #[must_use]
    pub fn new() -> Self {
        Self {
            fields: HashMap::new(),
        }
    }

    /// Wrap an existing `HashMap` as a config view without filtering.
    /// Intended for test fixtures only; live-path host code must use
    /// [`ConfigView::from_declared`].
    #[must_use]
    pub fn from_map(fields: HashMap<ConfigKey, ConfigValue>) -> Self {
        Self { fields }
    }

    /// Build a config view pre-filtered to `declared` keys — the only
    /// contract-compliant constructor for the live host/runtime path
    /// (docs/03 §host-boundary access enforcement; docs/02 §Pre-filtered
    /// config).
    ///
    /// Keys in `source` that are not in `declared` are dropped. Keys in
    /// `declared` that are not in `source` produce no entry (the typed
    /// accessors will return `None`, matching the undeclared/missing
    /// semantics modules already observe).
    #[must_use]
    pub fn from_declared<'a, I>(source: &HashMap<ConfigKey, ConfigValue>, declared: I) -> Self
    where
        I: IntoIterator<Item = &'a str>,
    {
        let mut fields = HashMap::new();
        for key in declared {
            if let Some(value) = source.get(key) {
                fields.insert(key.to_string(), value.clone());
            }
        }
        Self { fields }
    }

    /// Typed read: return the raw `ConfigValue` for `key`, if present.
    #[must_use]
    pub fn get(&self, key: &str) -> Option<&ConfigValue> {
        self.fields.get(key)
    }

    /// Typed read: `bool` value, or `None` if missing/other type.
    #[must_use]
    pub fn get_bool(&self, key: &str) -> Option<bool> {
        match self.fields.get(key)? {
            ConfigValue::Bool(b) => Some(*b),
            _ => None,
        }
    }

    /// Typed read: `i64` value, or `None` if missing/other type.
    #[must_use]
    pub fn get_int(&self, key: &str) -> Option<i64> {
        match self.fields.get(key)? {
            ConfigValue::Int(i) => Some(*i),
            _ => None,
        }
    }

    /// Typed read: `f64` value with subnormal normalization
    /// (subnormals are coerced to `0.0`), matching the WIT boundary
    /// behavior in `slicer-runtime::wit_host::normalize_subnormal_boundary`
    /// and the schema parser's `normalize_subnormal`.
    /// Returns `None` if missing/other type.
    ///
    /// `Percent` never coerces here — no base is available. `FloatOrPercent`
    /// only yields its literal when `is_percent` is `false`; when the value
    /// is a percent, callers MUST resolve it via [`ConfigView::get_abs_value`].
    #[must_use]
    pub fn get_float(&self, key: &str) -> Option<f64> {
        match self.fields.get(key)? {
            ConfigValue::Float(f) => Some(if f.is_subnormal() { 0.0 } else { *f }),
            ConfigValue::FloatOrPercent {
                value,
                is_percent: false,
            } => Some(if value.is_subnormal() { 0.0 } else { *value }),
            _ => None,
        }
    }

    /// Typed read: `String` value, or `None` if missing/other type.
    #[must_use]
    pub fn get_string(&self, key: &str) -> Option<&str> {
        match self.fields.get(key)? {
            ConfigValue::String(s) => Some(s.as_str()),
            _ => None,
        }
    }

    /// Read-time resolver for `percent` / `float_or_percent` config values,
    /// mirroring OrcaSlicer's `ConfigOptionFloatOrPercent::get_abs_value`.
    ///
    /// * `Percent(p)` resolves to `p / 100.0 * base` when `base > 0.0`,
    ///   otherwise `None` (a percent of a non-positive base is undefined).
    /// * `FloatOrPercent { value, is_percent }` resolves the same way when
    ///   `is_percent` is `true`; when `false`, `value` is already absolute
    ///   and is returned unchanged regardless of `base`.
    /// * `Float(f)` is already absolute and is returned unchanged.
    /// * Any other variant, or a missing key, yields `None`.
    #[must_use]
    pub fn get_abs_value(&self, key: &str, base: f64) -> Option<f64> {
        match self.fields.get(key)? {
            ConfigValue::Percent(p) => {
                if base > 0.0 {
                    Some(p / 100.0 * base)
                } else {
                    None
                }
            }
            ConfigValue::FloatOrPercent { value, is_percent } => {
                if *is_percent {
                    if base > 0.0 {
                        Some(value / 100.0 * base)
                    } else {
                        None
                    }
                } else {
                    Some(*value)
                }
            }
            ConfigValue::Float(f) => Some(*f),
            _ => None,
        }
    }

    /// Return all keys visible to the module, sorted for deterministic
    /// iteration (mirrors the WIT `keys()` contract).
    #[must_use]
    pub fn keys(&self) -> Vec<String> {
        let mut out: Vec<String> = self.fields.keys().cloned().collect();
        out.sort();
        out
    }

    /// True if `key` is visible to the module.
    #[must_use]
    pub fn contains_key(&self, key: &str) -> bool {
        self.fields.contains_key(key)
    }

    /// Number of declared keys visible to the module.
    #[must_use]
    pub fn len(&self) -> usize {
        self.fields.len()
    }

    /// True when no keys are visible.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.fields.is_empty()
    }

    /// Deterministically iterate all `(key, value)` pairs visible to the
    /// module, ordered by key. Used by non-typed consumers (e.g. the
    /// Python postpass bridge) that need to ship every declared value
    /// to a foreign runtime without additional round-trip host calls.
    pub fn iter_entries(&self) -> impl Iterator<Item = (&str, &ConfigValue)> {
        let mut keys: Vec<&str> = self.fields.keys().map(String::as_str).collect();
        keys.sort();
        keys.into_iter()
            .map(move |k| (k, self.fields.get(k).expect("iter_entries: key vanished")))
    }
}

impl Default for ConfigView {
    fn default() -> Self {
        Self::new()
    }
}

/// Non-planar shell reference
#[derive(Debug, Clone, Copy, Default, PartialEq, Serialize, Deserialize)]
pub struct NonPlanarShellRef {
    /// ID of the surface group this shell belongs to
    pub surface_group_id: SurfaceGroupId,
    /// Index of the shell (0 = top surface, 1..N = internal shells)
    pub shell_index: u32,
}

// `ResolvedConfig` is generated by the `declare_resolved_config!` macro
// invocation in `crate::resolved_config`. The struct, its `Default` impl,
// and the CLI-key dispatch (`apply_cli_key`) all come from a single
// declaration list there.

/// Active region in a global layer
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ActiveRegion {
    /// Object ID this region belongs to
    pub object_id: ObjectId,
    /// Region ID
    pub region_id: RegionId,
    /// Fully resolved config for this region
    pub resolved_config: ResolvedConfig,
    /// Effective layer height for this region
    pub effective_layer_height: f32,
    /// Non-planar shell reference (optional)
    pub nonplanar_shell: Option<NonPlanarShellRef>,
    /// True if this region skipped the previous global Z and is catching up
    pub is_catchup_layer: bool,
    /// Bottom Z of the catchup layer
    pub catchup_z_bottom: f32,
    /// Tool/filament index for this region
    pub tool_index: u32,
}

/// Global layer
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GlobalLayer {
    /// Index of the global layer
    pub index: u32,
    /// Z height of the layer
    pub z: f32,
    /// Active regions in this layer
    pub active_regions: Vec<ActiveRegion>,
    /// True if the layer contains non-planar features
    pub has_nonplanar: bool,
    /// True if multiple objects with different layer heights align at this Z
    pub is_sync_layer: bool,
}

/// Object layer reference
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ObjectLayerRef {
    /// Local layer index within the object
    pub local_layer_index: u32,
    /// Global layer index in the scene
    pub global_layer_index: u32,
    /// Effective layer height for this layer
    pub effective_layer_height: f32,
}

/// Layer plan IR
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LayerPlanIR {
    /// Schema version of this IR
    pub schema_version: SemVer,
    /// Global layers in the plan
    pub global_layers: Vec<GlobalLayer>,
    /// Per-object layer participation mapping
    pub object_participation: HashMap<ObjectId, Vec<ObjectLayerRef>>,
}

impl Default for LayerPlanIR {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_LAYER_PLAN_IR_SCHEMA_VERSION,
            global_layers: Vec::new(),
            object_participation: HashMap::new(),
        }
    }
}

// ============================================================================
// Seam Plan IR Types
// ============================================================================

/// One scored seam candidate from the prepass planner.
///
/// Used both inside `SeamPlanEntry.scored_candidates` and as the
/// `SeamPlanEntry.chosen_candidate` selected by the planning algorithm.
/// The `score` field is the primary sort key; lower is better.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ScoredSeamCandidate {
    /// Candidate position with extrusion width.
    pub position: Point3WithWidth,
    /// Normalized seam score (lower = preferred).
    pub score: f32,
    /// Enum tag explaining why this candidate was scored this way.
    pub reason: SeamReason,
}

/// One entry in the global seam plan.
///
/// Produced once per `(global_layer_index, object_id, region_id)` triple
/// by `PrePass::SeamPlanning` and stored immutably on the blackboard.
/// Consumed at dispatch time by `Layer::PerimetersPostProcess` to seed
/// `PerimeterRegionView.resolved_seam` so the apply-stage module
/// (seam-placer) operates on a pre-resolved seam without rescoring.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SeamPlanEntry {
    /// Stable region key for lookup during layer dispatch.
    pub region_key: RegionKey,
    /// The seam position selected by the planner.
    pub chosen_candidate: SeamPosition,
    /// Full scored candidate list for evidence and regression checks.
    pub scored_candidates: Vec<ScoredSeamCandidate>,
}

/// Seam plan IR — committed once to the blackboard by `PrePass::SeamPlanning`.
///
/// Stored as write-once on the blackboard alongside the other prepass
/// artifacts. Consumed by the layer dispatch path to inject resolved
/// seams into `PerimeterRegionView` before `seam-placer` runs.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SeamPlanIR {
    /// Schema version of this IR.
    pub schema_version: SemVer,
    /// One entry per active `(layer, object, region)` triple.
    pub entries: Vec<SeamPlanEntry>,
}

impl Default for SeamPlanIR {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_SEAM_PLAN_IR_SCHEMA_VERSION,
            entries: Vec::new(),
        }
    }
}

// ============================================================================
// Support Plan IR Types
// ============================================================================

/// One entry in the global support plan.
///
/// Produced once per `(global_layer_index, object_id, region_id)` triple
/// by `PrePass::SupportGeometry` and stored immutably on the blackboard.
/// Consumed at dispatch time by `Layer::Support` modules (notably
/// `tree-support`) that emit pre-planned organic branch geometry instead
/// of running a per-layer filler.
///
/// `global_layer_index` uses a signed integer to support raft prefix layers:
/// raft entries carry negative indices (`-1, -2, ..., -raft_layers`) so raft
/// always sorts before model layers (which use `0, 1, 2, ...`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SupportPlanEntry {
    /// Global (inter-object) layer index this entry applies to.
    /// Negative values (`-1`, `-2`, ...) are reserved for raft prefix layers.
    /// Non-negative values (`0`, `1`, ...) refer to model layers.
    pub global_layer_index: i32,
    /// Object the branches belong to.
    pub object_id: ObjectId,
    /// Region inside the object the branches belong to.
    pub region_id: RegionId,
    /// Planned branch geometry for this `(layer, object, region)` triple.
    /// Each `ExtrusionPath3D` is typically a two-point segment (a single
    /// MST edge) but may be multi-point for long merged branches.
    pub branch_segments: Vec<ExtrusionPath3D>,
}

/// Support plan IR — committed once to the blackboard by
/// `PrePass::SupportGeometry`.
///
/// Carries per-layer organic branch geometry produced by a simplified
/// OrcaSlicer-style top-down propagation (see the `support-planner`
/// core module). The per-layer `Layer::Support` tree-support module
/// consumes the plan when it is committed and emits branch segments
/// directly; modules whose algorithm is inherently per-layer (e.g.
/// `traditional-support`) do not read this IR.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SupportPlanIR {
    /// Schema version of this IR.
    pub schema_version: SemVer,
    /// One entry per active `(layer, object, region)` triple that received
    /// planned branches. Multiple entries may share `(layer, object)` when
    /// a single object has multiple regions on the same layer.
    pub entries: Vec<SupportPlanEntry>,
}

impl Default for SupportPlanIR {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_SUPPORT_PLAN_IR_SCHEMA_VERSION,
            entries: Vec::new(),
        }
    }
}

// ============================================================================
// Support Geometry IR Types
// ============================================================================

/// Key uniquely identifying one support geometry entry.
#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SupportGeometryKey {
    /// Model layer index that this support geometry entry applies to.
    /// `u32::MAX` sentinel = intermediate model-resolution layer.
    /// Consumers (e.g. `support-planner/src/lib.rs:211`) index
    /// `Vec<LayerCollisionCache>` directly with this value.
    pub global_support_layer_index: u32,
    /// Object this entry belongs to.
    pub object_id: ObjectId,
    /// Region identifier within the object.
    pub region_id: RegionId,
}

/// Support geometry IR — coarse outline prepass results.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SupportGeometryIR {
    /// Schema version of this IR.
    pub schema_version: SemVer,
    /// 0.0 = use model layer height (config schema enforces min > 0).
    pub support_layer_height_mm: f32,
    /// Distance in mm from column tops to add intermediate model layers.
    pub support_top_z_distance_mm: f32,
    /// Per-(layer, object, region) coarse outline polygons.
    pub entries: HashMap<SupportGeometryKey, Vec<ExPolygon>>,
}

impl Default for SupportGeometryIR {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_SUPPORT_GEOMETRY_IR_SCHEMA_VERSION,
            support_layer_height_mm: 0.0,
            support_top_z_distance_mm: 0.0,
            entries: HashMap::new(),
        }
    }
}

// ============================================================================
// Lightning Tree IR Types
// ============================================================================

/// One 2-point tree-edge segment for a lightning sparse-infill tree on a
/// single (object, layer). Compact 2-point integer-unit storage per ADR-0029
/// (no full topology; the per-layer `Layer::Infill` module reads these as
/// straight segments and does not need branch structure).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct LightningTreeEntry {
    /// Object this entry belongs to.
    pub object_id: ObjectId,
    /// Global model layer index this entry applies to.
    pub global_layer_index: i32,
    /// 2-point tree-edge segments in integer units. The consumer (packet
    /// 140's lightning-infill module) renders each pair as a straight
    /// segment. 139 is responsible for emitting the actual content; the
    /// 137 producer skeleton commits an empty `entries` Vec.
    pub tree_edge_segments: Vec<[Point2; 2]>,
}

/// Lightning tree IR — per-object, per-layer tree-edge segments produced by
/// the `PrePass::LightningTreeGen` stage. Consumed by the per-layer
/// `Layer::Infill` module via the `lightning-tree-segments` WIT view.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LightningTreeIR {
    /// Schema version of this IR.
    pub schema_version: SemVer,
    /// One entry per active `(object, layer)` triple that received lightning
    /// tree-edge segments. Multiple entries may share an `object_id` when
    /// the object spans multiple layers.
    pub entries: Vec<LightningTreeEntry>,
}

impl Default for LightningTreeIR {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_LIGHTNING_TREE_IR_SCHEMA_VERSION,
            entries: Vec::new(),
        }
    }
}

// ============================================================================
// Region Map IR Types
// ============================================================================

/// Region key (unique identifier for a region in a layer)
#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RegionKey {
    /// Global layer index
    pub global_layer_index: u32,
    /// Object ID
    pub object_id: ObjectId,
    /// Region ID
    pub region_id: RegionId,
    /// Ordered (paint_semantic_name, value) pairs identifying this region's paint variant.
    /// Empty for the legacy single-variant flow; populated by P1c (packet 93) when
    /// RegionMapping cross-product lands.
    #[serde(default)]
    pub variant_chain: Vec<(String, PaintValue)>,
}

/// Module invocation
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ModuleInvocation {
    /// ID of the module to invoke
    pub module_id: ModuleId,
    /// Configuration view for the module
    pub config_view: ConfigView,
}

/// Region plan
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RegionPlan {
    /// Interned config index into `RegionMapIR.configs`.
    /// Resolve via `RegionMapIR::config_for(&key)`.
    pub config: ConfigId,
    /// Module invocations per stage
    pub stage_modules: HashMap<StageId, Vec<ModuleInvocation>>,
    /// Per-paint-semantic config overrides (empty when no paint overrides apply)
    pub paint_overrides: BTreeMap<PaintSemantic, ResolvedConfig>,
}

/// Default cap on `RegionMapIR` entry count per docs/04_host_scheduler.md.
///
/// **P93 raise — `1_000` → `750_000`.**
///
/// Pre-P93 the cap was `1_000`, sized for single-entry-per-region scenes
/// (one variant chain per `(layer, ActiveRegion)`). P93 introduces the
/// region-split cross-product, so each `(layer, ActiveRegion)` now expands
/// into one `RegionPlan` per canonical variant chain — cardinality
/// `∏(1 + K_i)` where `K_i` is the number of opted-in paint values for
/// semantic `i` on that object.
///
/// 750× headroom rationale: a worst-realistic envelope of 16 colors × 1000
/// layers × 16 regions × ~3 modifier subtypes ≈ 750k pre-modifier entries.
/// Realistic 4-color × 200-layer × 4-region scenes land near ~3k entries,
/// comfortably under cap. Overflow surfaces the structured
/// [`RegionMappingError::CapExceeded`] diagnostic naming the top-contributing
/// `ObjectId` per AC-N2 (see
/// `crates/slicer-core/src/algos/region_mapping.rs`).
pub const DEFAULT_REGION_MAP_CAP: usize = 750_000;

/// Stable index into `RegionMapIR.configs`. Introduced in P1a (packet 91) so
/// duplicated `ResolvedConfig` payloads across painted-variant `RegionPlan`s
/// can intern to a single instance. Stable within one `RegionMapIR` only —
/// not portable across IRs.
#[derive(Copy, Clone, Debug, Default, Hash, Eq, PartialEq, Serialize, Deserialize)]
pub struct ConfigId(pub u32);

/// Region map IR
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RegionMapIR {
    /// Schema version of this IR
    pub schema_version: SemVer,
    /// Region plans keyed by region key
    pub entries: HashMap<RegionKey, RegionPlan>,
    /// Interned `ResolvedConfig` pool. Each `RegionPlan.config` is an index into
    /// this Vec. Use `RegionMapIR::intern_config` to add entries and
    /// `RegionMapIR::config_for` to resolve them.
    #[serde(default)]
    pub configs: Vec<ResolvedConfig>,
}

impl Default for RegionMapIR {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_REGION_MAP_IR_SCHEMA_VERSION,
            entries: HashMap::new(),
            // Pre-seed configs[0] with a default ResolvedConfig so ConfigId(0)
            // (i.e. ConfigId::default()) is always a valid interner index —
            // matches the packet 91 design invariant: legacy single-config flows
            // see a one-entry configs Vec; intern_config dedupes new configs in.
            configs: vec![ResolvedConfig::default()],
        }
    }
}

impl RegionMapIR {
    /// Resolves a raw `ConfigId` to its interned `ResolvedConfig`.
    ///
    /// Useful when the caller already has the `ConfigId` (e.g. from a
    /// `RegionPlan`) and does not need the full `RegionKey` lookup.
    pub fn config_for_raw(&self, id: ConfigId) -> &ResolvedConfig {
        &self.configs[id.0 as usize]
    }

    /// Resolves a `RegionKey` to its `ResolvedConfig` via the interner.
    /// Panics if the key is unknown or the ConfigId is out of bounds —
    /// both are construction invariants the interner upholds.
    pub fn config_for(&self, key: &RegionKey) -> &ResolvedConfig {
        let plan = self
            .entries
            .get(key)
            .expect("RegionKey not present in RegionMapIR.entries");
        &self.configs[plan.config.0 as usize]
    }

    /// Interns a `ResolvedConfig`, returning the existing `ConfigId` if an
    /// equal config is already present (linear scan — bounded by distinct
    /// configs per print job; revisit if profiling shows hot).
    pub fn intern_config(&mut self, rc: ResolvedConfig) -> ConfigId {
        if let Some(i) = self.configs.iter().position(|c| c == &rc) {
            ConfigId(i as u32)
        } else {
            self.configs.push(rc);
            ConfigId((self.configs.len() - 1) as u32)
        }
    }
}

// ============================================================================
// Slice IR Types
// ============================================================================

/// Polygon
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Polygon {
    /// List of points defining the polygon
    pub points: Vec<Point2>,
}

/// Polygon with holes
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExPolygon {
    /// Outer contour (CCW)
    pub contour: Polygon,
    /// Inner holes (CW)
    pub holes: Vec<Polygon>,
}

/// Sliced region
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SlicedRegion {
    /// Object ID this region belongs to
    pub object_id: ObjectId,
    /// Region ID
    pub region_id: RegionId,
    /// Closed polygon islands
    pub polygons: Vec<ExPolygon>,
    /// Inset polygons available for infill
    pub infill_areas: Vec<ExPolygon>,
    /// Non-planar surface group (optional)
    pub nonplanar_surface: Option<SurfaceGroupId>,
    /// Effective layer height
    pub effective_layer_height: f32,
    /// Per-segment paint annotations, populated only for paint semantics NOT declared `[[region_split]]` in a module manifest.
    /// Semantics that ARE region-split surface through SlicedRegion.variant_chain instead (see P1a/P1c).
    #[serde(default)]
    pub segment_annotations: HashMap<PaintSemantic, Vec<Vec<Option<PaintValue>>>>,
    /// Ordered (paint_semantic_name, value) pairs identifying this region's variant.
    /// Empty in the legacy single-variant flow; populated by P1c (93).
    #[serde(default)]
    pub variant_chain: Vec<(String, PaintValue)>,
    /// Minimum depth (in layers, 0 = exposed) within the top shell zone. `None` outside any top shell.
    #[serde(default)]
    pub top_shell_index: Option<u8>,
    /// Minimum depth within the bottom shell zone. `None` outside any bottom shell.
    #[serde(default)]
    pub bottom_shell_index: Option<u8>,
    /// Polygon-precise area to solid-fill from top shell projection.
    #[serde(default)]
    pub top_solid_fill: Vec<ExPolygon>,
    /// Polygon-precise area to solid-fill from bottom shell projection.
    #[serde(default)]
    pub bottom_solid_fill: Vec<ExPolygon>,
    /// True if this region spans an unsupported gap (bridge)
    #[serde(default)]
    pub is_bridge: bool,
    /// Per-layer expanded bridge polygons
    #[serde(default)]
    pub bridge_areas: Vec<ExPolygon>,
    /// Best bridge direction across all valid bridge regions (degrees)
    #[serde(default)]
    pub bridge_orientation_deg: f32,
    /// Sparse-only infill polygon after host-side fill partition.
    /// Empty until `Layer::Perimeters` commits — the host then computes
    /// `perimeter.infill_areas − union(bridge_areas, bottom_solid_fill, top_solid_fill)`
    /// with precedence `bridge > bottom > top > sparse`. The four canonical
    /// fill polygons (`bridge_areas`, `bottom_solid_fill`, `top_solid_fill`,
    /// `sparse_infill_area`) are pairwise disjoint subsets of
    /// `perimeter.infill_areas` after that hook. See
    /// `crates/slicer-runtime/src/region_partition.rs`.
    #[serde(default)]
    pub sparse_infill_area: Vec<ExPolygon>,
}

/// Slice IR
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SliceIR {
    /// Schema version of this IR
    pub schema_version: SemVer,
    /// Global layer index
    pub global_layer_index: u32,
    /// Z height of the layer
    pub z: f32,
    /// Sliced regions in this layer
    pub regions: Vec<SlicedRegion>,
}

impl Default for SliceIR {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_SLICE_IR_SCHEMA_VERSION,
            global_layer_index: 0,
            z: 0.0,
            regions: Vec::new(),
        }
    }
}

// ============================================================================
// Perimeter IR Types
// ============================================================================

/// Wall generator type
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum WallGenerator {
    /// Classic wall generator
    #[default]
    Classic,
    /// Arachne variable-width wall generator
    Arachne,
}

/// Infill type
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum InfillType {
    /// Grid infill
    #[default]
    Grid,
    /// Triangles infill
    Triangles,
    /// Honeycomb infill
    Honeycomb,
    /// Gyroid infill
    Gyroid,
    /// Lightning infill
    Lightning,
    /// Line infill
    Line,
    /// Concentric infill
    Concentric,
}

/// Support type
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SupportType {
    /// Traditional support generation
    #[default]
    Traditional,
    /// Tree support generation
    Tree,
}

/// A segment of a material boundary transition on a wall polygon.
///
/// Each segment records the point range (half-open `[start, end)`) on the
/// polygon contour where two different tool indices are adjacent. `near_tool`
/// is the tool on the inside of the wall; `far_tool` is the tool on the
/// outside. Either may be `None` when the polygon edge is adjacent to air or
/// a gap.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MaterialBoundarySegment {
    /// Half-open range `[start, end)` of point indices on the polygon contour
    /// where this boundary transition occurs.
    pub point_range: std::ops::Range<u32>,
    /// Tool index on the near side of the boundary (inside the wall).
    pub near_tool: Option<u32>,
    /// Tool index on the far side of the boundary (outside the wall).
    pub far_tool: Option<u32>,
}

/// Wall boundary type
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(into = "WallBoundaryTypeWire")]
pub enum WallBoundaryType {
    /// Outer wall facing air or a gap
    ExteriorSurface,
    /// Wall adjacent to a different material region
    MaterialBoundary {
        /// List of boundary segments describing each material transition
        segments: Vec<MaterialBoundarySegment>,
    },
    /// Inner wall — no special boundary handling
    Interior,
}

/// Wire format for `WallBoundaryType` that supports deserializing the
/// pre-4.2.0 `{ adjacent_tool: u32 }` shape via `#[serde(default)]`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
enum WallBoundaryTypeWire {
    ExteriorSurface,
    MaterialBoundary {
        #[serde(default)]
        segments: Vec<MaterialBoundarySegment>,
        #[serde(default)]
        adjacent_tool: Option<u32>,
    },
    Interior,
}

impl From<WallBoundaryTypeWire> for WallBoundaryType {
    fn from(wire: WallBoundaryTypeWire) -> Self {
        match wire {
            WallBoundaryTypeWire::ExteriorSurface => WallBoundaryType::ExteriorSurface,
            WallBoundaryTypeWire::Interior => WallBoundaryType::Interior,
            WallBoundaryTypeWire::MaterialBoundary {
                segments,
                adjacent_tool,
            } => {
                // Precedence: a non-empty `segments` list always wins. The
                // legacy `adjacent_tool` field is consulted ONLY to migrate the
                // pre-4.2.0 single-tool shape (which had no `segments`); if a
                // payload somehow carries both, the richer `segments` list is
                // authoritative and `adjacent_tool` is dropped.
                let segments = if let Some(tool) = adjacent_tool {
                    if segments.is_empty() {
                        vec![MaterialBoundarySegment {
                            point_range: 0..1,
                            near_tool: None,
                            far_tool: Some(tool),
                        }]
                    } else {
                        segments
                    }
                } else {
                    segments
                };
                WallBoundaryType::MaterialBoundary { segments }
            }
        }
    }
}

impl From<WallBoundaryType> for WallBoundaryTypeWire {
    fn from(value: WallBoundaryType) -> Self {
        match value {
            WallBoundaryType::ExteriorSurface => WallBoundaryTypeWire::ExteriorSurface,
            WallBoundaryType::Interior => WallBoundaryTypeWire::Interior,
            WallBoundaryType::MaterialBoundary { segments } => {
                WallBoundaryTypeWire::MaterialBoundary {
                    segments,
                    adjacent_tool: None,
                }
            }
        }
    }
}

impl<'de> Deserialize<'de> for WallBoundaryType {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let wire = WallBoundaryTypeWire::deserialize(deserializer)?;
        Ok(WallBoundaryType::from(wire))
    }
}

/// Loop type
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LoopType {
    /// Outer loop
    Outer,
    /// Inner loop
    Inner,
    /// Thin wall loop
    ThinWall,
    /// Non-planar shell loop
    NonPlanarShell,
    /// Gap-fill loop (T-062b)
    GapFill,
}

/// Wall feature flags
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WallFeatureFlags {
    /// Tool override for this segment
    pub tool_index: Option<u32>,
    /// Enables fuzzy skin modulation
    pub fuzzy_skin: bool,
    /// Segment is bridge-like
    pub is_bridge: bool,
    /// Segment belongs to thin-wall logic
    pub is_thin_wall: bool,
    /// If true, force skip of ironing behavior
    pub skip_ironing: bool,
    /// Custom paint values keyed by PaintSemantic::Custom module ID
    pub custom: HashMap<String, PaintValue>,
}

/// Width profile (for variable-width extrusion)
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WidthProfile {
    /// One width per vertex in path.points
    pub widths: Vec<f32>,
}

/// Point with width (for extrusion paths)
#[derive(Debug, Clone, Copy, Default, PartialEq, Serialize, Deserialize)]
pub struct Point3WithWidth {
    /// X coordinate in millimeters
    pub x: f32,
    /// Y coordinate in millimeters
    pub y: f32,
    /// Z coordinate in millimeters
    pub z: f32,
    /// Local extrusion width in millimeters
    pub width: f32,
    /// Multiplier on base extrusion volume
    pub flow_factor: f32,
    /// Overhang severity quartile (0-3), None if not classified
    #[serde(default)]
    pub overhang_quartile: Option<u8>,
}

/// Extrusion role
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ExtrusionRole {
    /// Outer wall
    OuterWall,
    /// Inner wall
    InnerWall,
    /// Thin wall
    ThinWall,
    /// Top solid infill
    TopSolidInfill,
    /// Bottom solid infill
    BottomSolidInfill,
    /// Internal solid infill — the solid shell layers *beneath* an exposed top
    /// surface or *above* an exposed bottom surface (top/bottom shell depth ≥ 1).
    /// OrcaSlicer role `stInternalSolid`; emitted as `;TYPE:Internal solid infill`.
    InternalSolidInfill,
    /// Sparse infill
    SparseInfill,
    /// Support material
    SupportMaterial,
    /// Support interface
    SupportInterface,
    /// Wipe tower
    WipeTower,
    /// Prime tower
    PrimeTower,
    /// Ironing
    Ironing,
    /// Bridge infill
    BridgeInfill,
    /// Skirt / brim
    Skirt,
    /// Brim (bed-adhesion loops). Shares the skirt/brim module's geometry
    /// with `Skirt` but is a distinct role so the g-code viewer can label
    /// it `;TYPE:Brim` (OrcaSlicer parity) rather than collapsing both
    /// into one `;TYPE:Skirt/Brim` "Undefined" bucket.
    Brim,
    /// Custom role
    Custom(String),
    /// Gap-fill extrusion (T-062b)
    GapFill,
}

impl ExtrusionRole {
    /// Returns the default print priority for this role.
    /// Values mirror the canonical producer-emit order used by Packet 40's
    /// stable-sort merge: lower = printed first, gaps ≥ 100 guarantee
    /// unambiguous slot insertion for finalization-pushed entities.
    pub const fn default_priority(&self) -> u32 {
        match self {
            Self::Skirt => 0,
            Self::Brim => 110,
            Self::OuterWall => 1000,
            Self::InnerWall => 1500,
            Self::ThinWall => 1700,
            Self::SparseInfill => 3000,
            Self::BridgeInfill => 3500,
            Self::InternalSolidInfill => 3800,
            Self::BottomSolidInfill => 4000,
            Self::TopSolidInfill => 4500,
            Self::SupportMaterial => 5000,
            Self::SupportInterface => 5500,
            Self::Ironing => 6000,
            Self::WipeTower => 8000,
            Self::PrimeTower => 8500,
            Self::Custom(_) => 9000,
            Self::GapFill => 2000,
        }
    }

    /// Returns `true` for roles whose extrusion entity is conventionally a
    /// closed loop — wall loops and perimeter-like outlines.
    ///
    /// Used by the G-code emitter's defensive closure check
    /// (`crates/slicer-gcode/src/emit.rs`) and by future wall-mutator audits.
    /// Roles in this set should carry an explicit closing repeat
    /// (`ExtrusionPath3D::is_closed()` returns true) by the time they reach
    /// emission; an open path with one of these roles is a sign that some
    /// post-process step dropped the closing repeat.
    ///
    /// Returns `true` for: `OuterWall`, `InnerWall`, `ThinWall`, `Skirt`, `Brim`.
    /// `Custom(_)` is conservatively treated as `false` — a custom-role path
    /// could be a polyline or a loop; the consumer should classify.
    pub const fn is_loop(&self) -> bool {
        matches!(
            self,
            Self::OuterWall | Self::InnerWall | Self::ThinWall | Self::Skirt | Self::Brim
        )
    }
}

/// 2D point with an associated local extrusion width (in millimeters).
///
/// Used by `ThickPolyline` to represent variable-width centerline paths before
/// they are lifted to 3D via `variable_width()`.
#[derive(Debug, Clone, Copy, Default, PartialEq, Serialize, Deserialize)]
pub struct Point2WithWidth {
    /// X coordinate in millimeters
    pub x: f32,
    /// Y coordinate in millimeters
    pub y: f32,
    /// Local extrusion width in millimeters
    pub width: f32,
}

/// A variable-width 2D centerline polyline.
///
/// Produced by `medial_axis` (simplified long-axis-spine approximation in M1;
/// full Voronoi-based medial axis deferred to M2).  Converted to a 3D
/// `ExtrusionPath3D` via `variable_width()` once the caller knows the layer Z.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ThickPolyline {
    /// Ordered centerline points with per-vertex width
    pub points: Vec<Point2WithWidth>,
}

/// Convert a variable-width centerline polyline into a 3D extrusion path.
///
/// Canonical construction defaults (mirrors skirt-brim helper):
/// `z = 0.0` (caller supplies layer Z later), `flow_factor = 1.0`,
/// `overhang_quartile = None`, `speed_factor = 1.0`.
pub fn variable_width(thick: &ThickPolyline, role: ExtrusionRole) -> ExtrusionPath3D {
    ExtrusionPath3D {
        points: thick
            .points
            .iter()
            .map(|p| Point3WithWidth {
                x: p.x,
                y: p.y,
                z: 0.0,
                width: p.width,
                flow_factor: 1.0,
                overhang_quartile: None,
            })
            .collect(),
        role,
        speed_factor: 1.0,
    }
}

/// 3D extrusion path
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ExtrusionPath3D {
    /// List of 3D points with width
    pub points: Vec<Point3WithWidth>,
    /// Role of this extrusion path
    pub role: ExtrusionRole,
    /// Speed factor multiplier
    pub speed_factor: f32,
}

impl ExtrusionPath3D {
    /// Returns `true` when this path represents a closed loop encoded by an
    /// explicit closing repeat: `points.first().xy == points.last().xy`.
    ///
    /// Mirrors OrcaSlicer's `ExtrusionPath::is_closed()`
    /// (`OrcaSlicerDocumented/src/libslic3r/ExtrusionEntity.hpp:269`). Wall
    /// loops, skirt/brim loops, and any other closed extrusion entity use
    /// this convention; open paths (sparse infill, travel) do not.
    ///
    /// Only the XY components of the first and last points are compared. Z
    /// and per-vertex width may differ between the first and last entries
    /// for entities that vary along the loop (bricklayer Z-shift,
    /// arachne-perimeters variable width); the XY endpoints must coincide
    /// so the closing edge has zero planar length.
    pub fn is_closed(&self) -> bool {
        match (self.points.first(), self.points.last()) {
            (Some(first), Some(last)) if self.points.len() >= 2 => {
                first.x == last.x && first.y == last.y
            }
            _ => false,
        }
    }
}

/// A single junction (vertex) of an `ExtrusionLine`.
///
/// Mirrors OrcaSlicer's Arachne `ExtrusionJunction`
/// (`OrcaSlicerDocumented/src/libslic3r/PerimeterGenerator.hpp`): a
/// beading-strategy vertex carrying its own local width plus the perimeter
/// index it was generated for. Part of the Arachne beading-strategy-stack
/// (packet 112, T-224); no consumer wires this into the WASM boundary yet.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct ExtrusionJunction {
    /// 3D position, local width, flow factor, and overhang classification.
    pub p: Point3WithWidth,
    /// Perimeter index this junction was generated for (0 = outermost).
    #[serde(default)]
    pub perimeter_index: u32,
}

/// A variable-width extrusion line produced by the Arachne beading-strategy
/// stack, prior to conversion into the existing `ExtrusionPath3D` wall
/// surface via [`extrusion_line_to_extrusion_path3d`].
///
/// Mirrors OrcaSlicer's Arachne `ExtrusionLine`
/// (`OrcaSlicerDocumented/src/libslic3r/PerimeterGenerator.hpp`). Part of the
/// Arachne beading-strategy-stack (packet 112, T-224); no consumer wires this
/// into the WASM boundary yet.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct ExtrusionLine {
    /// Ordered junctions (vertices) making up this line.
    pub junctions: Vec<ExtrusionJunction>,
    /// Inset index this line belongs to (0 = outermost wall).
    pub inset_idx: u32,
    /// True if this line was generated as part of an odd-width transition
    /// region rather than a uniform-bead perimeter.
    #[serde(default)]
    pub is_odd: bool,
    /// True when this line forms a closed loop (first and last junction
    /// coincide in XY), mirroring `ExtrusionPath3D::is_closed()`.
    #[serde(default)]
    pub is_closed: bool,
}

/// Type alias for a collection of Arachne beading-strategy `ExtrusionLine`s,
/// mirroring OrcaSlicer's `VariableWidthLines` (a `vector<ExtrusionLine>`).
/// Used by later Arachne beading-strategy-stack steps (packet 112, Steps 4-7).
pub type VariableWidthLines = Vec<ExtrusionLine>;

/// Convert an `ExtrusionLine` into the existing `ExtrusionPath3D` wall surface.
///
/// Bridges the Arachne beading-strategy stack's variable-width line
/// representation onto the established `ExtrusionPath3D` consumed by
/// downstream wall/G-code emission. `speed_factor` is set to the canonical
/// default `1.0`; callers that need per-line speed overrides should adjust
/// the returned value.
pub fn extrusion_line_to_extrusion_path3d(
    line: &ExtrusionLine,
    role: ExtrusionRole,
) -> ExtrusionPath3D {
    ExtrusionPath3D {
        points: line.junctions.iter().map(|j| j.p).collect(),
        role,
        speed_factor: 1.0,
    }
}

/// Wall loop
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WallLoop {
    /// 0 = outermost
    pub perimeter_index: u32,
    /// Type of loop
    pub loop_type: LoopType,
    /// 3D extrusion path
    pub path: ExtrusionPath3D,
    /// Variable-width profile
    pub width_profile: WidthProfile,
    /// Per-vertex feature flags
    pub feature_flags: Vec<WallFeatureFlags>,
    /// Boundary type
    pub boundary_type: WallBoundaryType,
}

/// Seam reason
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SeamReason {
    /// Concave corner
    Concave,
    /// Aligned edge
    Aligned,
    /// User forced
    UserForced,
    /// Sharp corner
    Sharp,
}

/// Seam candidate
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SeamCandidate {
    /// Position of the candidate
    pub position: Point3WithWidth,
    /// Score of the candidate
    pub score: f32,
    /// Reason for the candidate
    pub reason: SeamReason,
}

/// Seam position
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SeamPosition {
    /// Position of the seam
    pub point: Point3WithWidth,
    /// Index of the wall
    pub wall_index: u32,
}

/// Perimeter region
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PerimeterRegion {
    /// Object ID this region belongs to
    pub object_id: ObjectId,
    /// Region ID
    pub region_id: RegionId,
    /// Wall loops in this region
    pub walls: Vec<WallLoop>,
    /// Remaining area after wall insets
    pub infill_areas: Vec<ExPolygon>,
    /// Seam candidates
    pub seam_candidates: Vec<SeamCandidate>,
    /// Resolved seam position
    pub resolved_seam: Option<SeamPosition>,
}

/// Perimeter IR
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PerimeterIR {
    /// Schema version of this IR
    pub schema_version: SemVer,
    /// Global layer index
    pub global_layer_index: u32,
    /// Perimeter regions in this layer
    pub regions: Vec<PerimeterRegion>,
}

impl Default for PerimeterIR {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_PERIMETER_IR_SCHEMA_VERSION,
            global_layer_index: 0,
            regions: Vec::new(),
        }
    }
}

// ============================================================================
// Infill IR Types
// ============================================================================

/// Infill region
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct InfillRegion {
    /// Object ID this region belongs to
    pub object_id: ObjectId,
    /// Region ID
    pub region_id: RegionId,
    /// Sparse infill paths
    pub sparse_infill: Vec<ExtrusionPath3D>,
    /// Solid infill paths
    pub solid_infill: Vec<ExtrusionPath3D>,
    /// Ironing paths
    pub ironing: Vec<ExtrusionPath3D>,
}

/// Infill IR
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct InfillIR {
    /// Schema version of this IR
    pub schema_version: SemVer,
    /// Global layer index
    pub global_layer_index: u32,
    /// Infill regions in this layer
    pub regions: Vec<InfillRegion>,
}

impl Default for InfillIR {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_INFILL_IR_SCHEMA_VERSION,
            global_layer_index: 0,
            regions: Vec::new(),
        }
    }
}

// ============================================================================
// Support IR Types
// ============================================================================

/// Support IR
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SupportIR {
    /// Schema version of this IR
    pub schema_version: SemVer,
    /// Global layer index
    pub global_layer_index: u32,
    /// Support paths
    pub support_paths: Vec<ExtrusionPath3D>,
    /// Interface paths
    pub interface_paths: Vec<ExtrusionPath3D>,
    /// Raft paths
    pub raft_paths: Vec<ExtrusionPath3D>,
    /// Ironing paths
    pub ironing_paths: Vec<ExtrusionPath3D>,
}

impl Default for SupportIR {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_SUPPORT_IR_SCHEMA_VERSION,
            global_layer_index: 0,
            support_paths: Vec::new(),
            interface_paths: Vec::new(),
            raft_paths: Vec::new(),
            ironing_paths: Vec::new(),
        }
    }
}

// ============================================================================
// Layer Collection IR Types
// ============================================================================

/// Tool change
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ToolChange {
    /// Index of the entity after which the tool change occurs
    pub after_entity_index: u32,
    /// Tool index to change from
    pub from_tool: u32,
    /// Tool index to change to
    pub to_tool: u32,
}

/// Z hop
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ZHop {
    /// Index of the entity after which the Z hop occurs
    pub after_entity_index: u32,
    /// Height of the Z hop in millimeters
    pub hop_height: f32,
}

/// Retract or unretract decision from `Layer::PathOptimization`, keyed by entity anchor.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct TravelRetract {
    /// Index of the entity after which this retract/unretract is anchored.
    pub after_entity_index: u32,
    /// Retraction length in mm.
    pub length: f32,
    /// Retraction speed in mm/s.
    pub speed: f32,
    /// `true` = Unretract; `false` = Retract.
    pub is_unretract: bool,
    /// Emit-mode: `Gcode` materializes as inline-E `G1` moves; `Firmware`
    /// materializes as bare `G10`/`G11` opcodes. Defaults to `Gcode` for
    /// callers that haven't been migrated to thread the mode field.
    #[serde(default)]
    pub mode: RetractMode,
}

/// Travel move destination from `Layer::PathOptimization`, keyed by entity anchor.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct TravelMove {
    /// Stable identifier of the entity in `LayerCollectionIR.ordered_entities` after which this
    /// travel is emitted. Resolved at emit time via a per-layer `HashMap<u64, usize>` lookup.
    pub entity_id: u64,
    /// X destination (millimeters, mm).
    pub x: Option<f32>,
    /// Y destination (millimeters, mm).
    pub y: Option<f32>,
    /// Z destination (millimeters, mm).
    pub z: Option<f32>,
    /// Feed-rate override in mm/s (`None` = keep current speed).
    pub f: Option<f32>,
}

/// Print entity
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PrintEntity {
    /// Per-layer-monotonic stable identifier issued by `LayerEntityIdGen` at construction.
    /// Reserved value `0` MAY be used as uninitialized sentinel; valid IDs start at 1.
    pub entity_id: u64,
    /// Extrusion path
    pub path: ExtrusionPath3D,
    /// Role of the entity
    pub role: ExtrusionRole,
    /// Region key
    pub region_key: RegionKey,
    /// Topological order
    pub topo_order: u32,
    /// Resolved tool/extruder index for this entity (a pure SELECTOR — see
    /// `dominant_tool_index` in `layer_executor.rs`). Separated from
    /// `region_key.region_id` (a pure region IDENTITY) so a painted-variant
    /// identity hash can never leak into the tool slot (the packet-125 OOM).
    /// `#[serde(default)]` keeps older serialized `PrintEntity`s deserializable;
    /// the struct intentionally has no `Default` derive so every construction
    /// site is compiler-forced to set this field.
    #[serde(default)]
    pub tool_index: u32,
}

/// Kind of a guest-emitted layer annotation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum LayerAnnotationKind {
    /// A GCode comment (prefixed with `;`).
    Comment(String),
    /// A raw GCode line to emit verbatim.
    Raw(String),
}

/// Guest-emitted annotation (comment / raw line) to splice into the emitted
/// GCode at `after_entity_index`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LayerAnnotation {
    /// Insert the annotation after the entity with this 0-based `topo_order`.
    pub after_entity_index: u32,
    /// The annotation body.
    pub kind: LayerAnnotationKind,
}

/// Layer collection IR
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LayerCollectionIR {
    /// Schema version of this IR
    pub schema_version: SemVer,
    /// Global layer index
    pub global_layer_index: u32,
    /// Z height of the layer
    pub z: f32,
    /// Ordered, ready-to-emit extrusion entities
    pub ordered_entities: Vec<PrintEntity>,
    /// Tool changes in this layer
    pub tool_changes: Vec<ToolChange>,
    /// Z hops in this layer
    pub z_hops: Vec<ZHop>,
    /// Guest-emitted per-layer annotations (comments / raw lines).
    pub annotations: Vec<LayerAnnotation>,
    /// Retract/unretract decisions from `Layer::PathOptimization`.
    pub retracts: Vec<TravelRetract>,
    /// Travel move destinations from `Layer::PathOptimization`.
    pub travel_moves: Vec<TravelMove>,
}

impl Default for LayerCollectionIR {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_LAYER_COLLECTION_IR_SCHEMA_VERSION,
            global_layer_index: 0,
            z: 0.0,
            ordered_entities: Vec::new(),
            tool_changes: Vec::new(),
            z_hops: Vec::new(),
            annotations: Vec::new(),
            retracts: Vec::new(),
            travel_moves: Vec::new(),
        }
    }
}

// ============================================================================
// GCode IR Types
// ============================================================================

/// Selects whether retract/unretract commands are emitted as explicit G-code
/// extruder moves (`Gcode`) or delegated to the printer firmware via `G10`/`G11`
/// (`Firmware`). Default callers pass `Gcode` to preserve packet-15 behavior.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
pub enum RetractMode {
    /// Slicer emits retract/unretract as explicit `G1 E...` moves.
    #[default]
    Gcode,
    /// Slicer emits firmware retract/unretract (`G10`/`G11`).
    Firmware,
}

/// GCode command
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum GCodeCommand {
    /// Move command
    Move {
        /// X coordinate
        x: Option<f32>,
        /// Y coordinate
        y: Option<f32>,
        /// Z coordinate
        z: Option<f32>,
        /// Extrusion amount
        e: Option<f32>,
        /// Feed rate
        f: Option<f32>,
        /// Role of the move
        role: ExtrusionRole,
    },
    /// Retract command
    Retract {
        /// Retraction length
        length: f32,
        /// Retraction speed
        speed: f32,
        /// Retract emission mode (G-code vs. firmware)
        mode: RetractMode,
    },
    /// Unretract command
    Unretract {
        /// Unretraction length
        length: f32,
        /// Unretraction speed
        speed: f32,
        /// Retract emission mode (G-code vs. firmware)
        mode: RetractMode,
    },
    /// Fan speed command
    FanSpeed {
        /// Fan speed value (0-255)
        value: u8,
    },
    /// Temperature command
    Temperature {
        /// Tool index
        tool: u32,
        /// Temperature in Celsius
        celsius: f32,
        /// Whether to wait for temperature
        wait: bool,
    },
    /// Tool change command
    ToolChange {
        /// Entity index after which this tool change occurs
        after_entity_index: u32,
        /// Tool index to change from
        from: u32,
        /// Tool index to change to
        to: u32,
    },
    /// Comment command
    Comment {
        /// Comment text
        text: String,
    },
    /// Raw GCode command
    Raw {
        /// Raw text
        text: String,
    },
    /// Extrusion mode selector (M82 = absolute, M83 = relative)
    ExtrusionMode {
        /// `true` = absolute-E mode (M82); `false` = relative-E mode (M83).
        absolute: bool,
    },
}

/// Print metadata
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PrintMetadata {
    /// Estimated print time in seconds
    pub estimated_print_time_s: u32,
    /// Filament used per tool in millimeters
    pub filament_used_mm: Vec<f32>,
    /// Total layer count
    pub layer_count: u32,
    /// Slicer version string
    pub slicer_version: String,
}

/// GCode IR
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GCodeIR {
    /// Schema version of this IR
    pub schema_version: SemVer,
    /// List of GCode commands
    pub commands: Vec<GCodeCommand>,
    /// Print metadata
    pub metadata: PrintMetadata,
}

impl Default for GCodeIR {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_GCODE_IR_SCHEMA_VERSION,
            commands: Vec::new(),
            metadata: PrintMetadata::default(),
        }
    }
}

#[cfg(test)]
mod lightning_tree_ir_tests {
    use super::{LightningTreeIR, CURRENT_LIGHTNING_TREE_IR_SCHEMA_VERSION};

    #[test]
    fn default_uses_current_schema_version() {
        let ir = LightningTreeIR::default();
        assert_eq!(ir.schema_version, CURRENT_LIGHTNING_TREE_IR_SCHEMA_VERSION);
        assert!(ir.entries.is_empty());
    }
}

#[cfg(test)]
mod config_value_percent_tests {
    //! Unit tests for `ConfigValue::Percent` / `ConfigValue::FloatOrPercent`
    //! and `ConfigView::get_abs_value` (packet 150, Step 2, AC-2 / AC-N2).
    //! Module path deliberately contains "config" and test fn names
    //! contain "percent" / "percent_zero_base" so both
    //! `cargo test -p slicer-ir --lib config -- percent` and
    //! `cargo test -p slicer-ir --lib config -- percent_zero_base` select
    //! them.
    use super::{ConfigValue, ConfigView};
    use std::collections::HashMap;

    fn view_with(key: &str, value: ConfigValue) -> ConfigView {
        let mut fields = HashMap::new();
        fields.insert(key.to_string(), value);
        ConfigView::from_map(fields)
    }

    #[test]
    fn get_abs_value_resolves_percent_against_positive_base() {
        let view = view_with("k", ConfigValue::Percent(25.0));
        let resolved = view.get_abs_value("k", 0.4).expect("percent resolves");
        assert!(
            (resolved - 0.1).abs() < 1e-9,
            "expected 0.1, got {resolved}"
        );
    }

    #[test]
    fn get_abs_value_resolves_float_or_percent_literal_regardless_of_base() {
        let view = view_with(
            "k",
            ConfigValue::FloatOrPercent {
                value: 1.2,
                is_percent: false,
            },
        );
        // Literal (non-percent) values are returned unchanged no matter the base.
        assert_eq!(view.get_abs_value("k", 0.4), Some(1.2));
        assert_eq!(view.get_abs_value("k", 0.0), Some(1.2));
        assert_eq!(view.get_abs_value("k", -5.0), Some(1.2));
    }

    #[test]
    fn get_abs_value_resolves_float_or_percent_percent_against_positive_base() {
        let view = view_with(
            "k",
            ConfigValue::FloatOrPercent {
                value: 25.0,
                is_percent: true,
            },
        );
        let resolved = view.get_abs_value("k", 0.4).expect("percent resolves");
        assert!(
            (resolved - 0.1).abs() < 1e-9,
            "expected 0.1, got {resolved}"
        );
    }

    #[test]
    fn get_abs_value_percent_zero_base_returns_none() {
        let view = view_with("k", ConfigValue::Percent(25.0));
        assert_eq!(view.get_abs_value("k", 0.0), None);
    }

    #[test]
    fn get_abs_value_percent_zero_base_negative_base_returns_none() {
        let view = view_with("k", ConfigValue::Percent(25.0));
        assert_eq!(view.get_abs_value("k", -1.0), None);
    }

    #[test]
    fn get_abs_value_float_or_percent_percent_zero_base_returns_none() {
        let view = view_with(
            "k",
            ConfigValue::FloatOrPercent {
                value: 25.0,
                is_percent: true,
            },
        );
        assert_eq!(view.get_abs_value("k", 0.0), None);
    }

    #[test]
    fn get_abs_value_float_resolves_unchanged() {
        let view = view_with("k", ConfigValue::Float(3.5));
        assert_eq!(view.get_abs_value("k", 0.0), Some(3.5));
        assert_eq!(view.get_abs_value("k", 100.0), Some(3.5));
    }

    #[test]
    fn get_abs_value_missing_key_returns_none() {
        let view = ConfigView::new();
        assert_eq!(view.get_abs_value("missing", 1.0), None);
    }

    #[test]
    fn get_float_on_percent_value_returns_none() {
        let view = view_with("k", ConfigValue::Percent(25.0));
        assert_eq!(view.get_float("k"), None);
    }

    #[test]
    fn get_float_on_float_or_percent_percent_returns_none() {
        let view = view_with(
            "k",
            ConfigValue::FloatOrPercent {
                value: 25.0,
                is_percent: true,
            },
        );
        assert_eq!(view.get_float("k"), None);
    }

    #[test]
    fn get_float_on_float_or_percent_literal_returns_value() {
        let view = view_with(
            "k",
            ConfigValue::FloatOrPercent {
                value: 1.2,
                is_percent: false,
            },
        );
        assert_eq!(view.get_float("k"), Some(1.2));
    }
}
