//! Golden tests for `split_top_surfaces` with an independent analytic oracle.
//!
//! # Unit system
//! 1 unit = 100 nm = 10⁻⁴ mm, so 1 mm = 10 000 units.
//! All expected polygon coordinates are derived by hand from the axis-aligned
//! geometry specifications and hard-coded here. They are NOT generated by
//! running `split_top_surfaces` and snapshotting.
//!
//! # Hausdorff tolerance
//! Each fixture is verified with a symmetric polygon Hausdorff distance ≤ 50 units
//! (= 0.005 mm). The directed Hausdorff samples every vertex of the actual polygon
//! and finds its nearest-point-on-edge in the expected polygon using
//! `slicer_core::geometry::closest_point_on_polygons`, which already exists in the
//! codebase. The symmetric distance is `max(directed(actual→expected), directed(expected→actual))`.

#![allow(missing_docs)]

use slicer_core::geometry::closest_point_on_polygons;
use slicer_core::top_surface_split::split_top_surfaces;
use slicer_ir::{ExPolygon, Point2, Polygon};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Hausdorff tolerance in units: 0.005 mm × 10_000 units/mm = 50 units.
const HAUSDORFF_TOL_UNITS: f64 = 50.0;

/// Build an axis-aligned rectangle with the given corner coordinates (units).
fn rect(x0: i64, y0: i64, x1: i64, y1: i64) -> ExPolygon {
    ExPolygon {
        contour: Polygon {
            points: vec![
                Point2 { x: x0, y: y0 },
                Point2 { x: x1, y: y0 },
                Point2 { x: x1, y: y1 },
                Point2 { x: x0, y: y1 },
            ],
        },
        holes: Vec::new(),
    }
}

/// Directed Hausdorff distance from `source` vertices to nearest edge in `target`.
///
/// For every vertex of every contour in `source`, find the closest point on any
/// edge of `target` (via `closest_point_on_polygons`). Return the maximum of the
/// square roots of those minimum squared distances.
fn directed_hausdorff(source: &[ExPolygon], target: &[ExPolygon]) -> f64 {
    let mut max_dist: f64 = 0.0;
    for poly in source {
        for pt in &poly.contour.points {
            let dist_sq = closest_point_on_polygons(*pt, target)
                .map(|cp| cp.distance_sq)
                .unwrap_or(f64::MAX);
            let dist = dist_sq.sqrt();
            if dist > max_dist {
                max_dist = dist;
            }
        }
    }
    max_dist
}

/// Symmetric polygon Hausdorff distance between two polygon sets.
fn symmetric_hausdorff(a: &[ExPolygon], b: &[ExPolygon]) -> f64 {
    let d_ab = directed_hausdorff(a, b);
    let d_ba = directed_hausdorff(b, a);
    d_ab.max(d_ba)
}

/// Assert that two polygon sets are Hausdorff-close (≤ `HAUSDORFF_TOL_UNITS`).
///
/// Panics with a descriptive message if the distance exceeds the tolerance.
fn assert_hausdorff_close(actual: &[ExPolygon], expected: &[ExPolygon], label: &str) {
    assert!(
        !expected.is_empty(),
        "{label}: expected polygon set must not be empty (oracle error)"
    );
    assert!(
        !actual.is_empty(),
        "{label}: actual polygon set is empty but expected geometry"
    );
    let dist = symmetric_hausdorff(actual, expected);
    assert!(
        dist <= HAUSDORFF_TOL_UNITS,
        "{label}: symmetric Hausdorff {dist:.1} units exceeds tolerance {HAUSDORFF_TOL_UNITS} units (0.005 mm)"
    );
}

// ---------------------------------------------------------------------------
// Golden fixture 1: Full-top-coverage rectangle
//
// Region:          10 mm × 10 mm square [0,0]..[100000,100000]
// top_solid_fill:  same square (identical coverage)
//
// Expected:
//   top_portion    = whole rect [0,0]..[100000,100000]
//                    (intersection of rect with itself = rect)
//   non_top_portion = empty
//                    (difference of rect with itself = empty)
//
// Derivation: A ∩ A = A; A \ A = ∅.
// ---------------------------------------------------------------------------

#[test]
fn golden_full_top_coverage() {
    // 10 mm × 10 mm square: 100_000 units per side
    let region = vec![rect(0, 0, 100_000, 100_000)];
    let top_fill = vec![rect(0, 0, 100_000, 100_000)];

    let split = split_top_surfaces(&region, &top_fill);

    // Expected: top_portion ≈ whole rect
    // Hand-derived: intersection(A, A) = A
    let expected_top = vec![rect(0, 0, 100_000, 100_000)];
    assert_hausdorff_close(
        &split.top_portion,
        &expected_top,
        "golden_full_top_coverage / top_portion",
    );

    // Expected: non_top_portion is empty
    assert!(
        split.non_top_portion.is_empty(),
        "golden_full_top_coverage: non_top_portion must be empty when top_fill covers the whole region; got {} polygon(s)",
        split.non_top_portion.len()
    );
}

// ---------------------------------------------------------------------------
// Golden fixture 2: Partial ~50% coverage — right half
//
// Region:          10 mm × 10 mm square [0,0]..[100000,100000]
// top_solid_fill:  right half [50000,0]..[100000,100000]
//
// Expected:
//   top_portion    = right half [50000,0]..[100000,100000]
//                    (A ∩ R where R is right half)
//   non_top_portion = left half  [0,0]..[50000,100000]
//                    (A \ R = left half)
//
// Derivation (axis-aligned):
//   A = [0..100000] × [0..100000]
//   R = [50000..100000] × [0..100000]
//   A ∩ R = [50000..100000] × [0..100000]  ← right half
//   A \ R = [0..50000] × [0..100000]       ← left half
// ---------------------------------------------------------------------------

#[test]
fn golden_partial_right_half() {
    let region = vec![rect(0, 0, 100_000, 100_000)];
    // top_solid_fill = right half (x: 50_000..100_000)
    let top_fill = vec![rect(50_000, 0, 100_000, 100_000)];

    let split = split_top_surfaces(&region, &top_fill);

    // Hand-derived expected polygons (analytic axis-aligned geometry):
    let expected_top = vec![rect(50_000, 0, 100_000, 100_000)];
    let expected_non_top = vec![rect(0, 0, 50_000, 100_000)];

    assert_hausdorff_close(
        &split.top_portion,
        &expected_top,
        "golden_partial_right_half / top_portion",
    );
    assert_hausdorff_close(
        &split.non_top_portion,
        &expected_non_top,
        "golden_partial_right_half / non_top_portion",
    );
}

// ---------------------------------------------------------------------------
// Golden fixture 3: L-shape with top_solid_fill covering only the vertical arm
//
// The L-shape is the union of:
//   Vertical arm:   [0,0]..[20000,80000]   (2 mm wide × 8 mm tall)
//   Horizontal arm: [0,0]..[80000,20000]   (8 mm wide × 2 mm tall)
//
// Together they form an L. Their union is:
//   All of [0,0]..[20000,80000]  (vertical arm)
//   Plus [0,0]..[80000,20000]    (horizontal arm)
//   (They share the corner [0,0]..[20000,20000])
//
// top_solid_fill = vertical arm only: [0,20000]..[20000,80000]
//   (the part of the vertical arm ABOVE the horizontal arm overlap)
//
// For simplicity we model the L as two separate ExPolygon inputs and use the
// vertical arm above the overlap as top_solid_fill.
//
// Derivation:
//   L = vertical_arm ∪ horizontal_arm
//   top_fill = [0,20000]..[20000,80000]  (upper part of vertical arm)
//   top_portion    = L ∩ top_fill = [0,20000]..[20000,80000]
//   non_top_portion = L \ top_fill = horizontal_arm [0,0]..[80000,20000]
//
// All coordinates in units (1 unit = 100 nm; 1 mm = 10_000 units):
//   2 mm = 20_000 units, 8 mm = 80_000 units.
// ---------------------------------------------------------------------------

#[test]
fn golden_l_shape_vertical_arm_top() {
    // L-shape: two overlapping rectangles form the L.
    // vertical arm: x [0..20000], y [0..80000]
    // horizontal arm: x [0..80000], y [0..20000]
    let vertical_arm = rect(0, 0, 20_000, 80_000);
    let horizontal_arm = rect(0, 0, 80_000, 20_000);
    let region = vec![vertical_arm, horizontal_arm];

    // top_solid_fill = upper part of vertical arm only (above overlap with horizontal arm)
    // Derivation: the horizontal arm covers y [0..20000]. Above that (y [20000..80000])
    // in the vertical arm ([0..20000] × [20000..80000]) is purely vertical arm area.
    let top_fill = vec![rect(0, 20_000, 20_000, 80_000)];

    let split = split_top_surfaces(&region, &top_fill);

    // Hand-derived expected polygons:
    // top_portion    = intersection(L, top_fill) = [0,20000]..[20000,80000]  (upper vert arm)
    // non_top_portion = difference(L, top_fill)  = the rest of the L
    //                 Clipper2 will return the horizontal arm plus lower vertical overlap as
    //                 a single merged polygon: [0,0]..[80000,20000] union [0,0]..[20000,20000]
    //                 = [0,0]..[80000,20000] (the horizontal arm absorbs the overlap).
    let expected_top = vec![rect(0, 20_000, 20_000, 80_000)];
    let expected_non_top = vec![rect(0, 0, 80_000, 20_000)];

    assert_hausdorff_close(
        &split.top_portion,
        &expected_top,
        "golden_l_shape / top_portion",
    );
    assert_hausdorff_close(
        &split.non_top_portion,
        &expected_non_top,
        "golden_l_shape / non_top_portion",
    );
}
