// Code generated by wit-bindgen-go. DO NOT EDIT.

package configtypes

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// FloatOrPercentShape is used for storage in variant or result types.
type FloatOrPercentShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(FloatOrPercent{})]byte
}
