// Code generated by wit-bindgen-go. DO NOT EDIT.

package configtypes

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "slicer:config".

//go:wasmimport slicer:config/config-types [resource-drop]config-view
//go:noescape
func wasmimport_ConfigViewResourceDrop(self0 uint32)

//go:wasmimport slicer:config/config-types [method]config-view.get
//go:noescape
func wasmimport_ConfigViewGet(self0 uint32, key0 *uint8, key1 uint32, result *cm.Option[ConfigValue])

//go:wasmimport slicer:config/config-types [method]config-view.get-bool
//go:noescape
func wasmimport_ConfigViewGetBool(self0 uint32, key0 *uint8, key1 uint32, result *cm.Option[bool])

//go:wasmimport slicer:config/config-types [method]config-view.get-float
//go:noescape
func wasmimport_ConfigViewGetFloat(self0 uint32, key0 *uint8, key1 uint32, result *cm.Option[float64])

//go:wasmimport slicer:config/config-types [method]config-view.get-int
//go:noescape
func wasmimport_ConfigViewGetInt(self0 uint32, key0 *uint8, key1 uint32, result *cm.Option[int64])

//go:wasmimport slicer:config/config-types [method]config-view.get-string
//go:noescape
func wasmimport_ConfigViewGetString(self0 uint32, key0 *uint8, key1 uint32, result *cm.Option[string])

//go:wasmimport slicer:config/config-types [method]config-view.keys
//go:noescape
func wasmimport_ConfigViewKeys(self0 uint32, result *cm.List[string])
