// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package configtypes represents the imported interface "slicer:config/config-types".
package configtypes

import (
	"go.bytecodealliance.org/cm"
)

// FloatOrPercent represents the record "slicer:config/config-types#float-or-percent".
//
//	record float-or-percent {
//		value: f64,
//		is-percent: bool,
//	}
type FloatOrPercent struct {
	_         cm.HostLayout `json:"-"`
	Value     float64       `json:"value"`
	IsPercent bool          `json:"is-percent"`
}

// ConfigValue represents the variant "slicer:config/config-types#config-value".
//
//	variant config-value {
//		bool-val(bool),
//		int-val(s64),
//		float-val(f64),
//		string-val(string),
//		float-list(list<f64>),
//		string-list(list<string>),
//		percent-val(f64),
//		float-or-percent-val(float-or-percent),
//	}
type ConfigValue cm.Variant[uint8, FloatOrPercentShape, FloatOrPercent]

// ConfigValueBoolVal returns a [ConfigValue] of case "bool-val".
func ConfigValueBoolVal(data bool) ConfigValue {
	return cm.New[ConfigValue](0, data)
}

// BoolVal returns a non-nil *[bool] if [ConfigValue] represents the variant case "bool-val".
func (self *ConfigValue) BoolVal() *bool {
	return cm.Case[bool](self, 0)
}

// ConfigValueIntVal returns a [ConfigValue] of case "int-val".
func ConfigValueIntVal(data int64) ConfigValue {
	return cm.New[ConfigValue](1, data)
}

// IntVal returns a non-nil *[int64] if [ConfigValue] represents the variant case "int-val".
func (self *ConfigValue) IntVal() *int64 {
	return cm.Case[int64](self, 1)
}

// ConfigValueFloatVal returns a [ConfigValue] of case "float-val".
func ConfigValueFloatVal(data float64) ConfigValue {
	return cm.New[ConfigValue](2, data)
}

// FloatVal returns a non-nil *[float64] if [ConfigValue] represents the variant case "float-val".
func (self *ConfigValue) FloatVal() *float64 {
	return cm.Case[float64](self, 2)
}

// ConfigValueStringVal returns a [ConfigValue] of case "string-val".
func ConfigValueStringVal(data string) ConfigValue {
	return cm.New[ConfigValue](3, data)
}

// StringVal returns a non-nil *[string] if [ConfigValue] represents the variant case "string-val".
func (self *ConfigValue) StringVal() *string {
	return cm.Case[string](self, 3)
}

// ConfigValueFloatList returns a [ConfigValue] of case "float-list".
func ConfigValueFloatList(data cm.List[float64]) ConfigValue {
	return cm.New[ConfigValue](4, data)
}

// FloatList returns a non-nil *[cm.List[float64]] if [ConfigValue] represents the variant case "float-list".
func (self *ConfigValue) FloatList() *cm.List[float64] {
	return cm.Case[cm.List[float64]](self, 4)
}

// ConfigValueStringList returns a [ConfigValue] of case "string-list".
func ConfigValueStringList(data cm.List[string]) ConfigValue {
	return cm.New[ConfigValue](5, data)
}

// StringList returns a non-nil *[cm.List[string]] if [ConfigValue] represents the variant case "string-list".
func (self *ConfigValue) StringList() *cm.List[string] {
	return cm.Case[cm.List[string]](self, 5)
}

// ConfigValuePercentVal returns a [ConfigValue] of case "percent-val".
func ConfigValuePercentVal(data float64) ConfigValue {
	return cm.New[ConfigValue](6, data)
}

// PercentVal returns a non-nil *[float64] if [ConfigValue] represents the variant case "percent-val".
func (self *ConfigValue) PercentVal() *float64 {
	return cm.Case[float64](self, 6)
}

// ConfigValueFloatOrPercentVal returns a [ConfigValue] of case "float-or-percent-val".
func ConfigValueFloatOrPercentVal(data FloatOrPercent) ConfigValue {
	return cm.New[ConfigValue](7, data)
}

// FloatOrPercentVal returns a non-nil *[FloatOrPercent] if [ConfigValue] represents the variant case "float-or-percent-val".
func (self *ConfigValue) FloatOrPercentVal() *FloatOrPercent {
	return cm.Case[FloatOrPercent](self, 7)
}

var _ConfigValueStrings = [8]string{
	"bool-val",
	"int-val",
	"float-val",
	"string-val",
	"float-list",
	"string-list",
	"percent-val",
	"float-or-percent-val",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v ConfigValue) String() string {
	return _ConfigValueStrings[v.Tag()]
}

// ConfigView represents the imported resource "slicer:config/config-types#config-view".
//
//	resource config-view
type ConfigView cm.Resource

// ResourceDrop represents the imported resource-drop for resource "config-view".
//
// Drops a resource handle.
//
//go:nosplit
func (self ConfigView) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ConfigViewResourceDrop((uint32)(self0))
	return
}

// Get represents the imported method "get".
//
//	get: func(key: string) -> option<config-value>
//
//go:nosplit
func (self ConfigView) Get(key string) (result cm.Option[ConfigValue]) {
	self0 := cm.Reinterpret[uint32](self)
	key0, key1 := cm.LowerString(key)
	wasmimport_ConfigViewGet((uint32)(self0), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// GetBool represents the imported method "get-bool".
//
//	get-bool: func(key: string) -> option<bool>
//
//go:nosplit
func (self ConfigView) GetBool(key string) (result cm.Option[bool]) {
	self0 := cm.Reinterpret[uint32](self)
	key0, key1 := cm.LowerString(key)
	wasmimport_ConfigViewGetBool((uint32)(self0), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// GetFloat represents the imported method "get-float".
//
//	get-float: func(key: string) -> option<f64>
//
//go:nosplit
func (self ConfigView) GetFloat(key string) (result cm.Option[float64]) {
	self0 := cm.Reinterpret[uint32](self)
	key0, key1 := cm.LowerString(key)
	wasmimport_ConfigViewGetFloat((uint32)(self0), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// GetInt represents the imported method "get-int".
//
//	get-int: func(key: string) -> option<s64>
//
//go:nosplit
func (self ConfigView) GetInt(key string) (result cm.Option[int64]) {
	self0 := cm.Reinterpret[uint32](self)
	key0, key1 := cm.LowerString(key)
	wasmimport_ConfigViewGetInt((uint32)(self0), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// GetString represents the imported method "get-string".
//
//	get-string: func(key: string) -> option<string>
//
//go:nosplit
func (self ConfigView) GetString(key string) (result cm.Option[string]) {
	self0 := cm.Reinterpret[uint32](self)
	key0, key1 := cm.LowerString(key)
	wasmimport_ConfigViewGetString((uint32)(self0), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// Keys represents the imported method "keys".
//
//	keys: func() -> list<string>
//
//go:nosplit
func (self ConfigView) Keys() (result cm.List[string]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ConfigViewKeys((uint32)(self0), &result)
	return
}
