// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package moduleerrors represents the imported interface "slicer:common/module-errors".
package moduleerrors

import (
	"go.bytecodealliance.org/cm"
)

// ModuleError represents the record "slicer:common/module-errors#module-error".
//
//	record module-error {
//		code: u32,
//		message: string,
//		fatal: bool,
//	}
type ModuleError struct {
	_       cm.HostLayout `json:"-"`
	Code    uint32        `json:"code"`
	Message string        `json:"message"`
	Fatal   bool          `json:"fatal"`
}
