[package]
name = "slicer-integrated-modules"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
slicer-scheduler = { path = "../slicer-scheduler" }
slicer-sdk = { path = "../slicer-sdk" }
classic-perimeters = { path = "../../modules/core-modules/classic-perimeters", optional = true }

[features]
default = []
classic-perimeters = ["dep:classic-perimeters"]
