// Code generated by wit-bindgen-go. DO NOT EDIT.

package irhandles

import (
	"foreign-language-text-postprocess/slicer/types/geometry"
	"go.bytecodealliance.org/cm"
)

func lower_ExtrusionRole(v geometry.ExtrusionRole) (f0 uint32, f1 *uint8, f2 uint32) {
	f0 = (uint32)(v.Tag())
	switch f0 {
	case 13: // custom
		v1, v2 := cm.LowerString(*cm.Case[string](&v, 13))
		f1 = (*uint8)(v1)
		f2 = (uint32)(v2)
	}
	return
}

func lower_ExtrusionPath3d(v geometry.ExtrusionPath3d) (f0 *geometry.Point3WithWidth, f1 uint32, f2 uint32, f3 *uint8, f4 uint32, f5 float32) {
	f0, f1 = cm.LowerList(v.Points)
	f2, f3, f4 = lower_ExtrusionRole(v.Role)
	f5 = (float32)(v.SpeedFactor)
	return
}

func lower_Point3(v geometry.Point3) (f0 float32, f1 float32, f2 float32) {
	f0 = (float32)(v.X)
	f1 = (float32)(v.Y)
	f2 = (float32)(v.Z)
	return
}

func lower_WallBoundaryType(v WallBoundaryType) (f0 uint32, f1 *MaterialBoundarySegment, f2 uint32) {
	f0 = (uint32)(v.Tag())
	switch f0 {
	case 1: // material-boundary
		v1, v2 := cm.LowerList(*cm.Case[cm.List[MaterialBoundarySegment]](&v, 1))
		f1 = (*MaterialBoundarySegment)(v1)
		f2 = (uint32)(v2)
	}
	return
}

func lower_WallLoopView(v WallLoopView) (f0 uint32, f1 uint32, f2 *geometry.Point3WithWidth, f3 uint32, f4 uint32, f5 *uint8, f6 uint32, f7 float32, f8 *WallFeatureFlag, f9 uint32, f10 uint32, f11 *MaterialBoundarySegment, f12 uint32) {
	f0 = (uint32)(v.PerimeterIndex)
	f1 = (uint32)(v.LoopType)
	f2, f3, f4, f5, f6, f7 = lower_ExtrusionPath3d(v.Path)
	f8, f9 = cm.LowerList(v.FeatureFlags)
	f10, f11, f12 = lower_WallBoundaryType(v.BoundaryType)
	return
}

func lower_RegionKey(v RegionKey) (f0 uint32, f1 *uint8, f2 uint32, f3 *uint8, f4 uint32, f5 *cm.Tuple[string, PaintValue], f6 uint32) {
	f0 = (uint32)(v.LayerIndex)
	f1, f2 = cm.LowerString(v.ObjectID)
	f3, f4 = cm.LowerString(v.RegionID)
	f5, f6 = cm.LowerList(v.VariantChain)
	return
}

func lower_OptionF32(v cm.Option[float32]) (f0 uint32, f1 float32) {
	some := v.Some()
	if some != nil {
		f0 = 1
		v1 := (float32)(*some)
		f1 = (float32)(v1)
	}
	return
}

func lower_GcodeMoveCmd(v GcodeMoveCmd) (f0 uint32, f1 float32, f2 uint32, f3 float32, f4 uint32, f5 float32, f6 uint32, f7 float32, f8 uint32, f9 float32, f10 uint32, f11 *uint8, f12 uint32) {
	f0, f1 = lower_OptionF32(v.X)
	f2, f3 = lower_OptionF32(v.Y)
	f4, f5 = lower_OptionF32(v.Z)
	f6, f7 = lower_OptionF32(v.E)
	f8, f9 = lower_OptionF32(v.F)
	f10, f11, f12 = lower_ExtrusionRole(v.Role)
	return
}

func lower_PaintSemantic(v PaintSemantic) (f0 uint32, f1 *uint8, f2 uint32) {
	f0 = (uint32)(v.Tag())
	switch f0 {
	case 4: // custom
		v1, v2 := cm.LowerString(*cm.Case[string](&v, 4))
		f1 = (*uint8)(v1)
		f2 = (uint32)(v2)
	}
	return
}
