// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package irhandles represents the imported interface "slicer:ir-handles/ir-handles".
package irhandles

import (
	configtypes "foreign-language-text-postprocess/slicer/config/config-types"
	"foreign-language-text-postprocess/slicer/types/geometry"
	"go.bytecodealliance.org/cm"
)

// ExPolygon represents the type alias "slicer:ir-handles/ir-handles#ex-polygon".
//
// See [geometry.ExPolygon] for more information.
type ExPolygon = geometry.ExPolygon

// ExtrusionPath3d represents the type alias "slicer:ir-handles/ir-handles#extrusion-path3d".
//
// See [geometry.ExtrusionPath3d] for more information.
type ExtrusionPath3d = geometry.ExtrusionPath3d

// Point3 represents the type alias "slicer:ir-handles/ir-handles#point3".
//
// See [geometry.Point3] for more information.
type Point3 = geometry.Point3

// Point3WithWidth represents the type alias "slicer:ir-handles/ir-handles#point3-with-width".
//
// See [geometry.Point3WithWidth] for more information.
type Point3WithWidth = geometry.Point3WithWidth

// ExtrusionRole represents the type alias "slicer:ir-handles/ir-handles#extrusion-role".
//
// See [geometry.ExtrusionRole] for more information.
type ExtrusionRole = geometry.ExtrusionRole

// Point2WithWidth represents the type alias "slicer:ir-handles/ir-handles#point2-with-width".
//
// See [geometry.Point2WithWidth] for more information.
type Point2WithWidth = geometry.Point2WithWidth

// ThickPolyline represents the type alias "slicer:ir-handles/ir-handles#thick-polyline".
//
// See [geometry.ThickPolyline] for more information.
type ThickPolyline = geometry.ThickPolyline

// ConfigView represents the imported type alias "slicer:ir-handles/ir-handles#config-view".
//
// See [configtypes.ConfigView] for more information.
type ConfigView = configtypes.ConfigView

// ObjectID represents the string "slicer:ir-handles/ir-handles#object-id".
//
//	type object-id = string
type ObjectID string

// RegionID represents the string "slicer:ir-handles/ir-handles#region-id".
//
//	type region-id = string
type RegionID string

// LayerIdx represents the s32 "slicer:ir-handles/ir-handles#layer-idx".
//
// Signed because raft entries committed by `PrePass::SupportGeometry`
// carry negative `global_layer_index`. Layer-module exports always
// pass non-negative values; host conversion sites use `as u32` /
// `as i32` at the boundary to round-trip into u32-keyed IR types.
//
//	type layer-idx = s32
type LayerIdx int32

// MaterialBoundarySegment represents the record "slicer:ir-handles/ir-handles#material-boundary-segment".
//
//	record material-boundary-segment {
//		point-range-start: u32,
//		point-range-end: u32,
//		near-tool: option<u32>,
//		far-tool: option<u32>,
//	}
type MaterialBoundarySegment struct {
	_               cm.HostLayout     `json:"-"`
	PointRangeStart uint32            `json:"point-range-start"`
	PointRangeEnd   uint32            `json:"point-range-end"`
	NearTool        cm.Option[uint32] `json:"near-tool"`
	FarTool         cm.Option[uint32] `json:"far-tool"`
}

// WallBoundaryType represents the variant "slicer:ir-handles/ir-handles#wall-boundary-type".
//
//	variant wall-boundary-type {
//		exterior-surface,
//		material-boundary(list<material-boundary-segment>),
//		interior,
//	}
type WallBoundaryType cm.Variant[uint8, cm.List[MaterialBoundarySegment], cm.List[MaterialBoundarySegment]]

// WallBoundaryTypeExteriorSurface returns a [WallBoundaryType] of case "exterior-surface".
func WallBoundaryTypeExteriorSurface() WallBoundaryType {
	var data struct{}
	return cm.New[WallBoundaryType](0, data)
}

// ExteriorSurface returns true if [WallBoundaryType] represents the variant case "exterior-surface".
func (self *WallBoundaryType) ExteriorSurface() bool {
	return self.Tag() == 0
}

// WallBoundaryTypeMaterialBoundary returns a [WallBoundaryType] of case "material-boundary".
func WallBoundaryTypeMaterialBoundary(data cm.List[MaterialBoundarySegment]) WallBoundaryType {
	return cm.New[WallBoundaryType](1, data)
}

// MaterialBoundary returns a non-nil *[cm.List[MaterialBoundarySegment]] if [WallBoundaryType] represents the variant case "material-boundary".
func (self *WallBoundaryType) MaterialBoundary() *cm.List[MaterialBoundarySegment] {
	return cm.Case[cm.List[MaterialBoundarySegment]](self, 1)
}

// WallBoundaryTypeInterior returns a [WallBoundaryType] of case "interior".
func WallBoundaryTypeInterior() WallBoundaryType {
	var data struct{}
	return cm.New[WallBoundaryType](2, data)
}

// Interior returns true if [WallBoundaryType] represents the variant case "interior".
func (self *WallBoundaryType) Interior() bool {
	return self.Tag() == 2
}

var _WallBoundaryTypeStrings = [3]string{
	"exterior-surface",
	"material-boundary",
	"interior",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v WallBoundaryType) String() string {
	return _WallBoundaryTypeStrings[v.Tag()]
}

// WallLoopType represents the enum "slicer:ir-handles/ir-handles#wall-loop-type".
//
//	enum wall-loop-type {
//		outer,
//		inner,
//		thin-wall,
//		nonplanar-shell,
//		gap-fill
//	}
type WallLoopType uint8

const (
	WallLoopTypeOuter WallLoopType = iota
	WallLoopTypeInner
	WallLoopTypeThinWall
	WallLoopTypeNonplanarShell
	WallLoopTypeGapFill
)

var _WallLoopTypeStrings = [5]string{
	"outer",
	"inner",
	"thin-wall",
	"nonplanar-shell",
	"gap-fill",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e WallLoopType) String() string {
	return _WallLoopTypeStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e WallLoopType) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *WallLoopType) UnmarshalText(text []byte) error {
	return _WallLoopTypeUnmarshalCase(e, text)
}

var _WallLoopTypeUnmarshalCase = cm.CaseUnmarshaler[WallLoopType](_WallLoopTypeStrings[:])

// PaintSemantic represents the variant "slicer:ir-handles/ir-handles#paint-semantic".
//
//	variant paint-semantic {
//		material,
//		fuzzy-skin,
//		support-enforcer,
//		support-blocker,
//		custom(string),
//	}
type PaintSemantic cm.Variant[uint8, string, string]

// PaintSemanticMaterial returns a [PaintSemantic] of case "material".
func PaintSemanticMaterial() PaintSemantic {
	var data struct{}
	return cm.New[PaintSemantic](0, data)
}

// Material returns true if [PaintSemantic] represents the variant case "material".
func (self *PaintSemantic) Material() bool {
	return self.Tag() == 0
}

// PaintSemanticFuzzySkin returns a [PaintSemantic] of case "fuzzy-skin".
func PaintSemanticFuzzySkin() PaintSemantic {
	var data struct{}
	return cm.New[PaintSemantic](1, data)
}

// FuzzySkin returns true if [PaintSemantic] represents the variant case "fuzzy-skin".
func (self *PaintSemantic) FuzzySkin() bool {
	return self.Tag() == 1
}

// PaintSemanticSupportEnforcer returns a [PaintSemantic] of case "support-enforcer".
func PaintSemanticSupportEnforcer() PaintSemantic {
	var data struct{}
	return cm.New[PaintSemantic](2, data)
}

// SupportEnforcer returns true if [PaintSemantic] represents the variant case "support-enforcer".
func (self *PaintSemantic) SupportEnforcer() bool {
	return self.Tag() == 2
}

// PaintSemanticSupportBlocker returns a [PaintSemantic] of case "support-blocker".
func PaintSemanticSupportBlocker() PaintSemantic {
	var data struct{}
	return cm.New[PaintSemantic](3, data)
}

// SupportBlocker returns true if [PaintSemantic] represents the variant case "support-blocker".
func (self *PaintSemantic) SupportBlocker() bool {
	return self.Tag() == 3
}

// PaintSemanticCustom returns a [PaintSemantic] of case "custom".
func PaintSemanticCustom(data string) PaintSemantic {
	return cm.New[PaintSemantic](4, data)
}

// Custom returns a non-nil *[string] if [PaintSemantic] represents the variant case "custom".
func (self *PaintSemantic) Custom() *string {
	return cm.Case[string](self, 4)
}

var _PaintSemanticStrings = [5]string{
	"material",
	"fuzzy-skin",
	"support-enforcer",
	"support-blocker",
	"custom",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v PaintSemantic) String() string {
	return _PaintSemanticStrings[v.Tag()]
}

// PaintValue represents the variant "slicer:ir-handles/ir-handles#paint-value".
//
//	variant paint-value {
//		flag(bool),
//		scalar(f32),
//		tool-index(u32),
//	}
type PaintValue cm.Variant[uint8, float32, float32]

// PaintValueFlag returns a [PaintValue] of case "flag".
func PaintValueFlag(data bool) PaintValue {
	return cm.New[PaintValue](0, data)
}

// Flag returns a non-nil *[bool] if [PaintValue] represents the variant case "flag".
func (self *PaintValue) Flag() *bool {
	return cm.Case[bool](self, 0)
}

// PaintValueScalar returns a [PaintValue] of case "scalar".
func PaintValueScalar(data float32) PaintValue {
	return cm.New[PaintValue](1, data)
}

// Scalar returns a non-nil *[float32] if [PaintValue] represents the variant case "scalar".
func (self *PaintValue) Scalar() *float32 {
	return cm.Case[float32](self, 1)
}

// PaintValueToolIndex returns a [PaintValue] of case "tool-index".
func PaintValueToolIndex(data uint32) PaintValue {
	return cm.New[PaintValue](2, data)
}

// ToolIndex returns a non-nil *[uint32] if [PaintValue] represents the variant case "tool-index".
func (self *PaintValue) ToolIndex() *uint32 {
	return cm.Case[uint32](self, 2)
}

var _PaintValueStrings = [3]string{
	"flag",
	"scalar",
	"tool-index",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v PaintValue) String() string {
	return _PaintValueStrings[v.Tag()]
}

// RegionKey represents the record "slicer:ir-handles/ir-handles#region-key".
//
//	record region-key {
//		layer-index: layer-idx,
//		object-id: object-id,
//		region-id: region-id,
//		variant-chain: list<tuple<string, paint-value>>,
//	}
type RegionKey struct {
	_            cm.HostLayout                         `json:"-"`
	LayerIndex   LayerIdx                              `json:"layer-index"`
	ObjectID     ObjectID                              `json:"object-id"`
	RegionID     RegionID                              `json:"region-id"`
	VariantChain cm.List[cm.Tuple[string, PaintValue]] `json:"variant-chain"`
}

// WallFeatureFlag represents the record "slicer:ir-handles/ir-handles#wall-feature-flag".
//
//	record wall-feature-flag {
//		tool-index: option<u32>,
//		fuzzy-skin: bool,
//		is-bridge: bool,
//		is-thin-wall: bool,
//		skip-ironing: bool,
//		custom: list<tuple<string, paint-value>>,
//	}
type WallFeatureFlag struct {
	_           cm.HostLayout                         `json:"-"`
	ToolIndex   cm.Option[uint32]                     `json:"tool-index"`
	FuzzySkin   bool                                  `json:"fuzzy-skin"`
	IsBridge    bool                                  `json:"is-bridge"`
	IsThinWall  bool                                  `json:"is-thin-wall"`
	SkipIroning bool                                  `json:"skip-ironing"`
	Custom      cm.List[cm.Tuple[string, PaintValue]] `json:"custom"`
}

// WallLoopView represents the record "slicer:ir-handles/ir-handles#wall-loop-view".
//
//	record wall-loop-view {
//		perimeter-index: u32,
//		loop-type: wall-loop-type,
//		path: extrusion-path3d,
//		feature-flags: list<wall-feature-flag>,
//		boundary-type: wall-boundary-type,
//	}
type WallLoopView struct {
	_              cm.HostLayout            `json:"-"`
	PerimeterIndex uint32                   `json:"perimeter-index"`
	LoopType       WallLoopType             `json:"loop-type"`
	Path           ExtrusionPath3d          `json:"path"`
	FeatureFlags   cm.List[WallFeatureFlag] `json:"feature-flags"`
	BoundaryType   WallBoundaryType         `json:"boundary-type"`
}

// SegmentAnnotationsPolygon represents the record "slicer:ir-handles/ir-handles#segment-annotations-polygon".
//
//	record segment-annotations-polygon {
//		values: list<option<paint-value>>,
//	}
type SegmentAnnotationsPolygon struct {
	_      cm.HostLayout                  `json:"-"`
	Values cm.List[cm.Option[PaintValue]] `json:"values"`
}

// SegmentAnnotationsEntry represents the record "slicer:ir-handles/ir-handles#segment-annotations-entry".
//
//	record segment-annotations-entry {
//		semantic: paint-semantic,
//		polygons: list<segment-annotations-polygon>,
//	}
type SegmentAnnotationsEntry struct {
	_        cm.HostLayout                      `json:"-"`
	Semantic PaintSemantic                      `json:"semantic"`
	Polygons cm.List[SegmentAnnotationsPolygon] `json:"polygons"`
}

// QuartileBand represents the record "slicer:ir-handles/ir-handles#quartile-band".
//
// A quartile-banded subset of overhang polygons for a single layer,
// mirrors `slicer_ir::QuartileBand` (quartile 1 = least severe, 4 = most
// severe). Pre-filtered host-side to the owning `slice-region-view`'s
// region area before crossing the WIT boundary (packet 107).
//
//	record quartile-band {
//		quartile: u8,
//		polygons: list<ex-polygon>,
//	}
type QuartileBand struct {
	_        cm.HostLayout      `json:"-"`
	Quartile uint8              `json:"quartile"`
	Polygons cm.List[ExPolygon] `json:"polygons"`
}

// SurfaceGroupID represents the u64 "slicer:ir-handles/ir-handles#surface-group-id".
//
// Unique identifier for a surface group (matches `SurfaceGroupId` in the IR).
//
//	type surface-group-id = u64
type SurfaceGroupID uint64

// SurfaceGroup represents the record "slicer:ir-handles/ir-handles#surface-group".
//
// Read-side surface group record (populated from `SurfaceClassificationIR`).
// Distinct from `surface-group-proposal` in
// `prepass-mesh-analysis/prepass-mesh-analysis.wit`, which is the
// smaller PrePass write type.
//
//	record surface-group {
//		id: surface-group-id,
//		facet-indices: list<u32>,
//		z-min: f32,
//		z-max: f32,
//		area-mm2: f32,
//		printable: bool,
//		shell-count: u32,
//	}
type SurfaceGroup struct {
	_            cm.HostLayout   `json:"-"`
	ID           SurfaceGroupID  `json:"id"`
	FacetIndices cm.List[uint32] `json:"facet-indices"`
	ZMin         float32         `json:"z-min"`
	ZMax         float32         `json:"z-max"`
	AreaMm2      float32         `json:"area-mm2"`
	Printable    bool            `json:"printable"`
	ShellCount   uint32          `json:"shell-count"`
}

// SliceRegionView represents the imported resource "slicer:ir-handles/ir-handles#slice-region-view".
//
//	resource slice-region-view
type SliceRegionView cm.Resource

// ResourceDrop represents the imported resource-drop for resource "slice-region-view".
//
// Drops a resource handle.
//
//go:nosplit
func (self SliceRegionView) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SliceRegionViewResourceDrop((uint32)(self0))
	return
}

// BottomShellIndex represents the imported method "bottom-shell-index".
//
//	bottom-shell-index: func() -> option<u8>
//
//go:nosplit
func (self SliceRegionView) BottomShellIndex() (result cm.Option[uint8]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SliceRegionViewBottomShellIndex((uint32)(self0), &result)
	return
}

// BottomSolidFill represents the imported method "bottom-solid-fill".
//
//	bottom-solid-fill: func() -> list<ex-polygon>
//
//go:nosplit
func (self SliceRegionView) BottomSolidFill() (result cm.List[ExPolygon]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SliceRegionViewBottomSolidFill((uint32)(self0), &result)
	return
}

// BridgeAreas represents the imported method "bridge-areas".
//
//	bridge-areas: func() -> list<ex-polygon>
//
//go:nosplit
func (self SliceRegionView) BridgeAreas() (result cm.List[ExPolygon]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SliceRegionViewBridgeAreas((uint32)(self0), &result)
	return
}

// BridgeOrientationDeg represents the imported method "bridge-orientation-deg".
//
//	bridge-orientation-deg: func() -> f32
//
//go:nosplit
func (self SliceRegionView) BridgeOrientationDeg() (result float32) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_SliceRegionViewBridgeOrientationDeg((uint32)(self0))
	result = (float32)((float32)(result0))
	return
}

// Config represents the imported method "config".
//
// Per-region config view for this slice region. Host-populated at
// dispatch time (packet 131, Step 3) so region-scoped modules can read
// per-region overrides without routing through the module-level config.
//
//	config: func() -> config-view
//
//go:nosplit
func (self SliceRegionView) Config() (result ConfigView) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_SliceRegionViewConfig((uint32)(self0))
	result = cm.Reinterpret[ConfigView]((uint32)(result0))
	return
}

// EffectiveLayerHeight represents the imported method "effective-layer-height".
//
//	effective-layer-height: func() -> f32
//
//go:nosplit
func (self SliceRegionView) EffectiveLayerHeight() (result float32) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_SliceRegionViewEffectiveLayerHeight((uint32)(self0))
	result = (float32)((float32)(result0))
	return
}

// HasNonplanar represents the imported method "has-nonplanar".
//
//	has-nonplanar: func() -> bool
//
//go:nosplit
func (self SliceRegionView) HasNonplanar() (result bool) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_SliceRegionViewHasNonplanar((uint32)(self0))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// HeldClaims represents the imported method "held-claims".
//
//	held-claims: func() -> list<string>
//
//go:nosplit
func (self SliceRegionView) HeldClaims() (result cm.List[string]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SliceRegionViewHeldClaims((uint32)(self0), &result)
	return
}

// InfillAreas represents the imported method "infill-areas".
//
//	infill-areas: func() -> list<ex-polygon>
//
//go:nosplit
func (self SliceRegionView) InfillAreas() (result cm.List[ExPolygon]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SliceRegionViewInfillAreas((uint32)(self0), &result)
	return
}

// IsBridge represents the imported method "is-bridge".
//
//	is-bridge: func() -> bool
//
//go:nosplit
func (self SliceRegionView) IsBridge() (result bool) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_SliceRegionViewIsBridge((uint32)(self0))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// NeedsSupport represents the imported method "needs-support".
//
//	needs-support: func() -> bool
//
//go:nosplit
func (self SliceRegionView) NeedsSupport() (result bool) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_SliceRegionViewNeedsSupport((uint32)(self0))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// ObjectID represents the imported method "object-id".
//
//	object-id: func() -> object-id
//
//go:nosplit
func (self SliceRegionView) ObjectID() (result ObjectID) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SliceRegionViewObjectID((uint32)(self0), &result)
	return
}

// OverhangAreas represents the imported method "overhang-areas".
//
//	overhang-areas: func() -> list<ex-polygon>
//
//go:nosplit
func (self SliceRegionView) OverhangAreas() (result cm.List[ExPolygon]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SliceRegionViewOverhangAreas((uint32)(self0), &result)
	return
}

// OverhangQuartilePolygons represents the imported method "overhang-quartile-polygons".
//
//	overhang-quartile-polygons: func() -> list<quartile-band>
//
//go:nosplit
func (self SliceRegionView) OverhangQuartilePolygons() (result cm.List[QuartileBand]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SliceRegionViewOverhangQuartilePolygons((uint32)(self0), &result)
	return
}

// Polygons represents the imported method "polygons".
//
//	polygons: func() -> list<ex-polygon>
//
//go:nosplit
func (self SliceRegionView) Polygons() (result cm.List[ExPolygon]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SliceRegionViewPolygons((uint32)(self0), &result)
	return
}

// PrevLayerBoundary represents the imported method "prev-layer-boundary".
//
//	prev-layer-boundary: func() -> list<ex-polygon>
//
//go:nosplit
func (self SliceRegionView) PrevLayerBoundary() (result cm.List[ExPolygon]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SliceRegionViewPrevLayerBoundary((uint32)(self0), &result)
	return
}

// RegionID represents the imported method "region-id".
//
//	region-id: func() -> region-id
//
//go:nosplit
func (self SliceRegionView) RegionID() (result RegionID) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SliceRegionViewRegionID((uint32)(self0), &result)
	return
}

// SegmentAnnotations represents the imported method "segment-annotations".
//
//	segment-annotations: func() -> list<segment-annotations-entry>
//
//go:nosplit
func (self SliceRegionView) SegmentAnnotations() (result cm.List[SegmentAnnotationsEntry]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SliceRegionViewSegmentAnnotations((uint32)(self0), &result)
	return
}

// SparseInfillArea represents the imported method "sparse-infill-area".
//
//	sparse-infill-area: func() -> list<ex-polygon>
//
//go:nosplit
func (self SliceRegionView) SparseInfillArea() (result cm.List[ExPolygon]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SliceRegionViewSparseInfillArea((uint32)(self0), &result)
	return
}

// SurfaceGroup represents the imported method "surface-group".
//
//	surface-group: func() -> option<surface-group>
//
//go:nosplit
func (self SliceRegionView) SurfaceGroup() (result cm.Option[SurfaceGroup]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SliceRegionViewSurfaceGroup((uint32)(self0), &result)
	return
}

// TopShellIndex represents the imported method "top-shell-index".
//
//	top-shell-index: func() -> option<u8>
//
//go:nosplit
func (self SliceRegionView) TopShellIndex() (result cm.Option[uint8]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SliceRegionViewTopShellIndex((uint32)(self0), &result)
	return
}

// TopSolidFill represents the imported method "top-solid-fill".
//
//	top-solid-fill: func() -> list<ex-polygon>
//
//go:nosplit
func (self SliceRegionView) TopSolidFill() (result cm.List[ExPolygon]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SliceRegionViewTopSolidFill((uint32)(self0), &result)
	return
}

// VariantChain represents the imported method "variant-chain".
//
// Ordered (paint-semantic-name, value) pairs identifying this region's
// paint variant. Carries the painted FuzzySkin signal
// (`("fuzzy_skin", flag(true))`) so the perimeter guest can enable
// per-vertex jitter without routing through segment-annotations (D14).
//
//	variant-chain: func() -> list<tuple<string, paint-value>>
//
//go:nosplit
func (self SliceRegionView) VariantChain() (result cm.List[cm.Tuple[string, PaintValue]]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SliceRegionViewVariantChain((uint32)(self0), &result)
	return
}

// Z represents the imported method "z".
//
//	z: func() -> f32
//
//go:nosplit
func (self SliceRegionView) Z() (result float32) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_SliceRegionViewZ((uint32)(self0))
	result = (float32)((float32)(result0))
	return
}

// SeamPosition represents the record "slicer:ir-handles/ir-handles#seam-position".
//
//	record seam-position {
//		point: point3-with-width,
//		wall-index: u32,
//	}
type SeamPosition struct {
	_         cm.HostLayout   `json:"-"`
	Point     Point3WithWidth `json:"point"`
	WallIndex uint32          `json:"wall-index"`
}

// ExtrusionJunction represents the record "slicer:ir-handles/ir-handles#extrusion-junction".
//
// A single junction (vertex) of an `extrusion-line`, mirroring
// `slicer_ir::ExtrusionJunction` (Arachne beading-strategy stack,
// packet 112, T-224). Additive record only — not yet wired into any
// resource or world; no consumer this packet.
//
//	record extrusion-junction {
//		p: point3-with-width,
//		perimeter-index: u32,
//	}
type ExtrusionJunction struct {
	_              cm.HostLayout   `json:"-"`
	P              Point3WithWidth `json:"p"`
	PerimeterIndex uint32          `json:"perimeter-index"`
}

// ExtrusionLine represents the record "slicer:ir-handles/ir-handles#extrusion-line".
//
// A variable-width extrusion line produced by the Arachne
// beading-strategy stack, mirroring `slicer_ir::ExtrusionLine`
// (packet 112, T-224). Additive record only — not yet wired into any
// resource or world; no consumer this packet.
//
//	record extrusion-line {
//		junctions: list<extrusion-junction>,
//		inset-idx: u32,
//		is-odd: bool,
//		is-closed: bool,
//	}
type ExtrusionLine struct {
	_         cm.HostLayout              `json:"-"`
	Junctions cm.List[ExtrusionJunction] `json:"junctions"`
	InsetIdx  uint32                     `json:"inset-idx"`
	IsOdd     bool                       `json:"is-odd"`
	IsClosed  bool                       `json:"is-closed"`
}

// SeamCandidate represents the record "slicer:ir-handles/ir-handles#seam-candidate".
//
// Read-side seam candidate record, mirroring the `(pos, score)` shape
// written by `perimeter-output-builder.push-seam-candidate` below. Lets
// `Layer::PerimetersPostProcess` consumers (e.g. com.core.seam-placer)
// read back the candidates a `Layer::Perimeters` guest pushed for this
// region, closing the write-only gap `push-seam-candidate` originally
// left on `perimeter-region-view`.
//
//	record seam-candidate {
//		position: point3,
//		score: f32,
//	}
type SeamCandidate struct {
	_        cm.HostLayout `json:"-"`
	Position Point3        `json:"position"`
	Score    float32       `json:"score"`
}

// PerimeterRegionView represents the imported resource "slicer:ir-handles/ir-handles#perimeter-region-view".
//
//	resource perimeter-region-view
type PerimeterRegionView cm.Resource

// ResourceDrop represents the imported resource-drop for resource "perimeter-region-view".
//
// Drops a resource handle.
//
//go:nosplit
func (self PerimeterRegionView) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_PerimeterRegionViewResourceDrop((uint32)(self0))
	return
}

// BottomSolidFill represents the imported method "bottom-solid-fill".
//
//	bottom-solid-fill: func() -> list<ex-polygon>
//
//go:nosplit
func (self PerimeterRegionView) BottomSolidFill() (result cm.List[ExPolygon]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_PerimeterRegionViewBottomSolidFill((uint32)(self0), &result)
	return
}

// BridgeAreas represents the imported method "bridge-areas".
//
//	bridge-areas: func() -> list<ex-polygon>
//
//go:nosplit
func (self PerimeterRegionView) BridgeAreas() (result cm.List[ExPolygon]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_PerimeterRegionViewBridgeAreas((uint32)(self0), &result)
	return
}

// Config represents the imported method "config".
//
// Per-region config view for this perimeter region. Host-populated at
// dispatch time (packet 131, Step 3) so region-scoped modules can read
// per-region overrides without routing through the module-level config.
//
//	config: func() -> config-view
//
//go:nosplit
func (self PerimeterRegionView) Config() (result ConfigView) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_PerimeterRegionViewConfig((uint32)(self0))
	result = cm.Reinterpret[ConfigView]((uint32)(result0))
	return
}

// InfillAreas represents the imported method "infill-areas".
//
//	infill-areas: func() -> list<ex-polygon>
//
//go:nosplit
func (self PerimeterRegionView) InfillAreas() (result cm.List[ExPolygon]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_PerimeterRegionViewInfillAreas((uint32)(self0), &result)
	return
}

// ObjectID represents the imported method "object-id".
//
//	object-id: func() -> object-id
//
//go:nosplit
func (self PerimeterRegionView) ObjectID() (result ObjectID) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_PerimeterRegionViewObjectID((uint32)(self0), &result)
	return
}

// RegionID represents the imported method "region-id".
//
//	region-id: func() -> region-id
//
//go:nosplit
func (self PerimeterRegionView) RegionID() (result RegionID) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_PerimeterRegionViewRegionID((uint32)(self0), &result)
	return
}

// ResolvedSeam represents the imported method "resolved-seam".
//
//	resolved-seam: func() -> option<seam-position>
//
//go:nosplit
func (self PerimeterRegionView) ResolvedSeam() (result cm.Option[SeamPosition]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_PerimeterRegionViewResolvedSeam((uint32)(self0), &result)
	return
}

// SeamCandidates represents the imported method "seam-candidates".
//
//	seam-candidates: func() -> list<seam-candidate>
//
//go:nosplit
func (self PerimeterRegionView) SeamCandidates() (result cm.List[SeamCandidate]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_PerimeterRegionViewSeamCandidates((uint32)(self0), &result)
	return
}

// SparseInfillArea represents the imported method "sparse-infill-area".
//
// Partitioned fill polygons mirrored from the corresponding
// slice-region-view accessors (ADR-0028 Change 2 + §Amendment
// 2026-07-01). Host-populated at dispatch time so
// `Layer::InfillPostProcess` consumers can re-clip against the
// partitioned boundary.
//
//	sparse-infill-area: func() -> list<ex-polygon>
//
//go:nosplit
func (self PerimeterRegionView) SparseInfillArea() (result cm.List[ExPolygon]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_PerimeterRegionViewSparseInfillArea((uint32)(self0), &result)
	return
}

// ToolIndex represents the imported method "tool-index".
//
// Host-computed tool index: variant-chain material tool →
// RegionMapIR extensions["extruder"] → DEFAULT_TOOL(0).
//
//	tool-index: func() -> u32
//
//go:nosplit
func (self PerimeterRegionView) ToolIndex() (result uint32) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_PerimeterRegionViewToolIndex((uint32)(self0))
	result = (uint32)((uint32)(result0))
	return
}

// TopSolidFill represents the imported method "top-solid-fill".
//
//	top-solid-fill: func() -> list<ex-polygon>
//
//go:nosplit
func (self PerimeterRegionView) TopSolidFill() (result cm.List[ExPolygon]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_PerimeterRegionViewTopSolidFill((uint32)(self0), &result)
	return
}

// WallLoops represents the imported method "wall-loops".
//
//	wall-loops: func() -> list<wall-loop-view>
//
//go:nosplit
func (self PerimeterRegionView) WallLoops() (result cm.List[WallLoopView]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_PerimeterRegionViewWallLoops((uint32)(self0), &result)
	return
}

// WallSourceRegionID represents the imported method "wall-source-region-id".
//
// none = this region owns its walls; some(base) = this region
// shares the base region's walls (ADR-0028 §Amendment 2026-07-01).
//
//	wall-source-region-id: func() -> option<region-id>
//
//go:nosplit
func (self PerimeterRegionView) WallSourceRegionID() (result cm.Option[RegionID]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_PerimeterRegionViewWallSourceRegionID((uint32)(self0), &result)
	return
}

// PriorInfillRegion represents the record "slicer:ir-handles/ir-handles#prior-infill-region".
//
// Read-only snapshot of one `InfillIR` region bucket, mirroring
// `slicer_ir::InfillRegion` (ADR-0028 Option 1b). Passed to
// `run-infill-postprocess` as the `prior-infill` parameter so the
// post-process module can read what `Layer::Infill` emitted; the
// `infill-output-builder` stays write-only.
//
//	record prior-infill-region {
//		object-id: object-id,
//		region-id: region-id,
//		sparse-infill: list<extrusion-path3d>,
//		solid-infill: list<extrusion-path3d>,
//		ironing: list<extrusion-path3d>,
//	}
type PriorInfillRegion struct {
	_            cm.HostLayout            `json:"-"`
	ObjectID     ObjectID                 `json:"object-id"`
	RegionID     RegionID                 `json:"region-id"`
	SparseInfill cm.List[ExtrusionPath3d] `json:"sparse-infill"`
	SolidInfill  cm.List[ExtrusionPath3d] `json:"solid-infill"`
	Ironing      cm.List[ExtrusionPath3d] `json:"ironing"`
}

// InfillOutputBuilder represents the imported resource "slicer:ir-handles/ir-handles#infill-output-builder".
//
//	resource infill-output-builder
type InfillOutputBuilder cm.Resource

// ResourceDrop represents the imported resource-drop for resource "infill-output-builder".
//
// Drops a resource handle.
//
//go:nosplit
func (self InfillOutputBuilder) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_InfillOutputBuilderResourceDrop((uint32)(self0))
	return
}

// PushIroningPath represents the imported method "push-ironing-path".
//
//	push-ironing-path: func(path: extrusion-path3d) -> result<_, string>
//
//go:nosplit
func (self InfillOutputBuilder) PushIroningPath(path ExtrusionPath3d) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	path0, path1, path2, path3, path4, path5 := lower_ExtrusionPath3d(path)
	wasmimport_InfillOutputBuilderPushIroningPath((uint32)(self0), (*geometry.Point3WithWidth)(path0), (uint32)(path1), (uint32)(path2), (*uint8)(path3), (uint32)(path4), (float32)(path5), &result)
	return
}

// PushSolidPath represents the imported method "push-solid-path".
//
//	push-solid-path: func(path: extrusion-path3d) -> result<_, string>
//
//go:nosplit
func (self InfillOutputBuilder) PushSolidPath(path ExtrusionPath3d) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	path0, path1, path2, path3, path4, path5 := lower_ExtrusionPath3d(path)
	wasmimport_InfillOutputBuilderPushSolidPath((uint32)(self0), (*geometry.Point3WithWidth)(path0), (uint32)(path1), (uint32)(path2), (*uint8)(path3), (uint32)(path4), (float32)(path5), &result)
	return
}

// PushSparsePath represents the imported method "push-sparse-path".
//
//	push-sparse-path: func(path: extrusion-path3d) -> result<_, string>
//
//go:nosplit
func (self InfillOutputBuilder) PushSparsePath(path ExtrusionPath3d) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	path0, path1, path2, path3, path4, path5 := lower_ExtrusionPath3d(path)
	wasmimport_InfillOutputBuilderPushSparsePath((uint32)(self0), (*geometry.Point3WithWidth)(path0), (uint32)(path1), (uint32)(path2), (*uint8)(path3), (uint32)(path4), (float32)(path5), &result)
	return
}

// SetCurrentOrigin represents the imported method "set-current-origin".
//
//	set-current-origin: func(object-id: string, region-id: string) -> result<_, string>
//
//go:nosplit
func (self InfillOutputBuilder) SetCurrentOrigin(objectID string, regionID string) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	objectId0, objectId1 := cm.LowerString(objectID)
	regionId0, regionId1 := cm.LowerString(regionID)
	wasmimport_InfillOutputBuilderSetCurrentOrigin((uint32)(self0), (*uint8)(objectId0), (uint32)(objectId1), (*uint8)(regionId0), (uint32)(regionId1), &result)
	return
}

// PerimeterOutputBuilder represents the imported resource "slicer:ir-handles/ir-handles#perimeter-output-builder".
//
//	resource perimeter-output-builder
type PerimeterOutputBuilder cm.Resource

// ResourceDrop represents the imported resource-drop for resource "perimeter-output-builder".
//
// Drops a resource handle.
//
//go:nosplit
func (self PerimeterOutputBuilder) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_PerimeterOutputBuilderResourceDrop((uint32)(self0))
	return
}

// PushReorderedWallLoop represents the imported method "push-reordered-wall-loop".
//
//	push-reordered-wall-loop: func(pos: point3-with-width, wall-index: u32, rotated-wall-loop:
//	wall-loop-view) -> result<_, string>
//
//go:nosplit
func (self PerimeterOutputBuilder) PushReorderedWallLoop(pos Point3WithWidth, wallIndex uint32, rotatedWallLoop WallLoopView) (result cm.Result[string, struct{}, string]) {
	params := wasmimport_PerimeterOutputBuilderPushReorderedWallLoop_params{self: self, pos: pos, wallIndex: wallIndex, rotatedWallLoop: rotatedWallLoop}
	wasmimport_PerimeterOutputBuilderPushReorderedWallLoop(&params, &result)
	return
}

// wasmimport_PerimeterOutputBuilderPushReorderedWallLoop_params represents the flattened function params for [wasmimport_PerimeterOutputBuilderPushReorderedWallLoop].
// See the Canonical ABI flattening rules for more information.
type wasmimport_PerimeterOutputBuilderPushReorderedWallLoop_params struct {
	_               cm.HostLayout          `json:"-"`
	self            PerimeterOutputBuilder `json:"self"`
	pos             Point3WithWidth        `json:"pos"`
	wallIndex       uint32                 `json:"wall-index"`
	rotatedWallLoop WallLoopView           `json:"rotated-wall-loop"`
}

// PushResolvedSeam represents the imported method "push-resolved-seam".
//
//	push-resolved-seam: func(pos: point3, wall-index: u32) -> result<_, string>
//
//go:nosplit
func (self PerimeterOutputBuilder) PushResolvedSeam(pos Point3, wallIndex uint32) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	pos0, pos1, pos2 := lower_Point3(pos)
	wallIndex0 := (uint32)(wallIndex)
	wasmimport_PerimeterOutputBuilderPushResolvedSeam((uint32)(self0), (float32)(pos0), (float32)(pos1), (float32)(pos2), (uint32)(wallIndex0), &result)
	return
}

// PushSeamCandidate represents the imported method "push-seam-candidate".
//
//	push-seam-candidate: func(pos: point3, score: f32) -> result<_, string>
//
//go:nosplit
func (self PerimeterOutputBuilder) PushSeamCandidate(pos Point3, score float32) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	pos0, pos1, pos2 := lower_Point3(pos)
	score0 := (float32)(score)
	wasmimport_PerimeterOutputBuilderPushSeamCandidate((uint32)(self0), (float32)(pos0), (float32)(pos1), (float32)(pos2), (float32)(score0), &result)
	return
}

// PushWallLoop represents the imported method "push-wall-loop".
//
//	push-wall-loop: func(wall-loop: wall-loop-view) -> result<_, string>
//
//go:nosplit
func (self PerimeterOutputBuilder) PushWallLoop(wallLoop WallLoopView) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	wallLoop0, wallLoop1, wallLoop2, wallLoop3, wallLoop4, wallLoop5, wallLoop6, wallLoop7, wallLoop8, wallLoop9, wallLoop10, wallLoop11, wallLoop12 := lower_WallLoopView(wallLoop)
	wasmimport_PerimeterOutputBuilderPushWallLoop((uint32)(self0), (uint32)(wallLoop0), (uint32)(wallLoop1), (*geometry.Point3WithWidth)(wallLoop2), (uint32)(wallLoop3), (uint32)(wallLoop4), (*uint8)(wallLoop5), (uint32)(wallLoop6), (float32)(wallLoop7), (*WallFeatureFlag)(wallLoop8), (uint32)(wallLoop9), (uint32)(wallLoop10), (*MaterialBoundarySegment)(wallLoop11), (uint32)(wallLoop12), &result)
	return
}

// SetCurrentOrigin represents the imported method "set-current-origin".
//
//	set-current-origin: func(object-id: string, region-id: string) -> result<_, string>
//
//go:nosplit
func (self PerimeterOutputBuilder) SetCurrentOrigin(objectID string, regionID string) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	objectId0, objectId1 := cm.LowerString(objectID)
	regionId0, regionId1 := cm.LowerString(regionID)
	wasmimport_PerimeterOutputBuilderSetCurrentOrigin((uint32)(self0), (*uint8)(objectId0), (uint32)(objectId1), (*uint8)(regionId0), (uint32)(regionId1), &result)
	return
}

// SetInfillAreas represents the imported method "set-infill-areas".
//
//	set-infill-areas: func(areas: list<ex-polygon>) -> result<_, string>
//
//go:nosplit
func (self PerimeterOutputBuilder) SetInfillAreas(areas cm.List[ExPolygon]) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	areas0, areas1 := cm.LowerList(areas)
	wasmimport_PerimeterOutputBuilderSetInfillAreas((uint32)(self0), (*ExPolygon)(areas0), (uint32)(areas1), &result)
	return
}

// SlicePostprocessBuilder represents the imported resource "slicer:ir-handles/ir-handles#slice-postprocess-builder".
//
//	resource slice-postprocess-builder
type SlicePostprocessBuilder cm.Resource

// ResourceDrop represents the imported resource-drop for resource "slice-postprocess-builder".
//
// Drops a resource handle.
//
//go:nosplit
func (self SlicePostprocessBuilder) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SlicePostprocessBuilderResourceDrop((uint32)(self0))
	return
}

// SetPathZ represents the imported method "set-path-z".
//
//	set-path-z: func(region: region-key, path-idx: u32, vertex-idx: u32, z: f32) ->
//	result<_, string>
//
//go:nosplit
func (self SlicePostprocessBuilder) SetPathZ(region RegionKey, pathIdx uint32, vertexIdx uint32, z float32) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	region0, region1, region2, region3, region4, region5, region6 := lower_RegionKey(region)
	pathIdx0 := (uint32)(pathIdx)
	vertexIdx0 := (uint32)(vertexIdx)
	z0 := (float32)(z)
	wasmimport_SlicePostprocessBuilderSetPathZ((uint32)(self0), (uint32)(region0), (*uint8)(region1), (uint32)(region2), (*uint8)(region3), (uint32)(region4), (*cm.Tuple[string, PaintValue])(region5), (uint32)(region6), (uint32)(pathIdx0), (uint32)(vertexIdx0), (float32)(z0), &result)
	return
}

// SetPolygons represents the imported method "set-polygons".
//
//	set-polygons: func(region: region-key, polys: list<ex-polygon>) -> result<_, string>
//
//go:nosplit
func (self SlicePostprocessBuilder) SetPolygons(region RegionKey, polys cm.List[ExPolygon]) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	region0, region1, region2, region3, region4, region5, region6 := lower_RegionKey(region)
	polys0, polys1 := cm.LowerList(polys)
	wasmimport_SlicePostprocessBuilderSetPolygons((uint32)(self0), (uint32)(region0), (*uint8)(region1), (uint32)(region2), (*uint8)(region3), (uint32)(region4), (*cm.Tuple[string, PaintValue])(region5), (uint32)(region6), (*ExPolygon)(polys0), (uint32)(polys1), &result)
	return
}

// GcodeMoveCmd represents the record "slicer:ir-handles/ir-handles#gcode-move-cmd".
//
//	record gcode-move-cmd {
//		x: option<f32>,
//		y: option<f32>,
//		z: option<f32>,
//		e: option<f32>,
//		f: option<f32>,
//		role: extrusion-role,
//	}
type GcodeMoveCmd struct {
	_    cm.HostLayout      `json:"-"`
	X    cm.Option[float32] `json:"x"`
	Y    cm.Option[float32] `json:"y"`
	Z    cm.Option[float32] `json:"z"`
	E    cm.Option[float32] `json:"e"`
	F    cm.Option[float32] `json:"f"`
	Role ExtrusionRole      `json:"role"`
}

// RetractMode represents the variant "slicer:ir-handles/ir-handles#retract-mode".
//
//	variant retract-mode {
//		gcode,
//		firmware,
//	}
type RetractMode uint8

const (
	RetractModeGcode RetractMode = iota
	RetractModeFirmware
)

var _RetractModeStrings = [2]string{
	"gcode",
	"firmware",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e RetractMode) String() string {
	return _RetractModeStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e RetractMode) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *RetractMode) UnmarshalText(text []byte) error {
	return _RetractModeUnmarshalCase(e, text)
}

var _RetractModeUnmarshalCase = cm.CaseUnmarshaler[RetractMode](_RetractModeStrings[:])

// GcodeOutputBuilder represents the imported resource "slicer:ir-handles/ir-handles#gcode-output-builder".
//
//	resource gcode-output-builder
type GcodeOutputBuilder cm.Resource

// ResourceDrop represents the imported resource-drop for resource "gcode-output-builder".
//
// Drops a resource handle.
//
//go:nosplit
func (self GcodeOutputBuilder) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_GcodeOutputBuilderResourceDrop((uint32)(self0))
	return
}

// PushComment represents the imported method "push-comment".
//
//	push-comment: func(text: string) -> result<_, string>
//
//go:nosplit
func (self GcodeOutputBuilder) PushComment(text string) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	text0, text1 := cm.LowerString(text)
	wasmimport_GcodeOutputBuilderPushComment((uint32)(self0), (*uint8)(text0), (uint32)(text1), &result)
	return
}

// PushFanSpeed represents the imported method "push-fan-speed".
//
//	push-fan-speed: func(value: u8) -> result<_, string>
//
//go:nosplit
func (self GcodeOutputBuilder) PushFanSpeed(value uint8) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	value0 := (uint32)(value)
	wasmimport_GcodeOutputBuilderPushFanSpeed((uint32)(self0), (uint32)(value0), &result)
	return
}

// PushMove represents the imported method "push-move".
//
//	push-move: func(cmd: gcode-move-cmd) -> result<_, string>
//
//go:nosplit
func (self GcodeOutputBuilder) PushMove(cmd GcodeMoveCmd) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	cmd0, cmd1, cmd2, cmd3, cmd4, cmd5, cmd6, cmd7, cmd8, cmd9, cmd10, cmd11, cmd12 := lower_GcodeMoveCmd(cmd)
	wasmimport_GcodeOutputBuilderPushMove((uint32)(self0), (uint32)(cmd0), (float32)(cmd1), (uint32)(cmd2), (float32)(cmd3), (uint32)(cmd4), (float32)(cmd5), (uint32)(cmd6), (float32)(cmd7), (uint32)(cmd8), (float32)(cmd9), (uint32)(cmd10), (*uint8)(cmd11), (uint32)(cmd12), &result)
	return
}

// PushRaw represents the imported method "push-raw".
//
//	push-raw: func(text: string) -> result<_, string>
//
//go:nosplit
func (self GcodeOutputBuilder) PushRaw(text string) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	text0, text1 := cm.LowerString(text)
	wasmimport_GcodeOutputBuilderPushRaw((uint32)(self0), (*uint8)(text0), (uint32)(text1), &result)
	return
}

// PushRetract represents the imported method "push-retract".
//
//	push-retract: func(length: f32, speed: f32, mode: retract-mode) -> result<_, string>
//
//go:nosplit
func (self GcodeOutputBuilder) PushRetract(length float32, speed float32, mode RetractMode) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	length0 := (float32)(length)
	speed0 := (float32)(speed)
	mode0 := (uint32)(mode)
	wasmimport_GcodeOutputBuilderPushRetract((uint32)(self0), (float32)(length0), (float32)(speed0), (uint32)(mode0), &result)
	return
}

// PushTemperature represents the imported method "push-temperature".
//
//	push-temperature: func(tool: u32, celsius: f32, wait: bool) -> result<_, string>
//
//go:nosplit
func (self GcodeOutputBuilder) PushTemperature(tool uint32, celsius float32, wait bool) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	tool0 := (uint32)(tool)
	celsius0 := (float32)(celsius)
	wait0 := (uint32)(cm.BoolToU32(wait))
	wasmimport_GcodeOutputBuilderPushTemperature((uint32)(self0), (uint32)(tool0), (float32)(celsius0), (uint32)(wait0), &result)
	return
}

// PushToolChange represents the imported method "push-tool-change".
//
//	push-tool-change: func(after-entity-index: u32, from-tool: u32, to-tool: u32) ->
//	result<_, string>
//
//go:nosplit
func (self GcodeOutputBuilder) PushToolChange(afterEntityIndex uint32, fromTool uint32, toTool uint32) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	afterEntityIndex0 := (uint32)(afterEntityIndex)
	fromTool0 := (uint32)(fromTool)
	toTool0 := (uint32)(toTool)
	wasmimport_GcodeOutputBuilderPushToolChange((uint32)(self0), (uint32)(afterEntityIndex0), (uint32)(fromTool0), (uint32)(toTool0), &result)
	return
}

// PushUnretract represents the imported method "push-unretract".
//
//	push-unretract: func(length: f32, speed: f32, mode: retract-mode) -> result<_,
//	string>
//
//go:nosplit
func (self GcodeOutputBuilder) PushUnretract(length float32, speed float32, mode RetractMode) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	length0 := (float32)(length)
	speed0 := (float32)(speed)
	mode0 := (uint32)(mode)
	wasmimport_GcodeOutputBuilderPushUnretract((uint32)(self0), (float32)(length0), (float32)(speed0), (uint32)(mode0), &result)
	return
}

// PushZHop represents the imported method "push-z-hop".
//
//	push-z-hop: func(after-entity-index: u32, hop-height: f32) -> result<_, string>
//
//go:nosplit
func (self GcodeOutputBuilder) PushZHop(afterEntityIndex uint32, hopHeight float32) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	afterEntityIndex0 := (uint32)(afterEntityIndex)
	hopHeight0 := (float32)(hopHeight)
	wasmimport_GcodeOutputBuilderPushZHop((uint32)(self0), (uint32)(afterEntityIndex0), (float32)(hopHeight0), &result)
	return
}

// OrderedEntityView represents the record "slicer:ir-handles/ir-handles#ordered-entity-view".
//
//	record ordered-entity-view {
//		original-index: u32,
//		tool-index: u32,
//		region-key: region-key,
//		role: extrusion-role,
//		start-point: point3-with-width,
//		end-point: point3-with-width,
//		point-count: u32,
//	}
type OrderedEntityView struct {
	_             cm.HostLayout `json:"-"`
	OriginalIndex uint32        `json:"original-index"`

	// Resolved tool/extruder index (first-class selector since the
	// region_id↔tool split; read this, not region-key.region-id).
	ToolIndex  uint32          `json:"tool-index"`
	RegionKey  RegionKey       `json:"region-key"`
	Role       ExtrusionRole   `json:"role"`
	StartPoint Point3WithWidth `json:"start-point"`
	EndPoint   Point3WithWidth `json:"end-point"`
	PointCount uint32          `json:"point-count"`
}

// LayerCollectionBuilder represents the imported resource "slicer:ir-handles/ir-handles#layer-collection-builder".
//
//	resource layer-collection-builder
type LayerCollectionBuilder cm.Resource

// ResourceDrop represents the imported resource-drop for resource "layer-collection-builder".
//
// Drops a resource handle.
//
//go:nosplit
func (self LayerCollectionBuilder) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_LayerCollectionBuilderResourceDrop((uint32)(self0))
	return
}

// GetOrderedEntities represents the imported method "get-ordered-entities".
//
//	get-ordered-entities: func() -> list<ordered-entity-view>
//
//go:nosplit
func (self LayerCollectionBuilder) GetOrderedEntities() (result cm.List[OrderedEntityView]) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_LayerCollectionBuilderGetOrderedEntities((uint32)(self0), &result)
	return
}

// SetEntityOrder represents the imported method "set-entity-order".
//
//	set-entity-order: func(items: list<tuple<u32, bool>>) -> result<_, string>
//
//go:nosplit
func (self LayerCollectionBuilder) SetEntityOrder(items cm.List[cm.Tuple[uint32, bool]]) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	items0, items1 := cm.LowerList(items)
	wasmimport_LayerCollectionBuilderSetEntityOrder((uint32)(self0), (*cm.Tuple[uint32, bool])(items0), (uint32)(items1), &result)
	return
}

// SupportOutputBuilder represents the imported resource "slicer:ir-handles/ir-handles#support-output-builder".
//
//	resource support-output-builder
type SupportOutputBuilder cm.Resource

// ResourceDrop represents the imported resource-drop for resource "support-output-builder".
//
// Drops a resource handle.
//
//go:nosplit
func (self SupportOutputBuilder) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SupportOutputBuilderResourceDrop((uint32)(self0))
	return
}

// PushInterfacePath represents the imported method "push-interface-path".
//
//	push-interface-path: func(path: extrusion-path3d, is-top-interface: bool) -> result<_,
//	string>
//
//go:nosplit
func (self SupportOutputBuilder) PushInterfacePath(path ExtrusionPath3d, isTopInterface bool) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	path0, path1, path2, path3, path4, path5 := lower_ExtrusionPath3d(path)
	isTopInterface0 := (uint32)(cm.BoolToU32(isTopInterface))
	wasmimport_SupportOutputBuilderPushInterfacePath((uint32)(self0), (*geometry.Point3WithWidth)(path0), (uint32)(path1), (uint32)(path2), (*uint8)(path3), (uint32)(path4), (float32)(path5), (uint32)(isTopInterface0), &result)
	return
}

// PushRaftPath represents the imported method "push-raft-path".
//
//	push-raft-path: func(path: extrusion-path3d) -> result<_, string>
//
//go:nosplit
func (self SupportOutputBuilder) PushRaftPath(path ExtrusionPath3d) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	path0, path1, path2, path3, path4, path5 := lower_ExtrusionPath3d(path)
	wasmimport_SupportOutputBuilderPushRaftPath((uint32)(self0), (*geometry.Point3WithWidth)(path0), (uint32)(path1), (uint32)(path2), (*uint8)(path3), (uint32)(path4), (float32)(path5), &result)
	return
}

// PushSupportPath represents the imported method "push-support-path".
//
//	push-support-path: func(path: extrusion-path3d) -> result<_, string>
//
//go:nosplit
func (self SupportOutputBuilder) PushSupportPath(path ExtrusionPath3d) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	path0, path1, path2, path3, path4, path5 := lower_ExtrusionPath3d(path)
	wasmimport_SupportOutputBuilderPushSupportPath((uint32)(self0), (*geometry.Point3WithWidth)(path0), (uint32)(path1), (uint32)(path2), (*uint8)(path3), (uint32)(path4), (float32)(path5), &result)
	return
}

// SetCurrentOrigin represents the imported method "set-current-origin".
//
//	set-current-origin: func(object-id: string, region-id: string) -> result<_, string>
//
//go:nosplit
func (self SupportOutputBuilder) SetCurrentOrigin(objectID string, regionID string) (result cm.Result[string, struct{}, string]) {
	self0 := cm.Reinterpret[uint32](self)
	objectId0, objectId1 := cm.LowerString(objectID)
	regionId0, regionId1 := cm.LowerString(regionID)
	wasmimport_SupportOutputBuilderSetCurrentOrigin((uint32)(self0), (*uint8)(objectId0), (uint32)(objectId1), (*uint8)(regionId0), (uint32)(regionId1), &result)
	return
}

// SemanticRegion represents the record "slicer:ir-handles/ir-handles#semantic-region".
//
//	record semantic-region {
//		object-id: object-id,
//		polygons: list<ex-polygon>,
//		value: paint-value,
//	}
type SemanticRegion struct {
	_        cm.HostLayout      `json:"-"`
	ObjectID ObjectID           `json:"object-id"`
	Polygons cm.List[ExPolygon] `json:"polygons"`
	Value    PaintValue         `json:"value"`
}

// PaintRegionLayerView represents the imported resource "slicer:ir-handles/ir-handles#paint-region-layer-view".
//
//	resource paint-region-layer-view
type PaintRegionLayerView cm.Resource

// ResourceDrop represents the imported resource-drop for resource "paint-region-layer-view".
//
// Drops a resource handle.
//
//go:nosplit
func (self PaintRegionLayerView) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_PaintRegionLayerViewResourceDrop((uint32)(self0))
	return
}

// GetCustomRegions represents the imported method "get-custom-regions".
//
//	get-custom-regions: func(module-id: string) -> list<semantic-region>
//
//go:nosplit
func (self PaintRegionLayerView) GetCustomRegions(moduleID string) (result cm.List[SemanticRegion]) {
	self0 := cm.Reinterpret[uint32](self)
	moduleId0, moduleId1 := cm.LowerString(moduleID)
	wasmimport_PaintRegionLayerViewGetCustomRegions((uint32)(self0), (*uint8)(moduleId0), (uint32)(moduleId1), &result)
	return
}

// GetRegions represents the imported method "get-regions".
//
//	get-regions: func(semantic: paint-semantic) -> list<semantic-region>
//
//go:nosplit
func (self PaintRegionLayerView) GetRegions(semantic PaintSemantic) (result cm.List[SemanticRegion]) {
	self0 := cm.Reinterpret[uint32](self)
	semantic0, semantic1, semantic2 := lower_PaintSemantic(semantic)
	wasmimport_PaintRegionLayerViewGetRegions((uint32)(self0), (uint32)(semantic0), (*uint8)(semantic1), (uint32)(semantic2), &result)
	return
}

// LayerIndex represents the imported method "layer-index".
//
//	layer-index: func() -> layer-idx
//
//go:nosplit
func (self PaintRegionLayerView) LayerIndex() (result LayerIdx) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_PaintRegionLayerViewLayerIndex((uint32)(self0))
	result = (LayerIdx)((uint32)(result0))
	return
}

// LightningTreeSegments represents the imported method "lightning-tree-segments".
//
//	lightning-tree-segments: func(object-id: object-id, region-id: region-id) -> list<list<point3-with-width>>
//
//go:nosplit
func (self PaintRegionLayerView) LightningTreeSegments(objectID ObjectID, regionID RegionID) (result cm.List[cm.List[Point3WithWidth]]) {
	self0 := cm.Reinterpret[uint32](self)
	objectId0, objectId1 := cm.LowerString(objectID)
	regionId0, regionId1 := cm.LowerString(regionID)
	wasmimport_PaintRegionLayerViewLightningTreeSegments((uint32)(self0), (*uint8)(objectId0), (uint32)(objectId1), (*uint8)(regionId0), (uint32)(regionId1), &result)
	return
}

// SupportPlanSegments represents the imported method "support-plan-segments".
//
//	support-plan-segments: func(object-id: object-id, region-id: region-id) -> list<list<point3-with-width>>
//
//go:nosplit
func (self PaintRegionLayerView) SupportPlanSegments(objectID ObjectID, regionID RegionID) (result cm.List[cm.List[Point3WithWidth]]) {
	self0 := cm.Reinterpret[uint32](self)
	objectId0, objectId1 := cm.LowerString(objectID)
	regionId0, regionId1 := cm.LowerString(regionID)
	wasmimport_PaintRegionLayerViewSupportPlanSegments((uint32)(self0), (*uint8)(objectId0), (uint32)(objectId1), (*uint8)(regionId0), (uint32)(regionId1), &result)
	return
}
