// Code generated by wit-bindgen-go. DO NOT EDIT.

package irhandles

import (
	"foreign-language-text-postprocess/slicer/types/geometry"
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "slicer:ir-handles".

//go:wasmimport slicer:ir-handles/ir-handles [resource-drop]slice-region-view
//go:noescape
func wasmimport_SliceRegionViewResourceDrop(self0 uint32)

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.bottom-shell-index
//go:noescape
func wasmimport_SliceRegionViewBottomShellIndex(self0 uint32, result *cm.Option[uint8])

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.bottom-solid-fill
//go:noescape
func wasmimport_SliceRegionViewBottomSolidFill(self0 uint32, result *cm.List[ExPolygon])

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.bridge-areas
//go:noescape
func wasmimport_SliceRegionViewBridgeAreas(self0 uint32, result *cm.List[ExPolygon])

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.bridge-orientation-deg
//go:noescape
func wasmimport_SliceRegionViewBridgeOrientationDeg(self0 uint32) (result0 float32)

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.config
//go:noescape
func wasmimport_SliceRegionViewConfig(self0 uint32) (result0 uint32)

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.effective-layer-height
//go:noescape
func wasmimport_SliceRegionViewEffectiveLayerHeight(self0 uint32) (result0 float32)

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.has-nonplanar
//go:noescape
func wasmimport_SliceRegionViewHasNonplanar(self0 uint32) (result0 uint32)

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.held-claims
//go:noescape
func wasmimport_SliceRegionViewHeldClaims(self0 uint32, result *cm.List[string])

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.infill-areas
//go:noescape
func wasmimport_SliceRegionViewInfillAreas(self0 uint32, result *cm.List[ExPolygon])

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.is-bridge
//go:noescape
func wasmimport_SliceRegionViewIsBridge(self0 uint32) (result0 uint32)

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.needs-support
//go:noescape
func wasmimport_SliceRegionViewNeedsSupport(self0 uint32) (result0 uint32)

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.object-id
//go:noescape
func wasmimport_SliceRegionViewObjectID(self0 uint32, result *ObjectID)

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.overhang-areas
//go:noescape
func wasmimport_SliceRegionViewOverhangAreas(self0 uint32, result *cm.List[ExPolygon])

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.overhang-quartile-polygons
//go:noescape
func wasmimport_SliceRegionViewOverhangQuartilePolygons(self0 uint32, result *cm.List[QuartileBand])

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.polygons
//go:noescape
func wasmimport_SliceRegionViewPolygons(self0 uint32, result *cm.List[ExPolygon])

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.prev-layer-boundary
//go:noescape
func wasmimport_SliceRegionViewPrevLayerBoundary(self0 uint32, result *cm.List[ExPolygon])

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.region-id
//go:noescape
func wasmimport_SliceRegionViewRegionID(self0 uint32, result *RegionID)

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.segment-annotations
//go:noescape
func wasmimport_SliceRegionViewSegmentAnnotations(self0 uint32, result *cm.List[SegmentAnnotationsEntry])

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.sparse-infill-area
//go:noescape
func wasmimport_SliceRegionViewSparseInfillArea(self0 uint32, result *cm.List[ExPolygon])

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.surface-group
//go:noescape
func wasmimport_SliceRegionViewSurfaceGroup(self0 uint32, result *cm.Option[SurfaceGroup])

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.top-shell-index
//go:noescape
func wasmimport_SliceRegionViewTopShellIndex(self0 uint32, result *cm.Option[uint8])

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.top-solid-fill
//go:noescape
func wasmimport_SliceRegionViewTopSolidFill(self0 uint32, result *cm.List[ExPolygon])

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.variant-chain
//go:noescape
func wasmimport_SliceRegionViewVariantChain(self0 uint32, result *cm.List[cm.Tuple[string, PaintValue]])

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-region-view.z
//go:noescape
func wasmimport_SliceRegionViewZ(self0 uint32) (result0 float32)

//go:wasmimport slicer:ir-handles/ir-handles [resource-drop]perimeter-region-view
//go:noescape
func wasmimport_PerimeterRegionViewResourceDrop(self0 uint32)

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-region-view.bottom-solid-fill
//go:noescape
func wasmimport_PerimeterRegionViewBottomSolidFill(self0 uint32, result *cm.List[ExPolygon])

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-region-view.bridge-areas
//go:noescape
func wasmimport_PerimeterRegionViewBridgeAreas(self0 uint32, result *cm.List[ExPolygon])

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-region-view.config
//go:noescape
func wasmimport_PerimeterRegionViewConfig(self0 uint32) (result0 uint32)

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-region-view.infill-areas
//go:noescape
func wasmimport_PerimeterRegionViewInfillAreas(self0 uint32, result *cm.List[ExPolygon])

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-region-view.object-id
//go:noescape
func wasmimport_PerimeterRegionViewObjectID(self0 uint32, result *ObjectID)

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-region-view.region-id
//go:noescape
func wasmimport_PerimeterRegionViewRegionID(self0 uint32, result *RegionID)

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-region-view.resolved-seam
//go:noescape
func wasmimport_PerimeterRegionViewResolvedSeam(self0 uint32, result *cm.Option[SeamPosition])

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-region-view.seam-candidates
//go:noescape
func wasmimport_PerimeterRegionViewSeamCandidates(self0 uint32, result *cm.List[SeamCandidate])

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-region-view.sparse-infill-area
//go:noescape
func wasmimport_PerimeterRegionViewSparseInfillArea(self0 uint32, result *cm.List[ExPolygon])

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-region-view.tool-index
//go:noescape
func wasmimport_PerimeterRegionViewToolIndex(self0 uint32) (result0 uint32)

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-region-view.top-solid-fill
//go:noescape
func wasmimport_PerimeterRegionViewTopSolidFill(self0 uint32, result *cm.List[ExPolygon])

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-region-view.wall-loops
//go:noescape
func wasmimport_PerimeterRegionViewWallLoops(self0 uint32, result *cm.List[WallLoopView])

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-region-view.wall-source-region-id
//go:noescape
func wasmimport_PerimeterRegionViewWallSourceRegionID(self0 uint32, result *cm.Option[RegionID])

//go:wasmimport slicer:ir-handles/ir-handles [resource-drop]infill-output-builder
//go:noescape
func wasmimport_InfillOutputBuilderResourceDrop(self0 uint32)

//go:wasmimport slicer:ir-handles/ir-handles [method]infill-output-builder.push-ironing-path
//go:noescape
func wasmimport_InfillOutputBuilderPushIroningPath(self0 uint32, path0 *geometry.Point3WithWidth, path1 uint32, path2 uint32, path3 *uint8, path4 uint32, path5 float32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]infill-output-builder.push-solid-path
//go:noescape
func wasmimport_InfillOutputBuilderPushSolidPath(self0 uint32, path0 *geometry.Point3WithWidth, path1 uint32, path2 uint32, path3 *uint8, path4 uint32, path5 float32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]infill-output-builder.push-sparse-path
//go:noescape
func wasmimport_InfillOutputBuilderPushSparsePath(self0 uint32, path0 *geometry.Point3WithWidth, path1 uint32, path2 uint32, path3 *uint8, path4 uint32, path5 float32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]infill-output-builder.set-current-origin
//go:noescape
func wasmimport_InfillOutputBuilderSetCurrentOrigin(self0 uint32, objectId0 *uint8, objectId1 uint32, regionId0 *uint8, regionId1 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [resource-drop]perimeter-output-builder
//go:noescape
func wasmimport_PerimeterOutputBuilderResourceDrop(self0 uint32)

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-output-builder.push-reordered-wall-loop
//go:noescape
func wasmimport_PerimeterOutputBuilderPushReorderedWallLoop(params *wasmimport_PerimeterOutputBuilderPushReorderedWallLoop_params, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-output-builder.push-resolved-seam
//go:noescape
func wasmimport_PerimeterOutputBuilderPushResolvedSeam(self0 uint32, pos0 float32, pos1 float32, pos2 float32, wallIndex0 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-output-builder.push-seam-candidate
//go:noescape
func wasmimport_PerimeterOutputBuilderPushSeamCandidate(self0 uint32, pos0 float32, pos1 float32, pos2 float32, score0 float32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-output-builder.push-wall-loop
//go:noescape
func wasmimport_PerimeterOutputBuilderPushWallLoop(self0 uint32, wallLoop0 uint32, wallLoop1 uint32, wallLoop2 *geometry.Point3WithWidth, wallLoop3 uint32, wallLoop4 uint32, wallLoop5 *uint8, wallLoop6 uint32, wallLoop7 float32, wallLoop8 *WallFeatureFlag, wallLoop9 uint32, wallLoop10 uint32, wallLoop11 *MaterialBoundarySegment, wallLoop12 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-output-builder.set-current-origin
//go:noescape
func wasmimport_PerimeterOutputBuilderSetCurrentOrigin(self0 uint32, objectId0 *uint8, objectId1 uint32, regionId0 *uint8, regionId1 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]perimeter-output-builder.set-infill-areas
//go:noescape
func wasmimport_PerimeterOutputBuilderSetInfillAreas(self0 uint32, areas0 *ExPolygon, areas1 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [resource-drop]slice-postprocess-builder
//go:noescape
func wasmimport_SlicePostprocessBuilderResourceDrop(self0 uint32)

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-postprocess-builder.set-path-z
//go:noescape
func wasmimport_SlicePostprocessBuilderSetPathZ(self0 uint32, region0 uint32, region1 *uint8, region2 uint32, region3 *uint8, region4 uint32, region5 *cm.Tuple[string, PaintValue], region6 uint32, pathIdx0 uint32, vertexIdx0 uint32, z0 float32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]slice-postprocess-builder.set-polygons
//go:noescape
func wasmimport_SlicePostprocessBuilderSetPolygons(self0 uint32, region0 uint32, region1 *uint8, region2 uint32, region3 *uint8, region4 uint32, region5 *cm.Tuple[string, PaintValue], region6 uint32, polys0 *ExPolygon, polys1 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [resource-drop]gcode-output-builder
//go:noescape
func wasmimport_GcodeOutputBuilderResourceDrop(self0 uint32)

//go:wasmimport slicer:ir-handles/ir-handles [method]gcode-output-builder.push-comment
//go:noescape
func wasmimport_GcodeOutputBuilderPushComment(self0 uint32, text0 *uint8, text1 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]gcode-output-builder.push-fan-speed
//go:noescape
func wasmimport_GcodeOutputBuilderPushFanSpeed(self0 uint32, value0 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]gcode-output-builder.push-move
//go:noescape
func wasmimport_GcodeOutputBuilderPushMove(self0 uint32, cmd0 uint32, cmd1 float32, cmd2 uint32, cmd3 float32, cmd4 uint32, cmd5 float32, cmd6 uint32, cmd7 float32, cmd8 uint32, cmd9 float32, cmd10 uint32, cmd11 *uint8, cmd12 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]gcode-output-builder.push-raw
//go:noescape
func wasmimport_GcodeOutputBuilderPushRaw(self0 uint32, text0 *uint8, text1 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]gcode-output-builder.push-retract
//go:noescape
func wasmimport_GcodeOutputBuilderPushRetract(self0 uint32, length0 float32, speed0 float32, mode0 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]gcode-output-builder.push-temperature
//go:noescape
func wasmimport_GcodeOutputBuilderPushTemperature(self0 uint32, tool0 uint32, celsius0 float32, wait0 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]gcode-output-builder.push-tool-change
//go:noescape
func wasmimport_GcodeOutputBuilderPushToolChange(self0 uint32, afterEntityIndex0 uint32, fromTool0 uint32, toTool0 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]gcode-output-builder.push-unretract
//go:noescape
func wasmimport_GcodeOutputBuilderPushUnretract(self0 uint32, length0 float32, speed0 float32, mode0 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]gcode-output-builder.push-z-hop
//go:noescape
func wasmimport_GcodeOutputBuilderPushZHop(self0 uint32, afterEntityIndex0 uint32, hopHeight0 float32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [resource-drop]layer-collection-builder
//go:noescape
func wasmimport_LayerCollectionBuilderResourceDrop(self0 uint32)

//go:wasmimport slicer:ir-handles/ir-handles [method]layer-collection-builder.get-ordered-entities
//go:noescape
func wasmimport_LayerCollectionBuilderGetOrderedEntities(self0 uint32, result *cm.List[OrderedEntityView])

//go:wasmimport slicer:ir-handles/ir-handles [method]layer-collection-builder.set-entity-order
//go:noescape
func wasmimport_LayerCollectionBuilderSetEntityOrder(self0 uint32, items0 *cm.Tuple[uint32, bool], items1 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [resource-drop]support-output-builder
//go:noescape
func wasmimport_SupportOutputBuilderResourceDrop(self0 uint32)

//go:wasmimport slicer:ir-handles/ir-handles [method]support-output-builder.push-interface-path
//go:noescape
func wasmimport_SupportOutputBuilderPushInterfacePath(self0 uint32, path0 *geometry.Point3WithWidth, path1 uint32, path2 uint32, path3 *uint8, path4 uint32, path5 float32, isTopInterface0 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]support-output-builder.push-raft-path
//go:noescape
func wasmimport_SupportOutputBuilderPushRaftPath(self0 uint32, path0 *geometry.Point3WithWidth, path1 uint32, path2 uint32, path3 *uint8, path4 uint32, path5 float32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]support-output-builder.push-support-path
//go:noescape
func wasmimport_SupportOutputBuilderPushSupportPath(self0 uint32, path0 *geometry.Point3WithWidth, path1 uint32, path2 uint32, path3 *uint8, path4 uint32, path5 float32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [method]support-output-builder.set-current-origin
//go:noescape
func wasmimport_SupportOutputBuilderSetCurrentOrigin(self0 uint32, objectId0 *uint8, objectId1 uint32, regionId0 *uint8, regionId1 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport slicer:ir-handles/ir-handles [resource-drop]paint-region-layer-view
//go:noescape
func wasmimport_PaintRegionLayerViewResourceDrop(self0 uint32)

//go:wasmimport slicer:ir-handles/ir-handles [method]paint-region-layer-view.get-custom-regions
//go:noescape
func wasmimport_PaintRegionLayerViewGetCustomRegions(self0 uint32, moduleId0 *uint8, moduleId1 uint32, result *cm.List[SemanticRegion])

//go:wasmimport slicer:ir-handles/ir-handles [method]paint-region-layer-view.get-regions
//go:noescape
func wasmimport_PaintRegionLayerViewGetRegions(self0 uint32, semantic0 uint32, semantic1 *uint8, semantic2 uint32, result *cm.List[SemanticRegion])

//go:wasmimport slicer:ir-handles/ir-handles [method]paint-region-layer-view.layer-index
//go:noescape
func wasmimport_PaintRegionLayerViewLayerIndex(self0 uint32) (result0 uint32)

//go:wasmimport slicer:ir-handles/ir-handles [method]paint-region-layer-view.lightning-tree-segments
//go:noescape
func wasmimport_PaintRegionLayerViewLightningTreeSegments(self0 uint32, objectId0 *uint8, objectId1 uint32, regionId0 *uint8, regionId1 uint32, result *cm.List[cm.List[Point3WithWidth]])

//go:wasmimport slicer:ir-handles/ir-handles [method]paint-region-layer-view.support-plan-segments
//go:noescape
func wasmimport_PaintRegionLayerViewSupportPlanSegments(self0 uint32, objectId0 *uint8, objectId1 uint32, regionId0 *uint8, regionId1 uint32, result *cm.List[cm.List[Point3WithWidth]])
