[package]
name = "sdk-host-bridge-guest"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.60.0"
slicer-sdk = { path = "../../../slicer-sdk" }
slicer-ir  = { path = "../../../slicer-ir" }
slicer-schema = { path = "../../../slicer-schema" }

[workspace]
