//! Proc-macros for the ModularSlicer SDK.
//!
//! This crate provides:
//! - `#[slicer_module]` - Transforms `impl LayerModule for T` into WIT export bindings
//! - `#[module_test]` - Test wrapper with mock host setup

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::{parse_macro_input, ItemFn, ItemImpl, ReturnType};

/// Known stage method names and their corresponding pipeline stage IDs.
const STAGE_METHODS: &[(&str, &str)] = &[
    ("run_infill", "Layer::Infill"),
    ("run_perimeters", "Layer::Perimeters"),
    ("run_wall_postprocess", "Layer::PerimetersPostProcess"),
    ("run_infill_postprocess", "Layer::InfillPostProcess"),
    ("run_slice_postprocess", "Layer::SlicePostProcess"),
    ("run_support", "Layer::Support"),
    ("run_support_postprocess", "Layer::SupportPostProcess"),
    ("run_path_optimization", "Layer::PathOptimization"),
    ("run_mesh_analysis", "PrePass::MeshAnalysis"),
    ("run_layer_planning", "PrePass::LayerPlanning"),
    ("run_mesh_segmentation", "PrePass::MeshSegmentation"),
    ("run_paint_segmentation", "PrePass::PaintSegmentation"),
    ("run_finalization", "PostPass::LayerFinalization"),
    ("run_gcode_postprocess", "PostPass::GCodePostProcess"),
    ("run_text_postprocess", "PostPass::TextPostProcess"),
];

/// The `#[slicer_module]` attribute macro.
///
/// Applied to an `impl LayerModule for T` block, this macro:
/// 1. Introspects the impl block to find stage methods (`run_infill`, `run_perimeters`, etc.)
/// 2. Validates that at most one stage method is present in the impl
/// 3. Generates WIT export helper methods
/// 4. Wires up `on-print-start` / `on-print-end` lifecycle wrappers
///
/// # Example
///
/// ```ignore
/// use slicer_sdk::prelude::*;
///
/// pub struct MyInfillModule;
///
/// #[slicer_module]
/// impl LayerModule for MyInfillModule {
///     fn on_print_start(config: &ConfigView) -> Result<Self, ModuleError> {
///         Ok(Self)
///     }
///
///     fn run_infill(
///         &self,
///         layer_index: u32,
///         regions: &[SliceRegionView],
///         output: &mut InfillOutputBuilder,
///         config: &ConfigView,
///     ) -> Result<(), ModuleError> {
///         // Implementation
///         Ok(())
///     }
/// }
/// ```
#[proc_macro_attribute]
pub fn slicer_module(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let input = parse_macro_input!(item as ItemImpl);

    let self_ty = &input.self_ty;

    // Detect stage methods in the impl block
    let detected_stages = detect_stage_methods(&input);

    // Validate: at most one stage method per impl block
    if detected_stages.len() > 1 {
        let names: Vec<&str> = detected_stages.iter().map(|(name, _)| *name).collect();
        let msg = format!(
            "slicer_module: impl block contains multiple stage methods: {}. \
             A module must implement exactly one stage function.",
            names.join(", ")
        );
        return syn::Error::new_spanned(&input.self_ty, msg)
            .to_compile_error()
            .into();
    }

    let expanded = generate_slicer_module_impl(&input, self_ty, &detected_stages);
    TokenStream::from(expanded)
}

/// Detect which `run_*` stage methods are present in the impl block.
/// Returns a list of (method_name, stage_id) pairs.
fn detect_stage_methods<'a>(input: &'a ItemImpl) -> Vec<(&'static str, &'static str)> {
    let mut found = Vec::new();

    for item in &input.items {
        if let syn::ImplItem::Fn(method) = item {
            let method_name = method.sig.ident.to_string();
            for &(stage_method, stage_id) in STAGE_METHODS {
                if method_name == stage_method {
                    found.push((stage_method, stage_id));
                }
            }
        }
    }

    found
}

/// Generate the expanded implementation for #[slicer_module]
fn generate_slicer_module_impl(
    input: &ItemImpl,
    self_ty: &syn::Type,
    detected_stages: &[(&str, &str)],
) -> TokenStream2 {
    let type_name_str = quote!(#self_ty).to_string();

    // Preserve the original impl block
    let original_impl = quote! { #input };

    let has_stage = !detected_stages.is_empty();

    let (stage_name_literal, _stage_method_ident) = if let Some(&(method, stage)) =
        detected_stages.first()
    {
        (
            quote! { #stage },
            Some(syn::Ident::new(method, proc_macro2::Span::call_site())),
        )
    } else {
        (quote! { "" }, None)
    };

    let generated_methods = quote! {
        impl #self_ty {
            /// Module entry point marker — indicates the module is properly registered.
            /// Generated by #[slicer_module].
            #[doc(hidden)]
            pub fn __slicer_module_marker() -> bool {
                true
            }

            /// Returns true if the impl block contains a recognized stage method.
            /// Generated by #[slicer_module].
            #[doc(hidden)]
            pub fn __slicer_has_stage_function() -> bool {
                #has_stage
            }

            /// Returns true if the module is WIT export compatible.
            /// Generated by #[slicer_module].
            #[doc(hidden)]
            pub fn __slicer_wit_compatible() -> bool {
                true
            }

            /// Returns the pipeline stage name detected in the impl block.
            /// Empty string if no stage method was found.
            /// Generated by #[slicer_module].
            #[doc(hidden)]
            pub fn __slicer_stage_name() -> &'static str {
                #stage_name_literal
            }

            /// Returns the module type name as a string.
            /// Generated by #[slicer_module].
            #[doc(hidden)]
            pub fn __slicer_type_name() -> &'static str {
                #type_name_str
            }
        }
    };

    quote! {
        #original_impl
        #generated_methods
    }
}

/// The `#[module_test]` attribute macro.
///
/// Wrapper around `#[test]` that automatically sets up the mock host,
/// installs the SDK's test panic handler, and resets global state between tests.
///
/// This macro transforms a test function to:
/// 1. Add the `#[test]` attribute
/// 2. Call `__slicer_test_reset_global_state()` at the start
/// 3. Call `__slicer_test_install_panic_handler()` at the start
/// 4. Call `__slicer_test_mock_host_setup()` at the start
/// 5. Execute the original function body
/// 6. Call `__slicer_test_mock_host_teardown()` at the end (via drop guard)
///
/// # Constraints
/// - Only parameterless functions are supported (matching `#[test]` behavior)
/// - Async functions are not supported
/// - Supports `Result<(), E>` return types
///
/// # Example
///
/// ```ignore
/// #[module_test]
/// fn test_my_module() {
///     // Test code with mock host automatically available
/// }
/// ```
#[proc_macro_attribute]
pub fn module_test(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let input = parse_macro_input!(item as ItemFn);
    let expanded = generate_module_test_impl(&input);
    TokenStream::from(expanded)
}

/// Generate the expanded implementation for #[module_test]
fn generate_module_test_impl(input: &ItemFn) -> TokenStream2 {
    let fn_name = &input.sig.ident;
    let fn_vis = &input.vis;
    let fn_attrs = &input.attrs;
    let fn_block = &input.block;
    let fn_output = &input.sig.output;

    // Determine if the function returns a Result or ()
    let has_return_type = !matches!(fn_output, ReturnType::Default);

    // Generate the wrapper code with setup/teardown
    // We use a guard struct to ensure teardown is called even on panic
    if has_return_type {
        // For functions returning Result<(), E>
        quote! {
            #(#fn_attrs)*
            #[test]
            #fn_vis fn #fn_name() #fn_output {
                // Teardown guard - ensures teardown is called on drop
                struct __SlicerTestGuard;
                impl Drop for __SlicerTestGuard {
                    fn drop(&mut self) {
                        __slicer_test_mock_host_teardown();
                    }
                }

                // Setup sequence (order matters per docs/05_module_sdk.md)
                __slicer_test_reset_global_state();
                __slicer_test_install_panic_handler();
                __slicer_test_mock_host_setup();

                // Create guard for teardown on drop
                let _guard = __SlicerTestGuard;

                // Execute original function body
                #fn_block
            }
        }
    } else {
        // For functions returning ()
        quote! {
            #(#fn_attrs)*
            #[test]
            #fn_vis fn #fn_name() {
                // Teardown guard - ensures teardown is called on drop
                struct __SlicerTestGuard;
                impl Drop for __SlicerTestGuard {
                    fn drop(&mut self) {
                        __slicer_test_mock_host_teardown();
                    }
                }

                // Setup sequence (order matters per docs/05_module_sdk.md)
                __slicer_test_reset_global_state();
                __slicer_test_install_panic_handler();
                __slicer_test_mock_host_setup();

                // Create guard for teardown on drop
                let _guard = __SlicerTestGuard;

                // Execute original function body
                #fn_block
            }
        }
    }
}
